### ISSUE TITLE
dependencies.json file missing from 1.0 and 1.1 branches

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#114]
This sim doesn't seem to have the dependencies.json file checked in for previous releases.  This appears to be the case for both the 1.0 and 1.1 branches.  These should probably be pulled from the web site and checked in here so that maintenance releases can be done if needed.

**Comment by jbphet** [comment]
Hmmm.  I just looked on the web site, and the live version is 1.0.0.  Looking on spot.colorado.edu shows what appears to be a number of 1.1 release candidates from around June 2014, but it doesn't appear that the 1.1 release process was ever finished.  I know that @samreid is a bit swamped right now, but someone should be assigned to sort this out and check in the dependencies so that maintenance releases can be made if needed.  I'll assign to @ariel-phet for now, he can mark for discussion in developer meeting if he needs input from the developers.

**Comment by samreid** [comment]
Would an alternative be to do the S2105R republication?

**Comment by jessegreenberg** [comment]
In #130, it was decided that the 1.2 branch be merged into 1.1 branch so that 1.1 release process was completed.

Balloons and Static Electricity 1.1 was republished for S2015R with dependencies.json, so maintenance releases can go out as necessary.  This issue can be closed.
