### ISSUE TITLE
Long, Double string tests

### ISSUE THREAD

**Issue by elisemorgan** [phetsims/balloons-and-static-electricity#115]
Related to https://github.com/phetsims/tasks/issues/479

Test device: Personal Mac

Operating System: OS X 10.10.5

Browser: Chrome 47.0.2526.111

Problem description: Overlap w/ Long and Double string tests

Steps to reproduce: Perform string tests

Severity:

Screenshots:
Long:
![screen shot 2016-01-20 at 3 05 18 pm](https://cloud.githubusercontent.com/assets/12610678/12464755/cfcfad66-bf87-11e5-9fd9-667066020c92.jpg)

Double:
![screen shot 2016-01-20 at 3 05 49 pm](https://cloud.githubusercontent.com/assets/12610678/12464760/d7bf1610-bf87-11e5-9f50-a07676dc00c0.jpg)

Troubleshooting information (do not edit):
Name: ‪Balloons and Static Electricity‬:‪Balloons and Static Electricity‬
URL: http://phettest.colorado.edu/balloons-and-static-electricity/balloons-and-static-electricity_en.html?ea&brand=phet&stringTest=double
Version: 1.2.0-dev.1 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 Safari/537.36
Language: en-US
Window: 1275x654
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
Fixed in the above commit.  

For stringTest=double:

![screenshot_12](https://cloud.githubusercontent.com/assets/3046552/13060567/ce468452-d3ef-11e5-8eae-1aa836f6b6a2.png)

For stringTest=long:

![screenshot_11](https://cloud.githubusercontent.com/assets/3046552/13060581/d614b32a-d3ef-11e5-9d61-f8ac4ec8665f.png)

**Comment by pixelzoom** [comment]
This can be verified in:
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-dev.3/balloons-and-static-electricity_en.html

**Comment by jessegreenberg** [comment]
Balloons and Static Electricity went through RC and i18n testing for the redeploy.  All string tests passed. Closing.
