### ISSUE TITLE
User suggestion: uncharged balloon behavior

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#126]
I have one comment on the “Balloons and Static Electricity” simulation. It would be useful to improve upon the behavior of the balloons while uncharged. This behavior is no completely natural, eg. an uncharged balloon sticks to the wall and the sweater. This all the more unfortunate as this simulation is otherwise suited for younger children where “realism” is all the more important.

**Comment by ariel-phet** [comment]
@oliver-phet there is nothing we can "improve" here in terms of the code. We could however make a not in the teacher tips if not already there.

The "uncharged" balloon does not stick to the wall. It just stays wherever you place it. Only when charged does it feel forces. Perhaps forward me this suggestion, because perhaps I do not fully understand the issue being raised?

**Comment by ariel-phet** [comment]
Responded to user:

> I am not sure we fully understand your suggestion for improvement.
> 
> When the simulation starts up the balloon is uncharged. It has no horizontal forces acting on it, so if you place it first on the wall, it will stay there, but if you move it slightly off the wall still uncharged it will remain off the wall. We do not consider this behavior "sticking" to the wall; you are free to place the balloon wherever you want until it gets charged...once charged it begins to experience electrical attraction and repulsion, and then its position is determined by the outcome of the forces place on it.
> 
>  The simulation would get very confusing if the uncharged balloon always floated back to the center point...there are not forces to cause this action and it would muddle the idea of the electrical forces causing attraction and repulsion.
> 
> Could you let us know if that makes sense, or if you had something different in mind?

**Comment by arouinfar** [comment]
I just saw this issue and clarified this point in the teacher tips. 

@ariel-phet this issue seems to have been handled and doesn't currently have anyone assigned to it. Can it be closed?

**Comment by ariel-phet** [comment]
@arouinfar yes, I think so, I was waiting to hear back from the user, but if they come back with something not addressed in the teacher tips, I will reopen. Thanks.
