### ISSUE TITLE
Consider hanging balloons from the ceiling

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balloons-and-static-electricity#127]
In #117, @oliver-phet reported a user's concern

> Ideally, assuming the balloon is filled with helium, it should drift back upwards after being released, since it has not received any charge.

@ariel-phet  responded

> This is a very intentional choice. We don't want to conflate the idea of a buoyant force on the balloon with the electric forces on the balloon. It would be a very confusing user experience if the uncharged balloon floated up. Nobody claimed the balloons were helium filled, but the string is assumed to be "magic" and keeps the correct tension to keep the balloon in place. We will not address, but we can make a note in the teaching tips.

@arouinfar created the teacher tips, and included the following

> Uncharged balloons will stay wherever they are placed, and the string attached to them will maintain the appropriate tension to hold the balloon in place. The buoyant force acting on the balloons is intentionally not modeled in this simulation, so that students do not conflate the idea of the buoyant force on the balloon with the electric forces on the balloon.

@terracoda commented

> This is an important detail to add to the scene description in the accessible version of this simulation. I thought I should describe the balloons as helium balloons, but I refrained because they do not behave like helium balloons. Nice to know the string is "magic". Can we consider reversing the situation, so that the balloons are hanging from the ceiling? It might be more "implicitly" obvious that they are not actually helium balloons, then, although the string would still be "magic."

I like @terracoda's suggestion to hang the balloons from the ceiling. I think it would definitely help cue that the balloons are not helium filled (or that the buoyant force is not present/shown), which is an important model simplification. I think this is a change we should consider when redeploying this sim.

**Comment by arouinfar** [comment]
Perhaps if this change request is not overly difficult (or could be done in a quick-and-dirty, though less maintainable way), it could be done in a branch and we could interview students to see how they interpret the balloons hanging from the ceiling.

**Comment by jessegreenberg** [comment]
Changing the focal point is very simple, here is what it looks like if we just change the position of the strings.

![balloon-ceiling](https://cloud.githubusercontent.com/assets/6396244/12965189/86a1a0aa-d011-11e5-8047-d4aa28040429.PNG)

Right now, there isn't a ceiling.  If the ceiling is a graphic, it might also need charges like the wall.  Was the vision to rotate the balloon 180 degrees as well?

**Comment by arouinfar** [comment]
Thanks @jessegreenberg! I don't think there necessarily needs to be a ceiling graphic. We should, however, rotate the balloons 180* otherwise it may perpetuate the idea that the balloons are helium filled.

**Comment by jessegreenberg** [comment]
Sounds good @arouinfar.  My concern with no ceiling is that it might look strange in some screen resolutions.

![anchor](https://cloud.githubusercontent.com/assets/6396244/12965622/d7612c88-d014-11e5-9dab-18df6fa1d03b.PNG)

After rotating the balloon, it looks like we would also need to change the charge distribution along the balloon edge.

**Comment by jessegreenberg** [comment]
> it looks like we would also need to change the possible charge locations along the balloon edge.

**Comment by arouinfar** [comment]
Good point @jessegreenberg. Perhaps we could try adding gray stroke across the top of the screen that matches the one at the top of the wall to make it appear that the string is attached to something. I don't think we want to deal with a true ceiling that would act like a polarizable dielectric (like the wall).

![image](https://cloud.githubusercontent.com/assets/8419308/12965805/649f98d6-d016-11e5-8d11-b2bc841c7c0c.png)

It also looks like the balloon's charges should be collectively rotated 180*, though I imagine that's quite a bit more difficult than rotating artwork. Perhaps a quicker solution would be to shift the electrons down a little bit so that they fit within the boundary of the balloon, though I'm hesitant to spend much time pixel polishing. I think it'd be better to have something acceptable-looking go in front of a few students for interviews to see how it goes, and then have a deeper discussion with the design team to see if this is a change we'd actually like to make.

@jessegreenberg is there a relatively quick way to move the charges so that they are within the boundary of the balloon? That would be the only outstanding issue that would prevent me from putting this sim in front of students. (I would avoid using a narrow aspect ratio that reveals the floating string.) I am going to be scheduling ~3 interviews sometime Monday-Wed of next week for Bending Light & Pendulum Lab. This seems like a pretty quick sim that I could throw in at the end of the interviews.

**Comment by jessegreenberg** [comment]
Sure, that could be done quickly.  Assigning issue to me to invert the locations so they are in the balloon.

**Comment by jessegreenberg** [comment]
Here is a dev version with these changes: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-dev.2/balloons-and-static-electricity_en.html

@arouinfar please let me know if anything else needs to change before testing.

**Comment by terracoda** [comment]
Looking good! @jessegreenberg and @arouinfar. The shading on the balloon needs to be adjusted if we assume the light is still coming from the top.

Regarding the ceiling, I agree we might eventually need a ceiling. Honestly, I thought there was one. @jessegreenberg, perhaps you can make the top of the sim display like the bottom of the sim. The balloon doesn't travel beyond the top of the wall anyways, even when there is extra blue space.

**Comment by jessegreenberg** [comment]
Good point @terracoda, I forgot about the balloon shading!  Rotation of the image alone will be insufficient.  If we do end up with this implementation, we will need new images for the balloons.

A black border along the top could work for symmetry with the navigation bar.  Depending on student interviews, we could certainly add something like this, or the line suggested by @arouinfar.

**Comment by arouinfar** [comment]
@jessegreenberg dev.2 will work nicely for interviews. Thanks!

I agree with @terracoda that will will need to fix the shading on the balloon if we end up taking this approach, but it's fine as is for interviewing.

@jessegreenberg having the black border run along the top could also work nicely. Great suggestion!

**Comment by jessegreenberg** [comment]
Backed out of these changes for the redeploy, we can add them back in after student testing.

**Comment by arouinfar** [comment]
@jessegreenberg can you completely remove the string and rotate the balloon/charges so they are upright again? Based on earlier interviews, I'd like to see how students interpret a completely disconnected balloon.

**Comment by jessegreenberg** [comment]
@arouinfar Sure, here is a new dev version:

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-dev.4/balloons-and-static-electricity_en.html

**Comment by terracoda** [comment]
@arouinfar, a disconnected balloon is also a nice way to suggest it is not  a helium balloon.

**Comment by arouinfar** [comment]
@jessegreenberg thanks! We'll be interviewing on this version too.

**Comment by arouinfar** [comment]
We will still need to interview on this sim a few more times before having a discussion with the design team about the next steps to be taken. A few other sims will have interviews scheduled in the near-ish future (Pendulum Lab & Neuron) and this sim will be used at the end of those interviews.

**Comment by jessegreenberg** [comment]
It sounds like a maintenance release of Balloons and Static Electricity is coming soon.  @arouinfar do you know if the string should be removed for the maintenance release?

**Comment by arouinfar** [comment]
@jessegreenberg, I think a string from the ceiling is a better option than removing the string, but I'll re-review the interview footage and make a suggestion by the end of the week.

**Comment by jessegreenberg** [comment]
Thanks!  Also pinging @jbphet in case he does the maintenance release, since this will need to be sorted first.

**Comment by terracoda** [comment]
I am also curious about students respond to no string at all.

**Comment by arouinfar** [comment]
We interviewed six students. The first four students saw two version of the sim -- the string attached to the top vs. bottom of the string. The last two saw all three versions of the sim -- including the no string option. 

The no-string option didn't feel very natural at all to the two students who tried it. I do not think we should publish a version without the string to the main website. I'm not sure what the goals are for the phet-io version currently being tested or how student interactions will be framed, so it may be perfectly acceptable there.

The students self-reported preference was split evenly between attaching the balloons to the ceiling vs. attaching the balloons to the ground. That said, 4/6 students were explicitly asked what gas they thought was in the balloons. All four students indicated that they believed the the balloons attached to the ground were helium-filled, while the balloons attached to the ceiling were air-filled. This is problematic, as we don't want students to conflate the buoyant and electrostatic forces. 

We have also received some teacher feedback about the balloon's behavior not matching that of a helium-filled balloon, which would indicate that it's not just students who have the expectation of a helium-filled ballon.

If we are to make a change to the published sim, I think we should attach the balloon to the ceiling. However, we'll need to add a black stroke to the top of the string or allow the balloon anchor point to float outside of the dev boundary, otherwise we'll end up with situations where the balloon doesn't look anchored to anything:

<img width="528" alt="screen shot 2017-01-30 at 6 25 21 pm" src="https://cloud.githubusercontent.com/assets/8419308/22448882/87f17cb2-e719-11e6-8422-1e13f60577ae.png">

**Comment by terracoda** [comment]
@arouinfar, if we go with strings from the top, I suggest a visual barrier that looks like a bar that the strings are tied to. The reason being is that I think we need to make it look much different from a ceiling. If it looks like a ceiling, the ceiling should behave somewhat similar to a wall, right?

**Comment by jbphet** [comment]
@arouinfar said:
>  I do not think we should publish a version without the string to the main website. I'm not sure what the goals are for the phet-io version currently being tested or how student interactions will be framed, so it may be perfectly acceptable there.
I need someone to make a call on this pretty much immediately for the phet-io version that is currently in test.  It has no strings for the balloons, and I need to know if this is acceptable or needs to be changed prior to release.  I'm not sure whose call this is to make, so I'll assign to @ariel-phet for now.

In my opinion, attaching the balloon to the ceiling doesn't solve the problem of the balloon not matching people's expectations.  If the anchor point of the string is at the *bottom* of the simulation frame, people assume the balloon is full of helium and should thus move back to the point above where the string is attached when it is released (and is not charged), because that matches their real world experience.  If the anchor point was at the *top* of the frame, people would expect an uncharged balloon to go to the point immediately below the attachment point when released (again assuming it is uncharged), because that also matches their real world experience.  Situations in which a balloon is moved and then released, and then stays in exactly the same place are, shall we say, extremely rare in real life, regardless of where the string is attached.  So, we either need to get comfortable with the simplifying assumptions made by this sim or rewrite to be more consistent with the real world.  Since a rewrite is very unlikely to happen given our current priorities, and since @arouinfar said "[t]he no-string option didn't feel very natural at all to the two students who tried it", I think we should go back to having the string come from the bottom.  At least in that case we don't have to figure out how to add in a ceiling.

**Comment by ariel-phet** [comment]
@jbphet perhaps there is another alternative....

Attach balloons to a string from the bottom, but have a somewhat "loose string" the same way we do for cables on meter bodies like in concentration. I think the main visual that gives the impression of a helium balloon is the string is very "taut" in this visual, which makes you feel like there is a strong upward force. I think a somewhat loose string would better express the idea of "neutrally buoyant" and might feel natural and not cause other issues with the sim. Would that be tough to implement and take for a test drive?

**Comment by jbphet** [comment]
Let's see how much time I have left today after addressing the issues on the current phet-io RC and, if I can get to it, I'll give it a try.  Otherwise we have to decide to wait a week to provide @emily-phet with this release, put the strings back, or leave them out.

**Comment by arouinfar** [comment]
@jbphet @ariel-phet A student's expectation that the balloon is helium-filled is completely reasonable, given their everyday interactions. However, I think teachers need to be aware of these ideas to productively facilitate the use of the sim. If teachers also believe the balloon is helium-filled and buoyant, then there's a problem.

@oliver-phet can you do a quick search of phethelp email and see if you've had any teachers ask a similar question to the one in #117? I think the Teacher Tips adequately describe the model simplifications, so I wonder if teachers are still writing in with concerns about the behavior of the "helium" balloon.

If no one's been writing in, then chances are the Teacher Tips have done the job, and we don't necessarily need to worry about changing the sim. I do like @ariel-phet's alternative suggestion of the loose string, though.

**Comment by ariel-phet** [comment]
@jbphet @arouinfar agreed that at worst, keeping the strings attached to the bottom has generally worked for a long time, and the concerns it raises are addressed in the teacher-tips. I would be curious to see the loose string suggestion implemented sometime, but certainly the easiest would be to leave the strings on the bottom and taut as in the published version.

**Comment by terracoda** [comment]
@jbphet, excellent points! We have the same problem in either case.

For the record, I have not described the string at all in the non-visual version of the simulation. It has not yet been an issue. In an early interview with live description, I think there was one person who asked about whether the balloon was falling to the floor when two balloons were repelling.

I also, like the idea of a loser looking string.

**Comment by oliver-phet** [comment]
@arouinfar I looked through the entire history of phethelp emails and #117 is the only email we've had specific to this issue.

**Comment by arouinfar** [comment]
Thanks @oliver-phet! 

@jbphet I think we can keep the strings as-is for now.

@ariel-phet should I move the loose string suggestion to a new issue and close this one?

**Comment by ariel-phet** [comment]
@arouinfar yes, please move that suggestion to a new issue

**Comment by arouinfar** [comment]
Done!
