### ISSUE TITLE
Inconsistency of content in Visual Sim and PDOM

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#132]
Currently, the Wall heading and Wall descriptions remained in the PDOM after the user removes the Wall by pressing the Remove Wall button.

All evidence of the Wall needs to be hidden from AT while it is in a "removed" state. You might need to use both ARIA and CSS to do this.

Related issue, where we place the following text strings describing the states matters. Currently the content is out order somewhat.

1. _Wall removed from Play Area_ and 
2. _Green Balloon added to Play Area_

I suggest keeping the state text close to the associates buttons for now.

**Comment by jessegreenberg** [comment]
In commit above, the wall domElement is hidden when the WallNode is invisible.

**Comment by jessegreenberg** [comment]
> Related issue, where we place the following text strings describing the states matters. Currently the content is out order somewhat.

@terracoda could you please clarify what you mean by this?  Are you referring to the order that the screen reader announces the aria-live content?  Or the location of the paragraph's containing the update?

**Comment by jessegreenberg** [comment]
In the commit above, I moved the live description paragraph for the wall under the containing div of the 'add wall' button.

**Comment by terracoda** [comment]
Thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
Absolutely!  Location of live paragraph fixed, closing.
