### ISSUE TITLE
Performance issues when AT is active

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#137]
AT generally use a significant portion of the CPU.  This means that performance can be an issue when both AT and the simulation are in use.

In a user test today, we noticed that there can be significant delays for the auditory descriptions when the user is interacting with the simulation.  This can be disorienting and frustrating for the user.  In the test case, the user missed several descriptions and thought the sim was seizing up and continued to navigate to other screen elements.  When the AT finally caught up with the user, it had skipped multiple descriptions.

**Comment by jobara** [comment]
@jhung had some thoughts on a DOM only view; perhaps it could be toggled by a user if they are having performance issues.

**Comment by jessegreenberg** [comment]
Duplicate of #288, closing.
