### ISSUE TITLE
Balloon velocity/force does not reset when picked up wth keyboard nav

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balloons-and-static-electricity#140]
Picking up a balloon does not reset its "velocity" (if that's even how the underlying code works). For instance:
1. Remove the wall.
2. Pick up a balloon and give it a little charge.
3. Move the balloon to the far right of the screen.
4. Drop and quickly pick up the balloon. Simply pressing spacebar twice rapidly works.
5. Repeat 3 & 4. Sequential drops will have the balloon moving faster and faster toward the sweater.

Seen on Win 10 browsers. For phetsims/tasks/issues/566.

**Comment by jessegreenberg** [comment]
Thanks for catching this @phet-steele, fixed in above commit.  Closing.
