### ISSUE TITLE
need translations for new strings

### ISSUE THREAD

**Issue by vasily-shakhov** [phetsims/balloons-and-static-electricity#15]
In html5 version new string appeared. Need translate them to all languages.
List below (from balloons-and-static-electricity-strings.js):

            "BalloonApplet.removeWall": "Remove<br/> Wall",
            "BalloonApplet.addWall": "Add<br/> Wall",
            "BalloonApplet.resetBalloon": "resetBalloon",
            "BalloonApplet.resetBalloons": "resetBalloons"

**Comment by samreid** [comment]
Marking for S2015R since that pertains to i18n.

**Comment by pixelzoom** [comment]
This will be handled by translators via Rosetta when the sim is published with translation support. There's no need for PhET to do anything for new strings.

Closing.
