### ISSUE TITLE
Test static live regions

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#151]
@jobara mentioned that he had good luck with live regions when the region was added to the main html content before the sim is loaded.  It is possible that screen readers are having a difficult time with dynamic descriptions because our live regions are all added by the simulation.  It is possible that the screen reader is not registering observers to live regions that are added by the sim.

We should see if behavior of live regions is better if added statically (outside of sim).

**Comment by terracoda** [comment]
@jessegreenberg, just listene a little and this sounds promising. Have you actually added a few new descriptions as well as adding the aria-live region to the main html? I am hearing more descriptions.

**Comment by jessegreenberg** [comment]
@terracoda I actually haven't been able to try this yet.  Any new descriptions could be new content I have added, but I am not sure.  Glad more are coming through!

**Comment by jessegreenberg** [comment]
@jobara, This works really well for screen readers.  I tested NVDA on Chrome and Firefox and JAWS on IE, we are hearing all aria-live content in balloons-and-static-electricity.

One thing I am noticing: polite utterances need their own DOM element to queue messages.  If we have a single element with aria-live='polite', only the final text content will be read rather than the change in text as content changes.  For balloons-and-static-electricity, we will need ~6 elements with polite role in the top level html file for the sim.

Another thing I notice is that polite messages in the queue are read LIFO in Chrome and FIFO in IE and Firefox.

**Comment by jessegreenberg** [comment]
> we will need ~6 elements with polite role in the top level html file for the sim.

Or we could package all content into a single string and dispatch it to the aria-live element when ready?  Then we wouldn't have multiple 'polite' elements in the top level html file, and the order of messages would be platform independent.

**Comment by jessegreenberg** [comment]
We can begin to look at how to add these types of elements to the top level html file.  They will probably need to be added to sim.html and sim-development.html for access in build and RequireJS.

**Comment by terracoda** [comment]
@jessegreenberg, this is great news. Thanks @jobara! I can help with the HTML.

**Comment by terracoda** [comment]
@jessegreenberg, let me know when there is a new instance :-)

**Comment by jessegreenberg** [comment]
Hmm, still wonky behavior with Chrome + NVDA.  When setting textContent of an aria-live element to 
'‪Yellow Balloon‬ released against lower wall. No change in position. No change in charge'

Sometimes I will hear 'against lower wall', other times I will hear 'low'.  Other times I will hear nothing.

**Comment by jessegreenberg** [comment]
Still great in Firefox!

**Comment by jessegreenberg** [comment]
Maybe because focus transitions in this case?  Focus is moving to another element when a bunch of utterances are added to the queue.

**Comment by jessegreenberg** [comment]
We also still have the issue that if the user is dragging the balloon, many live alerts will be missed because keyboard interaction trumps aria-live.

**Comment by jessegreenberg** [comment]
Closing, we have determined that static live regions at the top of the body are necessary to receive aria-live updates.
