### ISSUE TITLE
Use of main vs article

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#170]
Asked in design doc, but placed here for documentation.

In an accessibility meeting we decided to use ```article``` instead of ```main``` to contain simulation content in order to support sims with multiple screens.  @terracoda can we do that in balloons-and-static-electricity?

**Comment by terracoda** [comment]
@jessegreenberg I did not realize a decision had been made on the use of article. I understand we can't have multiple main elements. The main element is optional. I'm not sure we need to change it to an article or just leave it out.

**Comment by terracoda** [comment]
@jessegreenberg Have you seen this HTML5 resource before?
http://html5doctor.com/downloads/h5d-sectioning-flowchart.png

It nicely demonstrates the decision making process for determining the correct block-level sectional element. According to this resource, articles can have sections, so I suppose we could try an article in place of main and see how it sounds to screen readers.

**Comment by jessegreenberg** [comment]
@terracoda, no I haven't, thanks! That is pretty neat!  According to that diagram, use of an article does seem appropriate.  We can proceed with that element for now.  Closing.
