### ISSUE TITLE
Performance terrible with VoiceOver + Safari

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#178]
VoiceOver seems to hang in VoiceOver when using Safari.  VoiceOver performs very well when used on the same machine with Chrome.

The sim itself has a high level of performance, (focus highlight is very responsive, balloon animations excellent), it is just the reading from VoiceOver which is slow.  It will read nothing, and then catch up by reading everything in rapid succession.

We might be setting DOM textContent every animation frame, would this overwhelm the reader?

**Comment by jessegreenberg** [comment]
I should note, testing on a MacBook Air.

**Comment by jessegreenberg** [comment]
Hmm, but the aria-live alerts seem to be announced rapidly. There is a substantial delay on reading content with arrow keys and when tabbing to a new input element.

**Comment by jessegreenberg** [comment]
Now performance is great.  Not sure what why.

**Comment by jessegreenberg** [comment]
After playing with the sim for a while, performance seems great.  Maybe some background task? Closing.

**Comment by jessegreenberg** [comment]
Reopening.  Performance is quite bad again, and it is not improving with time.

**Comment by jobara** [comment]
@jessegreenberg let me know if you'd like me to try this out on my machine and the details of what you were running to get the performance issues. My machine is going to be a bit faster than a MacBook Air though and it's running macOS Sierra.

**Comment by jessegreenberg** [comment]
Potentially useful information: VoiceOver says "Firefox Busy" very frequently when the sim is running in Firefox.

**Comment by jessegreenberg** [comment]
@terracoda reported that performance was great in Safari on a machine that was located at the Assets conference.  @jobara reported that performance was fine on his machine (MacOS Sierra).  @jhung also tested on his machine and verified that performance was in good shape ([I think] also MacOS Sierra).

**Comment by jessegreenberg** [comment]
I am no longer exhibiting this on Safari. Performance issues related to a11y will be discussed in #288.
