### ISSUE TITLE
JAWS reads 'blank' at the end of some content

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#181]

**Comment by jobara** [comment]
@jessegreenberg is there empty whitespace at the end of the text?

**Comment by jessegreenberg** [comment]
@jobara, yes that is a great point.  I will also see if there are any blank paragraphs in the DOM like ```<p></p>``` that are waiting for content to be populated.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, there is an interesting discussion on the WebAIM email list about "blank" being read out at the end of a lines. It seems more common in JAWS than NVDA and it seems like a user can adjust this setting, and perhaps we have to be particularly careful in "Application" mode when "normal screen behavior may not be in use."

[WebAIM Email Archive](http://webaim.org/discussion/mail_thread?thread=4067)

> Screen readers will report blank lines on a page. Perhaps this is what they mean? That's usually a legitimate piece of information though, caused by using ```<p>...</p>``` in the standard way. (Léonie)

> You can get a screen reader to announce a blank line if you have an empty block element (like the paragraph element) or a br element or a series of blank lines in a pre element. (TIM)

> Sounds like someone is giving this feedback for something very specific
where normal screen behavior may not be in use. (Hoffman)

This highlights the need to use correct punctuation like capitalization, commas, dashes and periods. It is information that can help with the overall meaning of the description.

And yes, I agree, we should not have any unneeded blanks or empty block elements lying about :-)

**Comment by jessegreenberg** [comment]
Adding high priority label to test and determine if this is still an issue.

**Comment by jessegreenberg** [comment]
After some google searching I  found this post:
https://www.reddit.com/r/Blind/comments/4cg78m/jaws_screen_reader_announcing_blank_after_each/

Seems reasonable, I will see if it happens after each paragraph.

**Comment by jessegreenberg** [comment]
Indeed, with this HTML JAWS reads "blank" after every paragraph, after the `ul`.
```html
<div tabindex="-1" id="436-499-966">
    <p tabindex="-1" id="436-499-966-967">This is an interactive sim. Descriptions change as you play with it. It has a Play Area and a Control Panel. The Play Area is a small room. The Control Panel has buttons, a checkbox, and radio buttons to change conditions in the room.</p>
    <ul tabindex="-1" id="436-499-966-968">
      ///
    </ul>
    <p tabindex="-1" id="436-499-966-973">Grab balloon to play.</p>
    <p tabindex="-1" id="436-499-966-974">If needed, checkout keyboard shortcuts under Sim Resources.</p>
</div>
```

**Comment by jessegreenberg** [comment]
The response from that post was
>That's the way it should work. JAWS indicates new paragraphs to the user by leaving a blank line between each one. If you test with NVDA you should notice it doesn't do this.

Though `reddit.com` is not the most trustworthy,  it matches what we have observed here. Closing this issue since it is not a bug but just the AT behavior. Pinging @terracoda so she is aware.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the ping!
