### ISSUE TITLE
Wall is described when invisible

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#185]
In an email, @terracoda said

> Moving right when there is no wall present, has the moving right "towards wall" descriptions.

**Comment by jessegreenberg** [comment]
I think this is fixed in the above commits @terracoda.  Will provide a new version shortly, if you notice any more references to the wall that shouldn't be there when the wall is invisible please let me know.

**Comment by terracoda** [comment]
Will do, @jessegreenberg.

**Comment by terracoda** [comment]
Yes, they are fixed.
I'll try to do more testing later.
Taliesin
