### ISSUE TITLE
If balloon is already on sweater, velocity should't be described

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#186]
@terracoda said 
>When the balloon is released on the sweater, I got "Moved quickly towards sweater." That might be a problem with my actual descriptions - not sure. It does not actually move, it just sticks.

**Comment by terracoda** [comment]
Thanks @jessegreenberg for opening this issue.

**Comment by jessegreenberg** [comment]
@terracoda I believe the above commit fixes this issue.  Closing.
