### ISSUE TITLE
Prepare accessible BASE for student testing

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#188]
We would like john-travoltage to be ready for student interviews the week of november 2. This issue will track preparation.

Initial checklist (subject to change)
- [x] A thorough internal review of the latest and greatest BASE and JT
- [x] Prioritize issues that must be completed before interviews
- [x] Work through any additional change requests
- [x] Another good (technical) discussion around how to conduct remote interviews
- [x] Discussion of how to conduct an interview (it would be great if someone could lead, ideally @terracoda if she isn’t traveling and feels ready for it)
- [x] Prioritize platforms and verify performance
- [x] Deploy version

**Comment by terracoda** [comment]
@jessegreenberg, this is issue for both JT and BASE, right?
I'd like to add descriptions edits to the list. Is this the appropriate place for that?

**Comment by jessegreenberg** [comment]
@terracoda, yes, there is an issue open in the john-travoltage repository as well (https://github.com/phetsims/john-travoltage/issues/122).

For the new descriptions, could you please create a new github issue describing the changes and assign it to me?  You can reference this issue in the new one if you wish by pasting the link to this issue in the description of the new one.

**Comment by terracoda** [comment]
@jessegreenberg, I created issue #193

**Comment by jessegreenberg** [comment]
Thanks @terracoda!

**Comment by jessegreenberg** [comment]
Closing, latest versions can be found at bit.ly/phetinterviews
