### ISSUE TITLE
a11y user review: JAWS repetition and suggested key commands

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#191]
We received this review of BASE from an informal test:

> I use JAWS 16 Professional edition. On the balloons and static electricity one, I see a drastic improvement from the 1st edition I tried which didn't give you and reference as to where the wall or sweater were. I have noticed though that it sometimes gets caught in a bit of a loop repeating where the balloon is in relation to other objects and it is sometimes hard to get it out of this loop to tell you where the charges are and what they are doing. Is there perhaps a key command I can use to get it to read off this information?

**Comment by jessegreenberg** [comment]
Version reviewed was http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-reader.6/balloons-and-static-electricity_en.html.

I have not observed any repetition in the latest version (http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-reader.7/balloons-and-static-electricity_en.html) hopefully latest implementations do not have this behavior, but I will try to reproduce the problem.

Hopefully, when repetition issue is fixed, charge information will be easier to find.  We decided to avoid global key commands because they make it impossible for the user to use default navigation strategies.  We could place additional help keys on the balloon and read help information on certain key presses.  While focus is on the draggable balloon 'i+c' could read all charge info.

@terracoda do you have any thoughts on this review or whether it would be beneficial or excessive to include a hotkey for charge information?

**Comment by terracoda** [comment]
@jessegreenberg, I haven't experienced repetition either with the latest version, but I was only successful with ChromeVox and Mac OS Sierra. However, another person was successful with VO and Safari and that user also did not experience any repetition. In much earlier prototypes we had a lot of repetition. That heavy repetition seems not to be present, but I have not tested with JAWS or NVDA.

__Getting Stuck__
As for getting stuck, I did get stuck on version 6 using VO, and I think we resolved that in version 7.

__Hot Keys - Need a Visual Button__
In terms of hotkeys for charge details or immediate information during a pause in interaction, we discussed ideas for this before, and yes, I think this would be useful. But I also think, it would be useful to get the visual button first before before adding more custom key commands. Recent users are not accessing the help option as earlier users did, so they are not finding and using the custom jump keys. The sim seems to be working well enough without them needing to access the help. However, the custom keys are still very useful for more advanced or quicker use of the sim and I think will likely be useful more complex sims. Users in earlier interviews did ask for a "How to use this sim" overview, so I think it is worth while getting a button or link in place for that.

**Comment by jessegreenberg** [comment]
Alright, thanks @terracoda.  In that case I think we can close this issue.  Design work for the visual button is being tracked in another issue.  I tested on JAWS and NVDA and saw no repetition.  It think this was caused by the way we were registering aria-live elements in the previous dev version.

> Recent users are not accessing the help option as earlier users did, so they are not finding and using the custom jump keys.

This is very helpful to know, thanks.
