### ISSUE TITLE
getQueryParameter in screen-reader.html

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#200]
Related to phetsims/query-string-machine#15.

I see yet-another implementation of `getQueryParameter` in screen-reader.html. 

• Why isn't this able to use the implementation in initialize-globals.js?
• Does this need to be converted to QueryStringMachine?

Assigning to @samreid (creator) and @jessegreenberg (most recent commit).

**Comment by jessegreenberg** [comment]
I took a look at this in https://github.com/phetsims/balloons-and-static-electricity/commit/2b145e2e16e1b92927e380ff4b757c71ba8ff1e3.  To answer the above:

> Why isn't this able to use the implementation in initialize-globals.js?

We probably could have, but didn't think of it at the time.  I think we could have gotten chipper.getQueryParameter by calling on it from the iframe's ```contentWindow``` after the sim had loaded.

> Does this need to be converted to QueryStringMachine?

In the commit above, I switched to using QueryStringMachine, it is really nice to also be able to use it in cases like this.

Closing.
