### ISSUE TITLE
The balloons should not be in an array

### ISSUE THREAD

**Issue by samreid** [phetsims/balloons-and-static-electricity#203]
During #201 I noticed that the balloons are in an array of 2 elements, and accessed like so:

```js
      var yellowBalloon = this.model.balloons[ 0 ];
      var greenBalloon = this.model.balloons[ 1 ];
```

The array was added in 51a8c3f02c40b83c27194c0b89b5808415be776e.

It would be better if the model had `model.yellowBalloon` and `model.greenBalloon`.

**Comment by samreid** [comment]
Tagging @jessegreenberg in case this interferes with accessibility instrumentation.

**Comment by samreid** [comment]
I added names in the above commit, with a get method for the array in the 6 or so places where we need to iterate over both balloons.  @jessegreenberg would you like to review?  I'm not sure how I should be testing the accessibility features (though I did try keyboard navigation and it didn't seem different after this change).

**Comment by jessegreenberg** [comment]
Thanks @samreid this looks great.  All accessibility features seem unchanged.
