### ISSUE TITLE
Use arrow keys to drag balloon with keyboard

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#205]
Should we add the ability to drag the balloon with the arrow keys when the screen reader is not in use?  When the screen reader is turned off, we have full control of the entire keyboard.

@emily-phet and @jessegreenberg like this idea, but it would be good to check with the rest of the team.  In the past, we have discussed that it could create an inconsistent experience if a blind student is working with sighted student.  Confusion might arise if one interaction pattern works on one platform but not another.

**Comment by jessegreenberg** [comment]
One idea was to try to detect when a screen reader is in use and set the interaction keys accordingly.  After some searching, it looks like this detecting screen reader use is not possible.  AT do not provide a user agent string, they work on top of the browser.  But all web discussion I could find about this is ~4 years old, so it would be good to verify.

Another option would be to enable the arrow keys and the WASD keys always.  When supported arrow keys would work intuitively.  When not supported, the descriptions would guide the user into using the WASD keys.

**Comment by jessegreenberg** [comment]
@jobara and @jhung agreed that it was not possible.  For privacy reasons, it was decided in the community that the content creators should not be aware of a user's disability.

In 11/15/16 we decided that we will enable both arrow keys and WASD keys.  As part of this we will have to determine how screen readers handle this, and determine how this impacts the navigation cues in the sim.

**Comment by jobara** [comment]
@jessegreenberg here's an interesting read on the subject https://www.marcozehe.de/2014/02/27/why-screen-reader-detection-on-the-web-is-a-bad-thing/

**Comment by jessegreenberg** [comment]
That is an excellent article @jobara, thanks very much!  That all makes a lot of sense.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, @jhung, @emily-phet, I agree that it would be useful to enable the arrow keys. It is my understanding that with the role application that screen readers should be releasing the Arrow keys to the web application anyways. It is possibly a bug that they do not all do that right now.

@jessegreenberg reported in another issue that NVDA (with Firefox) did actually release the Arrow keys, but Jaws did not. If we enable the Arrow keys we can do some more testing with the latest browsers and screen readers.

@jessegreenberg, do you have any tips on finding old issues. I found this somewhat related old closed issue about the Keyboard Help #105.

**Comment by terracoda** [comment]
@jobara, thanks for posting Marco's article. It is very interesting and a very important consideration. We shouldn't need to know if a person is using AT to make a good experience for them. It sure would be nice if all the vendors implemented standards in more similar ways, however :-)

**Comment by jessegreenberg** [comment]
From https://www.w3.org/TR/wai-aria/roles#application

In my opinion, the role is defined pretty loosely.  It seems like allowing arrow keys with role=application is sort of up to the AT's choice.  Here is a rundown of the latest testing with role=application and the arrow keys:

- NVDA + Firefox: Arrow keys work
- NVDA + Anything else: role=application doesn't work unless user explicitly enters 'forms mode'
- JAWS + IE: Arrow keys sort of work, but events are mangled such that they do not support drag and drop. (This might be a bug, but could have something to do with "Where appropriate, assistive technologies that typically intercept other standard device input events, such as touch screen input, could switch to an application browsing mode that passes some or all of those events through to the web application")
- JAWS + Anything else: I think 'insert + 3' trick works
- VoiceOver: Arrow keys do not work with role=applciation, they seem to be used by the virtual cursor always.

> do you have any tips on finding old issues.

@terracoda the only think I know of is to use github's search feature on the issues page.  You can search through open and closed issues by keyword or number.

**Comment by terracoda** [comment]
@jessegreenberg, I think the definition for __role application__ in the new [WAI-ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#application) fits our situation better, and is a little clearer. However, I do agree that the language is still vague. It says:

> assertive technology that intercept standard input events should switch to a mode that passes most or all standard input events through to the web application.

While reviewing the application role definition, I was reminded of some new attributes coming in 1.1 that might be helpful for us:

New properties aria-roledescription, aria-keyshortcuts, aria-placeholder, aria-current , aria-modal;

I am especially interested in [aria-roledescription](url) https://www.w3.org/TR/wai-aria-1.1/#aria-roledescription. I am thinking we can use that to replace the screen reader utterance, "Application" with something more meaningful like, "Draggable Yellow Balloon", or "Grabbed Yellow Balloon."

@jessegreenberg, @jobara would it be a good idea to start an issue for discussing the usefulness and applicability of new aria things?

**Comment by jessegreenberg** [comment]
@terracoda yes, that does sound useful!  I think the new repo https://github.com/phetsims/a11y-research/ would be a perfect place for that kind of issue.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for the repo cue!

**Comment by emily-phet** [comment]
@jessegreenberg - Just want to check in on this - if you're not already, can you go ahead and implement arrow keys for balloon dragging in BASE?

**Comment by jessegreenberg** [comment]
Yes, @emily-phet the commit above adds the arrow keys.  Ill deploy a dev version with these added.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet this version has the arrow keys enabled.  
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.5-dev.2/balloons-and-static-electricity_en.html

I will test how having both enabled in the sim works with various AT combinations in this issue.

**Comment by jessegreenberg** [comment]
The arrow keys also need to trigger the aria-live alerts.  The above link needs to be modified for this.

**Comment by jessegreenberg** [comment]
Testing results:

- NVDA + Chrome
  - WASD keys work!
  - Arrow keys work!
- NVDA + Firefox
  - WASD keys work!
  - Arrow keys work!
- NVDA + IE11
  - WASD keys work!
  - Arrow keys work!
- JAWS + Chrome
  - WASD keys work!
  - Arrow keys do not work - occasionally the balloon will move slightly, presumably because of the strange way the AT sends the event to the browser
- JAWS + Firefox
  - WASD keys work!
  - Arrow keys do not work (same as Chrome)
JAWS + IE11
  - WASD keys do not work.
  - Arrow keys do not work.

Unable to test VoiceOver for now, but I think we have consistently seen the arrow keys not work on that platform.  Happy to see everything working on NVDA!  And strange to see that nothing works on JAWS with IE11...

**Comment by jessegreenberg** [comment]
In all cases of JAWS, the arrow keys were obviously not working, so hopefully a user would be reminded to use the WASD keys.  But it would be best to prevent all arrow key events on that platform.  If I recall, the arrow key events are a constant stream of alternating ```keyup``` and ```keydown``` events for as long as an arrow key is pressed (this is why the balloon doesn't move at all).  So it might be possible to detect when the user is trying to drag the balloon with the arrow keys with JAWS.

**Comment by terracoda** [comment]
@jessegreenberg, I did a very quick test on my MacBook Air

* macOS Sierra + ChromeVox
 * WASD works.
 * Arrow keys move the balloon, but with no alerts.
* My MacOS Sierra, VO + Safari
 * WASD move the balloon, but I get no alerts (this might be my system)
 * Arrow keys - slow movement left and right. Good movement up and down. Good movement all directions with added shift key. No alerts and issues with other descriptions getting out of synch.

**Comment by jobara** [comment]
@jessegreenberg and @terracoda I tried this quickly with Safari and VoiceOver on macOS Sierra. I did get the alerts ( direction, charges, etc. ) with the WASD keys. For the arrow keys, they just send the balloon flying off in the direction pushed, unless the shift key is used. With the shift key the movement seemed good, but as @terracoda mentioned, there were no VoiceOver updates.

**Comment by jhung** [comment]
@jessegreenberg I just did a quick test with keyboard + Safari. My results are a little different from @terracoda's.

Mac OS Sierra, Safari, *no* VO
* After pressing key, the balloon moves and focus is removed from the balloon. You need to shift+Tab to put focus back on.
* I can only make one movement with arrow keys before the balloon becomes unresponsive to any keyboard input. i.e. Tab to focus balloon. Enter to grab. Right arrow to move balloon. Now focus is lost on the balloon (see the first point above). I press shift + TAB to put focus back on, and any arrow keys don't seem to do anything.

**Comment by terracoda** [comment]
@jhung, are you pressing Enter or Space to grab the balloon first? The pink outline should change to black.

@jessegreenberg, for me the balloon also went flying really far once when I pressed the left arrow key. Note that I did not try it without a screen reader yet.

Thanks @jhung for testing that!

The lack of alerts with my MacOS Sierra and VO seems to be an anomaly of my system.

**Comment by jhung** [comment]
@terracoda Yep. The behaviour is what @jobara describes (the balloon goes flying off in a direction). Putting focus back on to the balloon after that and attempting to move using arrow keys doesn't do anything.

Another funny thing is that once the balloon is in this unresponsive arrow state, trying to drag and drop with mouse has the balloon constantly moving back in the direction of the initial arrow key press... almost as if the key-up was never registered.

To reproduce:
* Tab to focus balloon. Press enter to grab.
* Press right arrow - balloon goes shooting off to the wall. Balloon would now lose focus.
* Shift-Tab back to the balloon.
* Press Enter to grab the balloon.
* Press any arrow keys - notice the balloon doesn't do anything.
* Use mouse and try dragging the balloon left-ward away from the wall. Notice how the balloon would move right even though you're moving left with the mouse (like you're fighting the right arrow keys of a ghost user at the keyboard).

**Comment by terracoda** [comment]
@jhung, very interesting!

**Comment by jessegreenberg** [comment]
@terracoda @jhung @jobara thanks very much for testing!

@terracoda regarding
> Arrow keys move the balloon, but with no alerts.

This should be fixed with https://github.com/phetsims/balloons-and-static-electricity/commit/eb9e0a7f5a83d7481f73feef48df6a61d8902b89.  I will deploy a new version soon with this fix.

For the issue where the balloon flies off in a direction, I agree with @jhung, it sounds like the ```keyup``` event is never getting registered.  @jhung @jobara were you by any chance testing with a bluetooth keyboard?  This is exactly what we see when a bluetooth keyboard is used.

**Comment by jessegreenberg** [comment]
Testing with VO.  I observed something different still:

- El Capitan (10.11.6) with VO:
  - WASD keys work
  - Arrow keys do not drag the balloon, but navigate the virtual cursor.  If the balloon is picked up, I can still press the left and right arrow keys to find information about the balloon without releasing it.

- El Capitan (10.11.6) without VO
  - WASD keys work
  - Arrow keys work

- Yosemite with VO:
  - WASD keys work
  - Arrow keys both move the balloon AND navigate the virtual cursor!  Once the virtual cursor leaves the balloon, arrow keys work as usual with the virtual cursor.

- Yosemite without VO:
  - WASD keys work
  - arrow keys work

Our sierra machine is out of office now, ill see if I can ping the borrower.

**Comment by terracoda** [comment]
@jessegreenberg, I was using a bluetooth keyboard! And I experienced some balloon flying as well.

**Comment by jessegreenberg** [comment]
Ah, thanks @terracoda!  In an accessibility meeting we decided that we would not support bluetooth keyboards for this reason.  Perhaps we need to rethink that.

**Comment by jessegreenberg** [comment]
Tested with a Sierra Machine - 

Safari with VO on Safari -
 - WASD keys work
 - Arrow keys broken, behave as reported by @jobara @terracoda and @jhung

Safari without VO on Safari
 - WASD keys work
 - Arrow keys work

Safari with VO on Chrome
 - WASD keys work
 - Arrow keys broken, behave as reported by @jobara @terracoda and @jhung

Safari without VO on Chrome
 - WASD keys work
 - Arrow keys work

**Comment by jessegreenberg** [comment]
This will need to be fixed in order to allow arrow keys for any platform.  I wonder if Sierra + VO has the same problem for keyup as apple with bluetooth keyboards - ```keyup``` is given to the browser with keycode=0?  If this is true, maybe we could get away with resetting the entire keystate on keyup if keycode===0.

**Comment by jessegreenberg** [comment]
> maybe we could get away with resetting the entire keystate on keyup if keycode===0.

This might fix the problem with the press and hold behavior, but it wouldn't fix the issue where the arrow keys both drag the balloon AND move the virtual cursor.

**Comment by jobara** [comment]
@jessegreenberg I was using a wired keyboard when testing macOS Sierra with VO + Safari. Also, I don't think the prior issue was with bluetooth keyboards specifically, but with how iOS works with physical ( maybe even the onscreen one ) keyboards. In this case, from the testing done so far, it does seem to be caused by VoiceOver.

**Comment by jessegreenberg** [comment]
I see, thanks @jobara.  Yes, now that the issue has surfaced with VoiceOver on MacOS Sierra, it looks like the issue is not specific to bluetooth keyboards.  Maybe we can submit a bug report to apple for this.

https://developer.apple.com/bug-reporting/

**Comment by emily-phet** [comment]
@jessegreenberg - yes, submitting a bug report sounds good to me.

**Comment by jessegreenberg** [comment]
Sounds good, I will prepare a bug report.  In the 11/22/16 accessibility meeting @jobara also provided some examples where the arrow keys were used in a web application context.  It would be good to review these and understand why the arrow keys are available there but not in this context.

https://github.com/fluid-project/infusion/tree/master/demos

**Comment by jessegreenberg** [comment]
Here is a demo that uses the application role with the arrow keys:
http://build.fluidproject.org/infusion/demos/keyboard-a11y/

This demo uses a grid role with the arrow keys:
http://build.fluidproject.org/infusion/demos/reorderer/gridReorderer/

**Comment by jessegreenberg** [comment]
While using a MacOS Sierra device, I found this setting in VoiceOver Utility:

"Always allow keyboard commands to navigate websites."

Default is unchecked.  When checking it, a dialog comes up that warns "Behavior of websites that use arrow keys for other functionality may be affected."  This setting might also interfere with features in BASE.

**Comment by jessegreenberg** [comment]
Testing http://build.fluidproject.org/infusion/demos/keyboard-a11y/ on MacOS Sierra and the arrow keys work great.

**Comment by jessegreenberg** [comment]
In both cases, the elements which have arrow key control have roles other than application which may provide working arrow keys.

This demo: http://build.fluidproject.org/infusion/demos/keyboard-a11y/

uses the List role.  The other demo uses the grid role.

Another difference is that the arrow keys set focus to a new element.  Explicitly setting focus could potentially prevent the virtual cursor from reading content when focus changes by the application.

**Comment by jessegreenberg** [comment]
Here is a JSFiddle that exemplifies the problem:

https://jsfiddle.net/ujszje1f/2/

With MacOS Sierra + VoiceOver + Safari, when focus is on the "Draggable Element" the arrow key event is passed to the browser and the virtual cursor reads text content.

**Comment by jessegreenberg** [comment]
What if the ```<p>``` is removed from under the div?

**Comment by jessegreenberg** [comment]
No change.  When I focus the draggable div, VoiceOver in Safari says:

"Web Application, Draggable Element.  You are currently on a text element inside of a frame."

And when I press an arrow key, it will move to the next paragraph or spell out "Draggable" letter by letter, but the event is still observed by the browser.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for rechecking these examples. The Grid roles definitely has native keyboard interactions available that involve arrow keys.

https://www.w3.org/TR/wai-aria-practices-1.1/#grid

I can't find explicit documentation on the list role, but since it is a group element with mandatory children, and is often used for navigation lists, I have a feeling there is some built-in keyboard accessibility there, too.

**Comment by jessegreenberg** [comment]
Here is an example where focus changes.

https://jsfiddle.net/r73r4ye2/

**Comment by jessegreenberg** [comment]
Thanks @terracoda that is good to know!  I will try the example in https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-263403226 with list and grid roles to see if the arrow keys start to work like the examples in https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-263376028.

**Comment by jessegreenberg** [comment]
Here is an example that uses role=listBox.

https://jsfiddle.net/00w409n1/

**Comment by jessegreenberg** [comment]
One thing I notice in these examples is that Safari lets us see the virtual cursor with a blinking text cursor.  With this, I can see that pressing the arrow keys moves focus off of the navigation element and onto text content.

This is very likely what is making the balloon fly off in one direction.  I am now guessing that this is NOT an issue with the keyup event as initially suggested, but an issue with focus.

**Comment by jessegreenberg** [comment]
In http://build.fluidproject.org/infusion/demos/keyboard-a11y/, the elements that can be interacted with the arrow keys are ```<img>``` elements with no text content or inner HTML.  There is nowhere for the virtual cursor to go.  I would like to try this in the JSFiddle.

**Comment by jessegreenberg** [comment]
https://jsfiddle.net/00w409n1/2/

**Comment by jessegreenberg** [comment]
This might be the secret sauce: https://github.com/fluid-project/infusion/blob/master/src/framework/core/js/jquery.keyboard-a11y.js#L331-L341

```preventDefault()```

**Comment by jessegreenberg** [comment]
https://jsfiddle.net/00w409n1/6/

In the above fiddle, the arrow keys are correctly restricted to the scripting and do not move the virtual cursor.

**Comment by jessegreenberg** [comment]
That was it!  The arrow keys now work with VoiceOver + MacOS Sierra + Safari!

**Comment by jessegreenberg** [comment]
JAWS still does not allow arrow keys to be used for this kind of application in any browser, but they feel unresponsive when using the sim so user's would presumably be reminded to the WASD keys.

**Comment by jobara** [comment]
@jessegreenberg great work on that investigation. Regarding JAWS, did you find any difference in any of your experiments?

**Comment by jessegreenberg** [comment]
Here is what I found with Windows 10 + JAWS

Chrome - Arrow keys do nothing for the balloon.  If you press and hold the arrow keys, every 3-6 seconds the balloon might move a few pixels in one direction.

Firefox - Same as Chrome.

IE - ```role=application``` does not seem to work.  WASD keys and Arrow keys do nothing for the balloon and move the cursor.  Pressing "insert + 3" to "Pass key through" works for both.

If I press and hold the down arrow key on the balloon in Chrome or Firefox, this is what the stream of events looks like (which is why it doesn't move at all)
![capture](https://cloud.githubusercontent.com/assets/6396244/20719693/e1647370-b619-11e6-8509-ed172a99315e.PNG)

**Comment by jessegreenberg** [comment]
I just tried http://build.fluidproject.org/infusion/demos/keyboard-a11y/ with IE and JAWS.  Arrow keys usually work in that application.  I can hear JAWS transition to a 'forms' mode of interaction with a little 'beep'.  I think this warrants a new issue to figure out why JAWS isn't switching to application mode in this case.

**Comment by terracoda** [comment]
@jessegreenberg, JAWS used to go into forms mode. Are you saying that in the latest version of the sim, JAWS does not enter forms mode with the application role?

**Comment by jessegreenberg** [comment]
@terracoda yes, that is correct.

**Comment by terracoda** [comment]
@jessegreenberg, I agree with @jobara, really great investigative work here! Really exciting stuff!

**Comment by jessegreenberg** [comment]
Thanks @terracoda, we are getting there!

@jobara I ran through all JSFiddle examples above and a few Infusion examples with JAWS + IE and the arrow keys work as expected.  The issue in BASE with JAWS is really for press and hold behavior for the arrow keys, so I want to see if we observe the same event stream as https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-263629048 in an Infusion example

**Comment by jessegreenberg** [comment]
Example http://build.fluidproject.org/infusion/demos/keyboard-a11y/ shows the same issue that we are seeing in BASE.

I modified https://github.com/fluid-project/infusion/blob/master/src/framework/core/js/jquery.keyboard-a11y.js#L331-L341 to log the key events. 

When pressing and holding the right arrow key, this is what I see when JAWS is turned off (expected):
![no-jaws](https://cloud.githubusercontent.com/assets/6396244/20729351/defc7dce-b63e-11e6-8490-513eca185106.PNG)

This is what we see when JAWS is turned on:
![jaws-on](https://cloud.githubusercontent.com/assets/6396244/20729396/096f0c7a-b63f-11e6-8846-6481b1334449.PNG)

**Comment by jobara** [comment]
@jessegreenberg thanks for clarifying and verifying that.

**Comment by jessegreenberg** [comment]
The arrow keys are enabled for drag and drop in balloons-and-static-electricity, though they do not work for JAWS due to the above issue.  I am going to close this issue and create a new one to track if any changes need to be made for design.

**Comment by terracoda** [comment]
@jessegreenberg, what version of BASE has the arrow keys working? I tested version [1.2.0-reader.7](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-reader.7/balloons-and-static-electricity_en.html) in Safari, FireFox, and Chrome with VO off and the arrows keys do not work in this version.

**Comment by jessegreenberg** [comment]
@terracoda this version has working arrow keys:
http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.5-dev.3/balloons-and-static-electricity_en.html?hideChargeControls&showLiveOutput

Though it was built on december 2 and won't include all of the bug fixes in the last 2 weeks.  I will build a new version and email to you.

**Comment by terracoda** [comment]
Thanks @jessegreenberg!

The arrow keys work on MacOS Sierra 10.12.1 (Chrome, FireFox, and Safari) when there is no screen reader enabled. I'm still trying to see how it works with VO :-) Will post results.

**Comment by terracoda** [comment]
@jessegreenberg 
MacOS Sierra 10.12.1 VO and Safari (10.0.1)
- initially the arrow keys worked ok. The up and down were better than the left and right. The left and right arrow keys made very small steps making them appear a bit resistant to moving.
- after a lot of rubbing, suddenly the arrow keys stopped working all together. They started moving focus instead. And at the same time, the A and D keys stopped working. The balloon would move a little right and then bounce back. W and S worked fine.
- after reloading the sim, the WASD keys worked again, but the Arrows did not. The arrow keys just move focus. I even cleared my cache.

The arrow keys work just fine in all browsers (Safari, Chrome, Fire Fox) when VO is off, which is what is most important.

**Comment by terracoda** [comment]
MacOS Sierra 10.12.1 VO and Chrome (55.0.2883.95)
MacBook Pro (2015) with native laptop keyboard.

- using left and right arrows move the virtual cursor and read through the PDOM, and the black grabbed highlight remains around the balloon.
- using the up and down arrows, the virtual cursor moves and the black outline disappears as well. 

This behavior is consistent with your results above (https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-261631005).

So, its seems for now the arrow keys remain useful for keyboard users without screen readers. The WASD keys remain accessible to screen reader users. If two students work together, they will have to stick with the WASD keys for now.

I hope it was ok, I added a couple of more tests to this issue (after closing). For some reason I was under the impression that the arrow keys worked with all screen readers except JAWS, but that is not the case.

**Comment by jessegreenberg** [comment]
Thanks for testing @terracoda, good to know there are still issues.  I expected that they would work in VO. I just tried testing again with macOS Sierra 10.12.1 on Chrome 54.0.2840.98 and Safari 10.0.1.  The arrow keys worked in both browsers with VoiceOver.

There is a user setting in VO that might be restricting use.  Could you please make sure that in VoiceOver Web settings that "Always allow keyboard commands tot navigate websites" is turned off?  That checkbox disables the arrow keys on interactive widgets.

**Comment by jessegreenberg** [comment]
I just updated to Chrome 55 and the arrow keys still work in that browser with VO turned on.

**Comment by terracoda** [comment]
@jessegreenberg, yes that checkbox was turned off when I tested. I actually just enabled it to see if it would help, but it doesn't.

The really strange thing was that in Safari and VO, thing initially worked ok (not 100%, but ok) and then it just stopped!

**Comment by jessegreenberg** [comment]
Ok, thanks - very strange.  When you the arrow keys were working, were you hearing any aria-live updates?

**Comment by terracoda** [comment]
Yes, with Safari the alerts were working with the Arrow keys. It was all working very nicely except for the slowness of the left and right arrow keys. It was was after I depleted the sweater of negative charges that the arrow keys stopped working and remain not working.

However, with Chrome, the Arrow keys never worked with VO on at all for me.

**Comment by jessegreenberg** [comment]
Ok, thanks.  @jobara @jhung if available, could you please test this version and see if arrow keys work with VO once the balloon is picked up for dragging?

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.6-dev.1/

I will see if I can verify on another machine as well.

**Comment by emily-phet** [comment]
@jessegreenberg 
I just took a quick look - the arrow keys don't work for me at all on Safari or Chrome with VoiceOver on. After grabbing the balloon, pressing the arrow keys moves the virtual cursor with no Balloon motion at all.

The arrow keys seem to work fine with VoiceOver off on Safari and Chrome.

**Comment by jessegreenberg** [comment]
Thanks @emily-phet.  Do you also use macOS Sierra?

**Comment by emily-phet** [comment]
@jessegreenberg Yes, macOS Sierra, v10.12.1

**Comment by jessegreenberg** [comment]
Ok, thanks, good to know.  I just tried on Yosemite 10.10.5 on Safari and Chrome with VO turned on and the arrow keys work there.

**Comment by jessegreenberg** [comment]
I also just tested on OSX 10.9 with VO in Chrome and Safari, arrow keys worked there too.  I dragged the balloon for a while and the balloon continued to work when all charges were removed from the sweater.

**Comment by emily-phet** [comment]
Sierra broke it? Too bad!

**Comment by jessegreenberg** [comment]
Possibly! Though it is working on Sierra for me (comment https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-267171084).

**Comment by terracoda** [comment]
@jessegreenberg, can you take a screen shot of your VO settings?

**Comment by jessegreenberg** [comment]
@terracoda this enough info?

![screen shot 2016-12-14 at 4 03 43 pm](https://cloud.githubusercontent.com/assets/6396244/21204970/18d6c8d6-c217-11e6-9f98-54c8191f858d.png)

**Comment by emily-phet** [comment]
Here's mine - looks like there's a difference for the "Navigate Images" option, "Always" vs "With Descriptions".

<img width="892" alt="screen shot 2016-12-14 at 4 08 04 pm" src="https://cloud.githubusercontent.com/assets/5109055/21205057/86072d56-c217-11e6-81c1-49e43dca2980.png">

**Comment by terracoda** [comment]
@jessegreenberg, @emily-phet I have tried both those settings. In the sims, the Navigate images setting doesn't matter since there are no images in the PDOM.

**Comment by jobara** [comment]
@jessegreenberg I tried the arrow keys in the sim just now and they seemed to work as expected. I'm using macOS 10.12.2 and Safari 10.0.2. My settings looked like yours.

As a side note, I did notice a side effect of the way that the movement is calculated on keypress. If i tap rapidly, the balloon doesn't move at all. So it feels a bit broken. I think you could probably make it travel a minimum distance on keyup, this may also fix the JAWS issue.

**Comment by terracoda** [comment]
@jessegreenberg, @jobara, @emily-phet, ok, I just had the most surreal experience. I am using a MacBook Air Sierra 10.12.2. Since I was at Assets, the interactive alerts have never worked for me on this machine - no idea why. I had tried several VO settings trying to get it to work.

I just tried the sim with the arrow keys, and the interactive alerts (dragging, rubbing, and releasing) were all spoken. I accidentally used the Arrow key, then grabbed the balloon again and upon the second grab, the alerts were no longer spoken.

I reloaded and they were spoken again, and now they are spoken when using the WASD keys, too.

Note, just before this test I was just adjusting my VO verbosity settings because I was only getting "This item has a help tag" when grabbing the balloon. So I think the change in VO settings is what is the making this all work. I think I will make another issue to record my VO settings. This might be helpful for the future.

**Comment by jessegreenberg** [comment]
@jobara thanks for testing!  Good to know that arrow keys were being captured by the application and not the virtual cursor.

> If i tap rapidly, the balloon doesn't move at all. So it feels a bit broken. I think you could probably make it travel a minimum distance on keyup, this may also fix the JAWS issue.

This is a great suggestion, thanks, I created a new issue to track this because I think there are lots of things to investigate and discuss here.

**Comment by jessegreenberg** [comment]
@terracoda that is really interesting, let us know what you find in the settings!

**Comment by jessegreenberg** [comment]
Hmmm...I was just playing with the sim to test #216 and while using VO in Safari and the arrow keys suddenly stopped working for the balloon.

**Comment by jessegreenberg** [comment]
If I hold the shift key down, the arrow keyws work.  Otherwise, they move VO's cursor.

**Comment by jessegreenberg** [comment]
@jobara, now that the arrow keys have stopped working in BASE, they have stopped working in other apps such as 

http://build.fluidproject.org/infusion/demos/reorderer/imageReorderer/

And I can't get them to work for anything other than the cursor even when focus is on interactive content.  Have you ever run into this before?

**Comment by terracoda** [comment]
@jessegreenberg, I just opened a new issue #217 which I found today. Everything stops working when I deplete the sweater of charges and have 2 balloons on the go.

**Comment by terracoda** [comment]
@jessegreenberg, in https://github.com/phetsims/balloons-and-static-electricity/issues/205#issuecomment-267173722, I noted that the arrow keys stopped working after I depleted the sweater of charge. I just tried that again (with a single balloon), and I did not encounter a problem.

**Comment by terracoda** [comment]
@jessegreenberg, should I put my VO settings in a separate issue? Maybe others would like to compare and comment?

**Comment by jessegreenberg** [comment]
> @jessegreenberg, should I put my VO settings in a separate issue? Maybe others would like to compare and comment?

Please do, that would be great!

**Comment by jobara** [comment]
@jessegreenberg when testing the sims earlier in the year i did run into cases where certain VO navigation just seemed to stop working. I reset my VO settings and things started to work again. This hasn't happened for a long time though, so I assumed it was just something that happened to my system. Not sure it's exactly the same as what you're seeing, but hopefully it will address your issue. It would also be interesting if you can consistently reproduce the issue.

To reset VO settings.

1. Open the VoiceOver Utility
2. In the menubar go to file > Reset All VoiceOver Preferences...
3. Click Reset

**Comment by terracoda** [comment]
@jobara, thanks for the VO reset tip. I haven't tried that. It would be good to compare all default settings with what I currently have set (https://github.com/phetsims/a11y-research/issues/14).

**Comment by jessegreenberg** [comment]
Thanks @jobara I will give that a try next time I have access to an apple device.

**Comment by jessegreenberg** [comment]
> Hmmm...I was just playing with the sim to test #216 and while using VO in Safari and the arrow keys suddenly stopped working for the balloon.

After work in john-travoltage, we now know why.  VO has a "quick nav" setting that totally changes navigation strategies.  The way to access this is to press left and right arrow keys at the same time. In "quick nav" mode, arrow keys cannot be used in an application.

I think this issue can be closed. We can use the arrow keys to move the balloon on all platforms except JAWS with Firefox, and a bug report has been submited to VFO. CLosing.
