### ISSUE TITLE
Polish Radio button size

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balloons-and-static-electricity#212]
@jessegreenberg since BASE is one of our earliest sims we had not really refined the look and feel of radio buttons. Modern sims tend to have the visual size of the radio button match the approximate size of the first letter of its label. For instance:

![radio button](https://cloud.githubusercontent.com/assets/4051174/20978898/ddee11c0-bc67-11e6-9874-e840f59e6335.PNG)

The radio buttons in BASE look quite bloated, since you are in this sim all the time, this might be a nice easy tweak. Not a high priority at all, but might be nice and quick to fix.

**Comment by jessegreenberg** [comment]
Sure, I just reduced the size of the button radii like so:
![reduce radius](https://cloud.githubusercontent.com/assets/6396244/20994531/334b2c52-bcae-11e6-9d45-da5a10b58448.PNG)

Good to close @ariel-phet?

**Comment by ariel-phet** [comment]
Looks perfect, thanks! (that pixel polish had been nagging at me for awhile!)
