### ISSUE TITLE
Drag balloon without step function

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#216]
In #205 @jobara said

> As a side note, I did notice a side effect of the way that the movement is calculated on keypress. If i tap rapidly, the balloon doesn't move at all. So it feels a bit broken. I think you could probably make it travel a minimum distance on keyup, this may also fix the JAWS issue.

We should investigate other methods of drag and drop, and define the important aspects of the drag and drop interaction.

**Comment by jessegreenberg** [comment]
In a 2D game, (on the web or otherwise) I would expect that rapidly tapping a key might not move an object because the object should only move while the key is down.  But maybe this impression is not correct.  In #205 @terracoda also said 

> And the arrow keys work, but the left and right are problematic as described by @jobara.

**Comment by jessegreenberg** [comment]
> I think you could probably make it travel a minimum distance on keyup, this may also fix the JAWS issue.

This would solve a few issues but it could also make for a less "game-like" interaction.  That may not be a bad thing, but we should discuss what is expected in drag and drop in a 2D interactive.

**Comment by jessegreenberg** [comment]
Here are a few questions I have:

- Do we need to support diagonal motion?
- Is the normal delay on press and hold acceptable for drag and drop in a game/initeractive?
- Should there be a minimum amount of movement on every single key press?

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet do you have any thoughts about this issue?  We could also discuss at the next accessibility meeting.

**Comment by terracoda** [comment]
@jessegreenberg, holding the key down seems to work fine (balloon keeps moving), but one then gets fewer descriptions, which may not be an entirely bad thing.

**Comment by terracoda** [comment]
@jessegreenberg, how would 

> a minimum amount of movement on every single key press
https://github.com/phetsims/balloons-and-static-electricity/issues/216#issuecomment-267404111

make it less functional to non-screen reader users?

**Comment by jessegreenberg** [comment]
> https://github.com/phetsims/balloons-and-static-electricity/issues/216#issuecomment-267420525

True, that one is not as bad.  It could give the user less control.  Fine control may not be too important in this sim.  But in other examples, it could make it harder for a user to move the object a few pixels if the minimum movement is set to some other value.

**Comment by jessegreenberg** [comment]
It would be pretty quick to change the implementation so that the dragging works with more typical event tracking that does not count on the step function.  I will do that in a branch and then we can compare the two versions.

**Comment by jessegreenberg** [comment]
Alright, here is a rough example of the difference between the two approaches:

- http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.6-dev.1/balloons-and-static-electricity_en.html?hideChargeControls
  - **Latest version, what we have tested with**
  - *Uses animation step to drag balloon with keyboard*
  - Pros:
    - Smoother experience for non-screen reader users
    - Supports diagonal dragging (combinations of arrow keys)
    - More control during interaction
- http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.6-drag-no-keyup-dev.1/balloons-and-static-electricity_en.html?hideChargeControls
  - **New implementation, different experience than what we have tested with**
    - This version introduced a few bugs, but is a rough draft to exemplify the interaction
  - *Uses more standard method of tracking keydown events in the browser*
  - Pros:
    - Arrow keys work reliably on all screen readers including JAWS and iOS with a bluetooth or physical keyboard (might not always work with VoiceOver, see #205)
    - Balloon moves small amount, no matter how long the key is pressed which may be the expected behavior, See https://github.com/phetsims/balloons-and-static-electricity/issues/216#issue-195873166

**Comment by emily-phet** [comment]
@jessegreenberg Took a quick look in Safari, and I really like the motion of the first option the best. The balloons movement feels "peppy" and active. I can't get the arrow keys to work with VO on, so I can't reproduce the issue @terracoda found where rapid presses result in no motion.

**Comment by terracoda** [comment]
@jessegreenberg, I agree with Emily, that the motion in version 1 (when pressing and holding) is nice and peppy. The thing I do not understand is when pressing up and down quickly, the key-press response behaviour is different when using left and right arrows than up and down arrows.

In example 2 (drag-no-keyup-dev), the left and right (quick presses) work better, but then of course, pressing and holding creates a bumpy motion rather than smooth.

I realize version 2 is still buggy, but just to note that I accidentally lost the balloon while still grabbed (i.e., without releasing it). I think I was pressing and holding. I also tried both Left and Up arrow at the same time, and this brought up a VO quick Nav with options to change reading level detail (words, characters, etc.) - just something that we may need to watch for.

So, just to re-iterate, @jessegreenberg, do you understand why the left and right arrows behave differently than the up and down arrows in version 1. Is there something special about the left and right arrows?

**Comment by jessegreenberg** [comment]
Thanks @terracoda and @emily-phet.  I agree, option 1 does feel better, we will proceed with that.  This will result in a bit more work, and the arrow keys may not work with JAWS or Apple with bluetooth keyboards, but the interaction is much smoother.

> do you understand why the left and right arrows behave differently than the up and down arrows in version 1. Is there something special about the left and right arrows?

@terracoda this is only when VO is turned on, correct?  For VO, the left/right arrow keys move the virtual cursor to the left/right, and the up/down arrow keys move the cursor to the previous/next item.  VoiceOver may handle the events differently for these two forms of navigation which might be why the left/right arrow keys are less responsive.

**Comment by terracoda** [comment]
@jessegreenberg, yes this behavior is VO only, so the difference is in VO's handling and not our implementation - makes sense, and maybe someday will improve as screen reader software improves.

**Comment by jessegreenberg** [comment]
Ok, thanks @terracoda.  Yes, hopefully! Also glad the arrows keys are working with VO for you now, they are no longer working for me - spontaneously stopped and I am not sure why.

I think we are in agreement for this issue, we will proceed with option 1 in https://github.com/phetsims/balloons-and-static-electricity/issues/216#issuecomment-267472217.

Closing.

**Comment by jobara** [comment]
@jessegreenberg just read this thread over again, and wanted to clear up some potential confusion about my initial suggestion. I wasn't suggesting abandoning what is referred to as option 1, but rather that a single keydown/keyup even combo could result in some movement, e.g. minimum 1 pixel movement. This could be any amount that seems reasonable though. That way, for someone who is tapping instead of holding, they will be able to move the balloon and would also work with the JAWS bug. And for others who would want to hold the keydown, they would still get the existing behaviour.

**Comment by jobara** [comment]
@jessegreenberg just saw your comment, https://github.com/phetsims/balloons-and-static-electricity/issues/218#issuecomment-267672869. That jitteriness could be a problem.

**Comment by jessegreenberg** [comment]
Thanks for clarifying @jobara, yes that makes sense.  I wanted to create this issue to discuss the possibility of option 2 in https://github.com/phetsims/balloons-and-static-electricity/issues/216#issuecomment-267472217 because it is perhaps a bit more accessible out of the box and works with JAWS and iOS keyboards.

But your suggestion to add some movement on the keyup event is great, and I started to investigate that option in #218.
