### ISSUE TITLE
Discuss Shift Key for smaller balloon steps, rather than bigger balloon steps

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#219]
@emily-phet, @jessegreenberg
There has been a lot of discussion about balloon movement recently (#205, #216, #218). 

Considering these issues and the fact that testing fine differences in distances near the wall is difficult for keyboard users, I propose making the Shift key make the balloon take smaller steps, rather than bigger steps. 

I think this is more useful for users and I am wondering if it would have beneficial side effects for implementation?

**Comment by jessegreenberg** [comment]
@terracoda mentioned this in the accessibility meeting 12/20/16  -

All thought this seemed like a good idea, and we ill give it a shot!

**Comment by jessegreenberg** [comment]
Assigning to myself to make the change.

**Comment by jessegreenberg** [comment]
Done in the above commits.  Example:

![recording 26](https://cloud.githubusercontent.com/assets/6396244/21446293/8d4fd570-c881-11e6-9dbf-2b0dffcf3ae9.gif)


@terracoda I am going to go ahead and close, but we can tweak the speed at any time.

**Comment by terracoda** [comment]
Awesome, @jessegreenberg!
