### ISSUE TITLE
Description differences between "show charge differences" and "show all charges"

### ISSUE THREAD

**Issue by emily-phet** [phetsims/balloons-and-static-electricity#231]
@terracoda has created and user tested a set of descriptions for BASE for the "show all charges" view. She is now working on descriptions for the "show no charges" and the "show charge differences" views. Since the original descriptions (designed for the "show all charges" view) emphasized the charge differences, is there any additional information needed to meet the goals of the "show charge differences" view. 
Here is a link to a version of the sim: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.2.0-reader.7/acccessibility-test.html that shows the current descriptions (designed for the "show all charges" view). @kathy-phet @ariel-phet please take a look at this sim and its descriptions and let me know what (if any) additional information would be useful to convey in the descriptions for the "show charge differences" view. (Note: visualization of descriptions works best when using keyboard navigation in the sim, rather than a mouse)

**Comment by kathy-phet** [comment]
I do think you can have different descriptions for this and somewhat different goals. The visual student doesn't have access to the sense of paired charge in this view - just the net charge. So "more positive charges than negative charges" is giving more information than the visual student has access too. It's hard to know how to rework the descriptions though. Perhaps ... "No net charge on balloon" then "Some negative charges visible on balloon. Equal positive charges visible on sweater." "More negative charges on balloon. More positive charges on sweater."

**Comment by terracoda** [comment]
@kathy-phet, thanks for the phrase, "no net charge"! I hadn't thought of that, though I have been using "net negative" and "net positive" elsewhere. I was exploring how I could use "net charge" descriptions in this view and leave them off in the other view. I will think about this while traveling. Thanks!!!!

**Comment by ariel-phet** [comment]
As I play around, one piece of information that seems to be missing to me is the movement of wall charges as I move a charge balloon close to the wall. The polarization of the wall is a gradual process, and I think the visual demonstrates that well, however, the description only changes the state of the wall once I have actually touch the wall. And then there is a description when I move away "Negative charges in wall return slightly". It seems the description of wall charges and how their overlap is changing needs to be refined in the "show all charges" view. However, this refinement would not affect the "show charge differences" view since no charges are shown on the wall.

Nothing obvious is coming to mind for the "show charge differences" view, since this is a much simplified view.

**Comment by terracoda** [comment]
@ariel-phet, thanks for the feedback. Long range forces are very difficult to describe in words. Sound is a much better option than words for describing the induced charge effect.
I agree that the induced charge description is not quite right yet. Also, interviews users have had different reactions to each iteration.
I also agree that in the simplified view of show no charges and show charge differences, not having to describe the induced charge is a bonus.
When we can actually sonfiy this sim, I think these simplified views will be very helpful at simplifying the soundscape, which may be very useful for pedagogical reasons.

**Comment by terracoda** [comment]
Comment about induced charge in https://github.com/phetsims/balloons-and-static-electricity/issues/231#issuecomment-276433213 has been address in new descriptions. See google doc: [Grid Descriptions Simplified and Revised](https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit#heading=h.elxd9k35q6fh)

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet can this issue be closed?  I believe charge view descriptions for a11y have been reflected in the design doc.

**Comment by terracoda** [comment]
Yes, closing this issue. The design doc has been updated.
