### ISSUE TITLE
Remove 'H' key for hotkeys and help

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#232]
@terracoda now that the navigation bar has a button for hot keys and help can we remove the 'h' key command from the draggable balloon?

**Comment by terracoda** [comment]
@jessegreenberg, I think that's a good idea. 

I wonder if the Scene Summary should let the users know how to quickly find this button? Let me ponder that a little...perhaps, after, "Grab balloon to play", but not sure we need a cue for this.

**Comment by jessegreenberg** [comment]
Alright, the keyboard help content can be accessed from the navigation bar now.  I am going to close this issue, but @terracoda let me know if you think that another cue for this button is necessary.
