### ISSUE TITLE
black rectangle in oneBalloonIcon - needed?

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#233]
I'm instrumenting this sim for PhET-iO, and just instrumented a black rectangle that lives inside of the one balloon icon.  I don't understand the purpose of this rectangle, and it wasn't at all obvious to me where it is ever made visible.  Assigning to @jessegreenberg to have a look.  Perhaps this can be removed.

To see it, go into `ControlPanel.js` in this repo and search for `var oneBalloonIcon`.  The black rectangle is the second child.

**Comment by jessegreenberg** [comment]
It looks like it is there so that the two icons have the same dimensions for layout.  But the radio button group, or whatever interface element is being used, should handle that automatically, so it should be removed.

**Comment by jessegreenberg** [comment]
Removed, closing.
