### ISSUE TITLE
charge is not conserved

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#234]
In v1.1.5, which is live on the web site as of this writing, the number of free positive and negative charges is off by one after the yellow balloon interacts with the sweater.  The screenshot below shows what happens if the balloon is rubbed on the sleeve of the sweater and then moved to the wall.  There are five unmatched negative charges on the balloon and six unmatched positive charges on the sweater.

![base-unbalanced](https://cloud.githubusercontent.com/assets/3082831/21569336/29676732-ce79-11e6-98c7-49ace91e1aef.PNG)

This was found when working to solve some issues with state updating for PhET-iO (see #204), and I suspect the issue is that one of the free negative charges isn't being added to the scene graph.  I'll do an initial investigation and see if there is a quick fix.

**Comment by jbphet** [comment]
The problem was actually that two of the minus charge views had identical positions, and thus overlapped on the balloon, making them look like a single charge.  I've fixed this issue by changing the position of one of the charges as defined in the `POSITIONS` array in the `BalloonModel.js` file.  I tested this by visual inspection, however, I couldn't tell how these positions were arrived at in the first place and whether there is some pattern to them that should be followed.  There is nothing in the documentation that says where they came from.  I'm going to assign this to @jessegreenberg to decide if the position change is reasonable, since it looks like he has most recently been the primary developer (I'm basing this on GitHub history).

I'm also adding @ariel-phet as an assignee to determine whether this warrants a maintenance release.  It would be an easy one to do, and since it does appear to violate conservation of charge, it seems to me like we should correct it.

**Comment by jessegreenberg** [comment]
Based on the current implementation, this change looks acceptable to me @jbphet.  I don't really know how these positions were determined either, I am not aware of any additional documentation for this.  I assume it was visual inspection initially as well.

@ariel-phet assigning to you to decide whether or not to do a maintenance release.  Merging https://github.com/phetsims/balloons-and-static-electricity/commit/b09ef3e1c9d662ea1a04ef01981d5c50ad4db0cb into the latest release branch should not require any additional testing.

**Comment by ariel-phet** [comment]
@jessegreenberg yes, this seems worthy of a maintenance release.

I would also request one other minor tweak. BASE has very large radio buttons. The current version on master has smaller radio buttons buttons, but also smaller text labels. I would prefer smaller radio buttons in the maintenance release (I believe this is the last remaining sim with oversize radio buttons, and I am a big fan of consistency). If that tweak can also be made without requiring additional testing it would be great. If it is more complicated than that, do not bother.

**Comment by jessegreenberg** [comment]
@phet-steele pointed out that QA credits are missing.  @phet-steele could you please paste in this issue what the QA credits should be for this sim?

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/balloons-and-static-electricity/issues/212 we made the radio buttons smaller, but not the text size, I'm not sure why those are smaller now in master.  I will take a look.  It should be straight forward to include the smaller radio buttons (with the correct text size) in this maintenance release.

**Comment by phet-steele** [comment]
Steele Dalton, Bryce Griebenow, Elise Morgan, Oliver Orejola, Benjamin Roberts, Bryan Yoelin

**Comment by jessegreenberg** [comment]
When I cherry-pick https://github.com/phetsims/balloons-and-static-electricity/commit/b09ef3e1c9d662ea1a04ef01981d5c50ad4db0cb, charge is still not conserved.  I think something else is making the balloon charge off by one.

**Comment by jessegreenberg** [comment]
It is correct in master.

**Comment by jessegreenberg** [comment]
In 1.1, BalloonNode has

```js
    //if change charge, show more minus charges
    model.chargeProperty.link( function updateLocation( chargeVal ) {
      if ( chargeVal ) {
        model.minusCharges[ model.plusCharges.length - 1 - chargeVal - 1 ].view.visible = true;
      }
    } );
```

In Master, BalloonNode has
```
    //if change charge, show more minus charges
    model.chargeProperty.link( function updateLocation( chargeVal ) {
      if ( chargeVal ) {
        model.minusCharges[ model.plusCharges.length - 1 - chargeVal ].view.visible = true;
      }
    } );
```

Which must be causing the discrepancy.

**Comment by jessegreenberg** [comment]
When we make the change, there are still enough point charges available (array index stays withing bounds) because there are a few too many entries in BalloonModel.positions.

This is still a minor change and it seems safe to publish a maintenance release.

**Comment by jessegreenberg** [comment]
I published the maintenance version, with changes to fix:
 - QA credits
 - Conservation of charge
 - Radio button size

Closing.
