### ISSUE TITLE
encapsulate a11y strings in 1 .js file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#236]
Decided at 1/5/17 dev meeting...

Move all a11y strings to one .js file, something like BASEA11yString.js.  

Also do this for other sims (and common code?) that contain a11y strings.

**Comment by jessegreenberg** [comment]
a11y strings isolated in a single file (BASEA11yStrings.js) in the above commit.  https://github.com/phetsims/john-travoltage/issues/133 is the only other sim where this is necessary, and we haven't hard coded any strings in common code. Closing.
