### ISSUE TITLE
refactor to separate model and view for charges

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#237]
While working on #204, I noticed some architectural issues in the original code.  During the most recent developer meeting, we discussed whether to address these and decided that we should.  This is one of those issues.

Some of the view components are currently stored in the model, which is a clear violation of the model-view-controller architecture that PhET generally tries to use for all simulations.  This is probably best illustrated with a code excerpt.  The code below was taken from `BalloonNode.js`.  In it, view elements are being created to represent the plus and minus charges in the balloon model, but the references to them are then being added back to the model.

```js
    for ( var i = 0; i < model.plusCharges.length; i++ ) {
      model.plusCharges[ i ].view = new PlusChargeNode(
        model.plusCharges[ i ].locationProperty,
        plusChargeNodesTandemGroup.createNextTandem()
      );
      originalChargesNode.addChild( model.plusCharges[ i ].view );

      model.minusCharges[ i ].view = new MinusChargeNode(
        model.minusCharges[ i ].locationProperty,
        minusChargeNodesTandemGroup.createNextTandem()
      );
      originalChargesNode.addChild( model.minusCharges[ i ].view );
    }
```

This is also true for `SweaterModel.js`, and there is a portion of code where the state of the view is being updated in the model.  The code looks like this:

```js
    //charge from sweater to balloon
    moveChargeTo: function( charge, balloon ) {
      charge.movedProperty.set( true );
      charge.view.visible = false;
      .
      .
      .
    },
```

This should be refactored so that the view portions of the code do not cross into the model.

**Comment by jbphet** [comment]
Assigning to @jessegreenberg, as discussed in the 1/5/2016 developer meeting.

**Comment by jessegreenberg** [comment]
Luckily the model and view weren't too entangled, in all cases the view was added to the model so that there was a reference to the view component for visibility in the same file.

@jbphet would you like to review changes?

**Comment by jbphet** [comment]
Apologies - I never got to this, and it has been a long time.  I just scanned through the commits, and it seems like they addressed my concerns.  Closing.
