### ISSUE TITLE
BalloonModel adds static function outside of the inherit function

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#239]
There are several functions in the BalloonModel that are essentially static functions but are not added using the fourth parameter of the `inherit` call.  It's not apparent why this is done like this - perhaps the code was done before `inherit` supported statics?  At any rate, I'd be willing to clean this up but would like someone to take a look first and make sure I'm not misunderstanding this.  Assigning to @jessegreenberg to see if he concurs that this should be changed.

**Comment by jbphet** [comment]
Also, I'm not sure why these methods are static and not just methods on the `BalloonModel` instance.  Most if not all of them require an instance of the balloon model.

**Comment by jessegreenberg** [comment]
I agree with both comments @jbphet I will take a stab at this change.

**Comment by jessegreenberg** [comment]
In the above commit I moved almost all functions of BalloonModel to the prototype since they required the instance of the BalloonModel as a param.  getForce was the only one that I moved to statics, but all were moved to the inherit call.  Closing.

**Comment by jessegreenberg** [comment]
I also updated the JSDoc quite a bit
