### ISSUE TITLE
Add "Insights into Student Use" section to the Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balloons-and-static-electricity#242]
Add "Insights into Student Use" section to the Teacher Tips based on the discussion in #127.

**Comment by arouinfar** [comment]
If the changes in #244 are published, I'll also need to update the screenshots.

**Comment by arouinfar** [comment]
@ariel-phet now that the loose string has been approved, do you know when the next release will be? I'd like to update the Teacher Tips with new screenshots and revise the Model Simplifications a little bit, and have that timed to the next release.

**Comment by ariel-phet** [comment]
@arouinfar probably discuss with @jessegreenberg or @jbphet - I am not sure if the loose string change would require a maintenance release or a full retest. (pretty sure it could be a maintenance release). If so, you can coordinate with @jessegreenberg once you have the Tips redone.

**Comment by arouinfar** [comment]
I've updated the Teacher Tips, so I'll go ahead and close this issue. I'll coordinate with @jbphet and @jessegreenberg to find out when the sim will be republished.
