### ISSUE TITLE
sim does its own dt calculation, using milliseconds instead of seconds

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#243]
Issue moved from phet-io repo https://github.com/phetsims/phet-io/issues/1005 and discovered during instrumentation:

The file BalloonsAndStaticElectricty.js contains a step function with the code:

      var curTime = Date.now();
      var dt = curTime - this.oldTime;

      this.balloons.forEach( function( balloon ) {
        if ( balloon.isVisibleProperty.get() ) {
          balloon.step( self, dt );
        }
      } );

      this.oldTime = curTime;

The step function is supplied a dt value by the framework, so I have no idea why this is being done. Also, it ends up providing a value that is in milliseconds instead of seconds (as our framework does), so to fix this some work would likely need to be done on the balloon model code.

**Comment by samreid** [comment]
This is likely to be the cause of https://github.com/phetsims/phet-io/issues/994

**Comment by samreid** [comment]
Fixed in the preceding commits, @jessegreenberg can you please verify?

**Comment by jbphet** [comment]
Ideally, we would change the other portions of the simulation to use the dt value without requiring it to be multiplied by 1000.  I'll leave it to @jessegreenberg to determine whether this would take too much effort to make it worthwhile or not.  If it can be done in an hour or less, I'd say go for it, otherwise close this and move on.

**Comment by jessegreenberg** [comment]
I want to take a look at this before #246.

**Comment by jessegreenberg** [comment]
It doesn't look like there is really a physics model in this sim, other than the electric forces feel sort of like ```kqq / r^2```.  But the actual model uses ```kqq / r^3```, k is 0.1 for the sweater charges and 10000 for the wall charges, q's are the integer number of charges on each object, and r is the distance in ScreenView coordinates. My guess is the values were chosen to look natural and most like the Java version.  We can change the sim to use the normal dt value without multiplying it by 1000, but it is all pretty arbitrary.

**Comment by jessegreenberg** [comment]
The sim looks good with https://github.com/phetsims/balloons-and-static-electricity/commit/5f4765cc5f321a7b12648e9ffaf379ff20cae8ac and https://github.com/phetsims/balloons-and-static-electricity/commit/08c47e9f1932871f1223b0204c0877e691e6003c @samreid.

@jbphet given https://github.com/phetsims/balloons-and-static-electricity/issues/243#issuecomment-279564121 I am inclined to close this issue.  I think it would take less than an hour to change, but it would involve replacing
```js
      var dt = dtSeconds * 1000; // seconds to milliseconds
```
with tweaks to constants in BalloonModel, WallModel, and other places to make the sim look and feel the same.  I will clarify this where the constants are defined in the code.

**Comment by jessegreenberg** [comment]
I added some doc to clarify https://github.com/phetsims/balloons-and-static-electricity/issues/243#issuecomment-279564121.  Closing.
