### ISSUE TITLE
Try attaching balloon to ground with loose string

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balloons-and-static-electricity#244]
In #127 @ariel-phet suggested:

>Attach balloons to a string from the bottom, but have a somewhat "loose string" the same way we do for cables on meter bodies like in concentration. I think the main visual that gives the impression of a helium balloon is the string is very "taut" in this visual, which makes you feel like there is a strong upward force. I think a somewhat loose string would better express the idea of "neutrally buoyant" and might feel natural and not cause other issues with the sim. Would that be tough to implement and take for a test drive?

A taught string cue that the balloon is helium-filled, while a loose string may make it easier to perceive the balloon as neutrally buoyant.

@ariel-phet please prioritize.

**Comment by ariel-phet** [comment]
@jessegreenberg is this something you would be willing to try implementing (since you have been the main person on BASE for awhile)? If not, please assign back to me.

**Comment by ariel-phet** [comment]
Marking as medium, since it seems we are considering getting this sim republished in the "near'ish" future ideally with keyboard nav, so it would be good to settle this design question

**Comment by jessegreenberg** [comment]
Sure, I will take a look at this.  

> sim republished in the "near'ish" future ideally with keyboard nav,

I don't think keyboard nav can be ready for a publication in the near-ish future, there is still a fair amount of work to do like this sim's keyboard help dialog, radio buttons, graphical indication of how to play with the balloon, and such.

**Comment by jbphet** [comment]
I've implemented this, and @arouinfar had a look and has initially approved.  Assigning to @ariel-phet to check it out on master and, if he's cool with it, he can close the issue.

Screenshot:
![base](https://cloud.githubusercontent.com/assets/3082831/22573915/bde4864c-e968-11e6-8549-dfe8eb0ffb66.png)

**Comment by ariel-phet** [comment]
@jbphet @arouinfar I personally really like this change. 

Might be good to see what @kathy-phet thinks. 

Assigning back to @jbphet to show at next status meeting if @kathy-phet has not commented.

**Comment by jbphet** [comment]
I demonstrated this to @kathy-phet, and she thought it looked good.  Closing.
