### ISSUE TITLE
Re-record sim primer

### ISSUE THREAD

**Issue by arouinfar** [phetsims/balloons-and-static-electricity#250]
From #241 

> There's only one teaching example in the primer that uses two balloons. The narrator refers to like charges repelling, but makes no explicit mention of the sweater. A balloon is used to repel the other balloon off the sweater three times during this chunk of the primer. What makes things tricky is that the narrator's outro is also recorded over the two balloons repelling, so we can't just edit that part out. If you want to take a look at the primer, the relevant section is ~1:50-2:10.

A charged balloon should not be able to dislodge the other balloon from the sweater. This behavior is exhibited in the sim primer, which will need to be re-recorded.

**Comment by arouinfar** [comment]
Talking to @amyh-phet, it sounds like we can keep the same audio track, but re-record the screen capture. Reassigning to @amyh-phet.

**Comment by amyh-phet** [comment]
New screen capture completed.  Video produced, subtitled, and live on website.
