### ISSUE TITLE
Propagate QA credits to other branches

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balloons-and-static-electricity#255]
@jessegreenberg the 1.1 branch is the only one with QA credits. Please copy the credits from the 1.1 branch to all other appropriate branches (I'm thinking master, 1.2, and 1.2-phetio) AND add "Ethan Johnson". Other than that, current 1.1 QA credits are good.

For phetsims/tasks/issues/795

**Comment by jonathanolson** [comment]
Added to master/1.2/1.2-phetio.

@phet-steele, look good?

**Comment by phet-steele** [comment]
Done, thanks @jonathanolson!
