### ISSUE TITLE
Identify challenges for charge view descriptions for Balloons and Static Electricity

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#257]
The Balloons and Static Electricity sim has thee different views for charges:

1. Show all charges (default)
2. Show no charges
3. Show charge differences

We have described the first view (all charges) using relative amounts (none, a few, several, many). Beginning to explore design questions for describing the other 2 views in this google sheet. I will post questions for discussion in this issue.

Note that views 2 and 3 may be most relevant for teachers.
Moving this issue here from the a11y-research repo.

**Comment by terracoda** [comment]
@terracoda is working in a google doc called [BASE: Charge Views](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.dutyxmd7brtv) to identify challenges and design descriptions.

**Comment by terracoda** [comment]
_**Challenge 1:**_ letting the user know what changes when they select a radio button in the list.

**h3: Charge Views**
- radio label: Show all charges
- radio label: Show no charges
- radio label: Show charge differences

**Interactive Alerts to announce the change on selection**
- All charges shown in this view.
- No charges shown in this view.
- Only charges differences shown in this view.

More drafted examples [in design document](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.4ajyxniemtvu),  but I think with this style of alert, we can remove the emphasis on “No charges shown” in the PDOM descriptions for the _Show no charges_ view. See design document and _Wall case 3_ and _Sweater cases 1-5_.

Any comments on these three interactive alerts, @emily-phet, @jessegreenberg.

**Comment by terracoda** [comment]
_**Challenge 2:**_ Text of dynamic descriptions
Given the information provided by the interactive alerts in (https://github.com/phetsims/balloons-and-static-electricity/issues/257#issuecomment-304873851), I outlined five questions in the design document for the dynamic descriptions for the Wall, Sweater and Balloon related to what to include in the Dynamic Descriptions in the additional 2 Charge Views.

Please see [Dynamic Descriptions in the design document](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.r9wdku23hc7t).

**Comment by jessegreenberg** [comment]
@terracoda I have a slight preference for some of the other styles of alerts like "All charges shown" or "Showing all charges".  Alerts up to now have been more active like "Wall removed",  "Balloon Added", "Sim sound off".  "All charges shown in this view" sounds more like an on-demand description than an alert to me.

**Comment by jessegreenberg** [comment]
But I do understand if it aligns better with other descriptions.

**Comment by terracoda** [comment]
@jessegreenberg, good point. Is it the "in this view" part that makes it sound less action-oriented to you? That's the part I was trying to work in.

Do these sound any better?
- Showing all charges in this view.
- Showing no charges shown in this view.
- Only showing charges differences in this view.

Perhaps the heading _"Charge Views"_ and the labels do enough to make is clear that one is just changing how the charge information is presented. There will also be the on-demand help text, "Choose how you see or hear charge information."

**Comment by terracoda** [comment]
@jessegreenberg, after discussing with @emily-phet, we decided to try the verb "hidden" to emphasize success of the interaction without repeating the label text. So I have 4 options. How do you think these sound? Options 3 and 4 are obviously longer than desired, but may be helpful for some learners. 

**Option 1:**
- No charges hidden.
- All charges hidden.
- Pairs of charges hidden.

**Option 2:**
- No charges hidden.
- All charges hidden.
- Only charge differences shown.

**Option 3:**
- No charges hidden.
- All charges hidden.
- Pairs of charges hidden, only charge differences shown.

**Option 4:**
- No charges hidden.
- All charges hidden.
- Only charge differences shown, pairs of charges hidden.

**Comment by emily-phet** [comment]
@terracoda How about "only unpaired charges shown" for the alert when "charge differences" view is selected?

**Comment by terracoda** [comment]
@emily-phet, that could work. So you are thinking these three alerts:

**Option 5:**
- No charges hidden.
- All charges hidden.
- Only unpaired charges shown.

**Comment by emily-phet** [comment]
@terracoda Yup!

**Comment by jessegreenberg** [comment]
@terracoda the alerts for the charge view radio buttons have been implemented.  Can this be closed?

**Comment by terracoda** [comment]
@jessegreenberg, yes. Closing.
