### ISSUE TITLE
BASE Design Check List (Laundry List Milestone)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#258]
I lost my list on on February 2, 2018. I don't know how.
Everything was done, so it is not such a tragedy.

**Comment by emily-phet** [comment]
@terracoda Looks good, very helpful to have one spot for an overview.

**Comment by terracoda** [comment]
@emily-phet I just un-assigned you, but maybe you want to stay on the issue as an assignee?

**Comment by terracoda** [comment]
@emily-phet, except for "Independent Movement for Second Balloon", I think I am on track.

**Comment by terracoda** [comment]
Some how my list disappeared??

**Comment by terracoda** [comment]
I am closing this issue.
