### ISSUE TITLE
do a maintenance release on 1.2-phetio to get lazyLink and reset support

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#261]
Version 1.2-phetio is being used by the sonification wrappers to test out different sound designs.  Currently, support for 'lazyLink' does not exist in this version.  Also, there has been talk of trying out some things to make it so that reset can be done without causing separate sounds for every parameter that gets reset.  I'll also try to pick up this functionality in this maintenance release in order to support testing.

**Comment by jessegreenberg** [comment]
@jbphet there is now a 1.3-phetio, is this issue still relevant?

**Comment by jbphet** [comment]
Nope, this is resolved.  Thanks for the ping.  Closing.
