### ISSUE TITLE
"scene switch" buttons not accessible

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#264]
This was originally reported by @terracoda in https://github.com/phetsims/balloons-and-static-electricity/issues/240#issuecomment-301904698, I'm moving it into a separate GitHub issue.

@terracoda said:
> The scene switch and the radio buttons are not keyboard accessible in this view. Is that intentional? Or should I start new issues for those items? The radios have never been accessible. They have been turned off for most of my research activities thus far. The scene switcher, however, has been keyboard accessible in earlier versions.

I believe the "scene switch" buttons to which she is referring are the ones for switching between one two two balloons.  I tested on the current master version, and indeed, this selector is never highlighted when tabbing through the keyboard accessible items.  Oddly, the "Reset Balloons" button appears to be selected twice when tabbing through the items, and since this button is immediately below the scene switch buttons, I suspect this is related.

Assigning to @emily-phet to prioritize and assign.

**Comment by terracoda** [comment]
@jbphet, yes I am referring to the _Two-balloon experiment_ switch.

**Comment by jessegreenberg** [comment]
I am fixing this now.

**Comment by jessegreenberg** [comment]
Fixed with the above commits, closing.
