### ISSUE TITLE
add query parameter to show visual grid

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#265]
This was originally requested by @terracoda in https://github.com/phetsims/balloons-and-static-electricity/issues/240#issuecomment-301907922, I'm moving it into a separate GitHub issue.

@terracoda said:

> [I]s it possible to add a parameter that allows me to use the visual grid, so I can more easily work on the descriptions? @jessegreenberg had one set up for me before. It might be just be "grid", but the following link doesn't swap the background for the visual grid background.
>
> http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.2/balloons-and-static-electricity_en.html?grid
>
> Would it possible to do that for me?

I looked at `BalloonsAndStaticElectricityQueryParameters.js` and didn't see any parameters that looked like they were related to showing the visual grid.  Perhaps this was a one-off thing that @jessegreenberg did.

Assigning to @emily-phet to prioritize and assign.

**Comment by terracoda** [comment]
@jbphet the visual grid that I mentioned is posted in issue https://github.com/phetsims/balloons-and-static-electricity/issues/227, but here's copy for here.
![bs-grid-upper-lower-regions](https://cloud.githubusercontent.com/assets/1902116/26171593/11b27dfc-3b20-11e7-8187-32521922cc79.png)

The grid parameter that @jessegreenberg main available to me was quite some time ago.

**Comment by jessegreenberg** [comment]
I just added query parameter "showGrid" to see the grid.  Sorry, it was previously made visible with query parameter "dev", which wasn't the best.

@terracoda the grid is still out of date, and doesn't look like the one in your image yet, but the showGrid will make it visible moving forward.  Closing.

**Comment by terracoda** [comment]
Thanks @jessegreenberg!
