### ISSUE TITLE
Add Enter key as way to release the balloon

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#267]
In recent design discussions for the keyboard shortcuts dialog (issue #263), and the design of visual grab cues for the balloon (issue #206), questions have come up as to why only the **Space key** works to release the balloon. And, I feel that this is mostly a side effect of early design choices. Based on iterations, since then, for the grab interaction, it now makes sense to add the **Enter key** to the key presses that release the balloon.

**History**
The initial design for the grab and drag was a custom one, press any Arrow key to grab and start dragging the balloon, and Space and Control Enter (Windows Only) were chosen for the release interaction. After user testing, nobody used Control Enter, so we dropped support for that key pattern.

Furthermore, the combined custom grab/drag interaction was fraught with technical problems due to they way screen reader software reserves the use of the Arrow keys for navigation. The combined interaction was also complicated for screen reader users, so we changed the interaction to a 2-step process, a native grab, then a custom drag. 
1. A grab button (a native button interaction) launches the move mode (drag/rub mode) with Enter or Space.
2. Once the user actively grabs the balloon, they get instructions on the custom interaction.

Now that we know the grab interaction (Space and Enter) works well for screen reader users, it seems to make sense to align the release interaction to be both **Space and Enter**, too.

Any objections, @emily-phet, @jessegreenberg.

**Comment by terracoda** [comment]
And FYI, @arouinfar and I have already updated the Keyboard Shortcuts dialog (#263) to reflect this change. A wonderful side effect is that adding **Enter** to the release really shortens the amount instructions needed.

**Comment by jessegreenberg** [comment]
Done in the above commit, though I want to test in several browsers before closing.

**Comment by jessegreenberg** [comment]
Indeed, very broken in Firefox.

**Comment by jessegreenberg** [comment]
Problem is in scenery, Firefox iterates over the listener objects differently than chrome.

**Comment by jessegreenberg** [comment]
It is including things in its enumerable list that Chrome doesn't.

**Comment by jessegreenberg** [comment]
Working in Chrome, Firefox, Edge, and IE11. Closing.
