### ISSUE TITLE
Description review 

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#269]
Testing descriptions with Voice Over, Safari 10.0.3 on Mac OS Sierra 10.12.3
Sim version: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.6-dev.2/balloons-and-static-electricity_en.html?hideChargeControls

Some of these issues may be addressed already in later versions:

- [ ] "At wall" read out when JW is used without Wall present. It should say it's position in the Play without the wall, something like right side of Play Area.
- [ ] Can't reproduce, but once while moving green balloon towards right with no wall present, I heard descriptions as if wall was present, but I can't reproduce.
- [ ] Grid description slightly off (being addressed with new grid documentation).

I am putting issues here that I find as I do intermittent testing while designing.
Will add to this list.

**Comment by jessegreenberg** [comment]
Thanks for testing @terracoda.  Accessible content has been almost entirely reimplemented since 1.1.6.

These issues in particular should no longer be a problem, closing.
