### ISSUE TITLE
Charg View Challenge: Rubbing on Sweater and Not Picking Up Charges

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#270]
Related to issue #257, when "Show charge differences" is selected, one difficult thing to do is to cue the user on how to "find useful places to rub" when the useful areas on the sweater are actually blank "neutral" spaces.

In the _Show all charges_ view we have 3 interactive alerts that describe 
1. where to find more pairs of charges
2. when the last negative charges are picked up
3. a reminder to release if the user continues with unproductive rubbing once sweater is visually depleted of negative charges.

Here's the draft wording for the same 3 alerts, but when _Show charge differences_ is selected. 

1. **Alert 1 - finding more productive rubbing space, i.e. more pairs**
  No change in [[net charge]]. On [[left side]] of sweater. [[More hidden pairs of charges]] [[down and to the right]].

2. **Alert 2 - indication that there no more places to rub and get a change in charge**
  Sweater has [[positive net charge]], showing [[all]] positive charges. [[Yellow balloon]] has [[negative]] net charge, showing [[many]] negative charges. 

3. **Alert 3 - a reminder to release if unproductive rubbing continues**
  No change in [[net charge]]. On [[lower-right arm]] of sweater. [[Press Space to release]].

Alert 1 is the toughest. Other possible phrases:
- [[More neutral spaces]] down and to the right.
- [[No charge differences]] down and to the right.
- [[No charge differences found]] down and to the right.

Comments welcome @emily-phet, @jessegreenberg, and others.

A side-by-side comparison of the alerts for all three views is available [here in the design document](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.acxl37jgsh7b).

**Comment by terracoda** [comment]
Question for @emily-phet, I think it is a good idea to use the words "net charge" it Alert 1, rather than just "charges". I think it helps focus this view on "net charge."

Any thoughts?

**Comment by emily-phet** [comment]
@terracoda I like the Alert 1 you have above with "more hidden charges". I agree using "net charge" is a good choice here.

**Comment by terracoda** [comment]
@emily-phet, great, and just to be clear, you like "more hidden **pairs** of charges", right :-) ?

**Comment by emily-phet** [comment]
@terracoda - yes "more hidden pairs of charges".

**Comment by jessegreenberg** [comment]
@terracoda can this issue be closed?  Has this been reflected in the design document?

**Comment by terracoda** [comment]
@jessegreenberg, yes this is reflected in the design document. Closing issue!
