### ISSUE TITLE
Charge View Challenge: Interactive Grab Alert

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#271]
Related to issue #257, when "Show charge differences" is selected, the information provided upon grabbing the balloon changes slightly.

A side-by-side comparison of the grab alert for all three views is available [here in the design document](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.2rq0f331igo1).

How do these descriptions sound, @emily-phet? 

**Balloon is sticking to sweater when it is grabbed:**
- Grabbed. Sticking to right arm of sweater. Has [[negative]] net charge,  [[a few negative]] charges showing. Sweater has [[positive]] net charge, [[a few positive]] charges showing. Press W, A, S, or D key to move balloon. Space to release.

**Balloon is sticking to wall when it is grabbed:**
- Grabbed. Sticking to upper wall. Yellow balloon has [[negative]] net charge, a few negative charges showing. Wall has [[no]] net charge, [[no]] charges showing. Press W, A, S, or D key to move balloon. Space to release.

**Balloon is neutral and touching wall when it is grabbed:**
- Grabbed. Touching wall. Yellow balloon has [[no]] net charge, [[no]] charges showing. Wall has [[no]] net charge, [[no]] charges showing. Press W, A, S, or D key to move balloon. Space to release.

**Comment by jessegreenberg** [comment]
@terracoda is this issue still relevant?  Or has the wording been settled in the new design document?

**Comment by terracoda** [comment]
@jessegreenberg, yes this main part of the alerts has been reflected in the design document, and the "sticking state" is no longer relevant as we just changed that yesterday. Closing this issue.

**Comment by jessegreenberg** [comment]
Based on comment https://github.com/phetsims/balloons-and-static-electricity/issues/271#issuecomment-322664011, I think this issue can be closed.
