### ISSUE TITLE
Polarization does not seem evenly centered around the balloon

### ISSUE THREAD

**Issue by phet-steele** [phetsims/balloons-and-static-electricity#273]
The red line below shows the approximate electron "center" for the balloon, the point around where I would expect the wall to be polarized. Instead, the green line shows the approximate center of the polarization curvature, which is much lower. In other words, it looks like the bottom of the balloon is polarizing the wall much more than the top of the balloon, even though the balloon has a visually even distribution of electrons.
![img_0062-1](https://user-images.githubusercontent.com/5863899/26898696-1813fa02-4b8a-11e7-8a3d-47252d0dfb01.PNG)

This has been a problem since 1.0.0. Java seemed to handle this better since it had a lower electron "center":
<img width="747" alt="screen shot 2017-06-07 at 2 04 36 pm" src="https://user-images.githubusercontent.com/5863899/26898912-bc0692aa-4b8a-11e7-94f3-0837e890aa06.png">

I chose to show this with max electrons on the balloon for the sake of making this visually clearer, but it happens all the same with any amount of negative charge. @ariel-phet is this incorrect, and what say you about addressing this?

**Comment by ariel-phet** [comment]
@phet-steele I cannot say I have every noticed this issue before, but it does seem incorrect. 

@jessegreenberg do you mind taking a look since you have been in this sim quite a bit?

**Comment by jessegreenberg** [comment]
Sure, I will take a look.

**Comment by jessegreenberg** [comment]
![using-center](https://user-images.githubusercontent.com/6396244/27051221-8e0aad0a-4f72-11e7-9316-3b9386bc4141.PNG)

Red line is balloon center, green line is the average y position of the balloon's charges.  WallModel is using balloon center to place charges in the wall, it should be placing relative to center of charges.

Even using the red line, the u shape looks too low.

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/27052740-e8bd315a-4f77-11e7-8c5e-7bacd26d0156.PNG)

Should be fixed in the above commit.

**Comment by jessegreenberg** [comment]
@phet-steele @ariel-phet can you verify this is fixed?  You can use green line to see vertical charge center with query parameter ```showBalloonChargeCenter```

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.3/balloons-and-static-electricity_en.html?showBalloonChargeCenter

**Comment by jessegreenberg** [comment]
If we add many more charges, it looks like this (just so you can see the U shape of the charges:
![i4 cimgpsh_orig](https://user-images.githubusercontent.com/6396244/27093208-189b1da0-5023-11e7-80ac-4f1947bfb692.png)

@ariel-phet, one thing @phet-steele and I were wondering, does the peak of the 'U' shape need to change depending on how many/where charges are in the balloon?

**Comment by ariel-phet** [comment]
@jessegreenberg current behavior in https://github.com/phetsims/balloons-and-static-electricity/issues/273#issuecomment-307909372 looks great. I don't think the peak of the U shape needs to be altered from its current behavior.

**Comment by jessegreenberg** [comment]
Sounds good.  Should this get patched into a maintenance release or OK to let this go out next time this is deployed off of master? https://github.com/phetsims/balloons-and-static-electricity/commit/d99656fe3c5f97ac8f013971046a0001f155547f included one new function, spot checking seems sufficient.

**Comment by ariel-phet** [comment]
@jessegreenberg I think a maintenance release would be appropriate since it is actually buggy physics.

**Comment by jessegreenberg** [comment]
Maintenance RC spot check task was created in https://github.com/phetsims/tasks/issues/861.

**Comment by phet-steele** [comment]
Nice, thanks @jessegreenberg. Looks to be running well.
