### ISSUE TITLE
Yellow and Green balloon stick to the same location on Sweater?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#279]
Should it be possible for the two balloons to stick to the exact same spot on the sweater?
Adding and removing the wall has no effect. Is this just an optical illusion of the 2-D representation? Are the balloons actually beside each other on the sweater? Obviously, the yellow balloon is not sticking to the green balloon, but it is difficult to tell in this case?

@jessegreenberg could this behaviour be at all related to @samreid's fix to @pixelzoom's comments in https://github.com/phetsims/balloons-and-static-electricity/issues/67?

<img width="534" alt="two-balloons-same-spot" src="https://user-images.githubusercontent.com/1902116/27917388-689b24a0-6246-11e7-9f9b-f3db2bf4f4ed.png">

[Version 1.3.0-dev.6](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.6/balloons-and-static-electricity-a11y-view.html)

**Comment by jessegreenberg** [comment]
Good question @terracoda, I am not sure if this is an issue.  The balloons are at the same location.  In http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.0-rc2/balloons-and-static-electricity_en.html (from https://github.com/phetsims/balloons-and-static-electricity/issues/67) the charged balloons can still push each other off the sweater so this wasn't happening.

I think this is related to https://github.com/phetsims/balloons-and-static-electricity/issues/241 because the solution to that issue prevents balloons from being pushed off the sweater.

@ariel-phet @arouinfar @terracoda is this an issue and does it require a fix?

**Comment by terracoda** [comment]
@jessegreenberg, @ariel-phet, @arouinfar I'm trying to understand the locations of the balloons, so I can describe it accurately. The yellow balloon is not "on the green balloon", but maybe "near" it or "beside" it.

**Comment by jessegreenberg** [comment]
The current description strategy describes things relative to the play area, wall, and sweater. If the yellow balloon is "sticking to lower right side of sweater", and green balloon is "touching lower right side of sweater" would that  naturally be descriptive enough to indicate that the two balloons are near each other?

**Comment by jessegreenberg** [comment]
@terracoda, @ariel-phet @arouinfar and I played with the sim and reproduced the case you pointed out in your screenshot.

We discussed trying a a solution where when the balloons overlap on release we bump the one on top to the left a little bit so it is clear that they are  not in the same location.

This would not apply a force on the balloon, nor would the top balloon pick up charges as it moves over a little.  But it might solve this UI issue.

I am not sure how this might impact descriptions, do you have any thoughts on this solution?

**Comment by arouinfar** [comment]
Thanks for summarizing @jessegreenberg!

**Comment by terracoda** [comment]
@jessegreenberg, re https://github.com/phetsims/balloons-and-static-electricity/issues/279#issuecomment-313484207, yes, that is what I was thinking about. But more in the case where a release happens. Once a balloon is released, the user reads both descriptions, and both descriptions read as "sticking to lower right side of sweater". 

During interaction, the user will likely only get information about the ungrabbed balloon if it moves. However, I was exploring when (if ever) is the location of second balloon needed during interaction, especially when a release happens just at the edge of the sweater while also near the second balloon. In this case, the released balloon behaves quite dramatically (flies up and around, or over to the wall, or over to the right edge and then back again).

If the balloon is released directly on or under the second balloon (technically just inside the edge of the sweater), no movement at all happens.

I was wondering if this dramatic difference in sim behaviour warranted adding some indication of proximity to the release alert, like "Green balloon released [[near other balloon]]". This could help explain why the balloon flies off so dramatically, but it doesn't explain why it doesn't move away from the second balloon if they are both in the exact same place just on the inside edge of the sweater.

I think it makes perfect sense to have the released balloon move off the second balloon a little to the left. It would look like the balloon is attracting more to the sweater than the other balloon. I also think this solution is more inline with the issue @phet-steele outlined in an earlier issue (lack of movement upon release at sweater edges).

If the balloon moves just a little, I think I already have a description for small movement for releases on sweater. 

Appending the already existing "sticking state & location" of the second balloon at the very end of the release alert should help explain the different balloon behaviours when the balloon is released near the other balloon without having to add the "near other balloon" wording explicitly.

Sorry for the long post to say I agree with the suggested solution, and I don't think it will negatively description work.

**Comment by jessegreenberg** [comment]
Sounds good @terracoda thanks for the description of your thoughts on describing this case.

**Comment by jessegreenberg** [comment]
The balloon will shift a little bit when released while overlapping the sweater.  The balloons can also overlap in the play area (while neutral) and when sticking to the wall.

@arouinfar @ariel-phet  should the balloon also shift in those cases?

Overlapping in these cases has always been possible (at least in the HTML5 versions).

**Comment by arouinfar** [comment]
@jessegreenberg overlapping the balloons on the sweater is a little problematic because it creates the illusion that the balloons are stuck to one another, rather than the sweater. I think the wall could be perceived as having some depth, meaning overlapped balloons would be next to one another. I wouldn't be opposed to vertically bumping a balloon along the wall, but I don't see it as being necessary. Completely overlapped neutral balloons in the play area do not need to shift at all.

**Comment by terracoda** [comment]
@jessegreenberg, I agree with @arouinfar. The wall has hidden depth where the sweater does not, so not necessary to shift balloons there - only on the sweater.

**Comment by ariel-phet** [comment]
Agreed with @arouinfar and @terracoda

**Comment by jessegreenberg** [comment]
The balloon should now move slightly to the left to prevent occlusion when the balloons overlap on the sweater.  @arouinfar @terracoda @ariel-phet could you please review how it behaves in this version?

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.4/balloons-and-static-electricity_en.html?accessibility

**Comment by arouinfar** [comment]
Looks good to me @jessegreenberg!

**Comment by terracoda** [comment]
Looks good to me, too @jessegreenberg.

**Comment by ariel-phet** [comment]
Looks good to me.

**Comment by ariel-phet** [comment]
@terracoda I assume you could close this now?

**Comment by terracoda** [comment]
Yes, closing. Thanks, @jessegreenberg.
