### ISSUE TITLE
Small oscillating balloon movement in two-balloon scenarios? Is it a bug?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#280]
In two-balloon scenarios when one balloon with a small amount of charge (2-5 charges) repels balloon and goes to wall, it will return to sweater (depending on where the other balloon is), and when it returns it travels slowly all the way back to left edge, bounces back a little and then sticks to lower left side of sweater, or lower left arm of sweater. It may oscillate a little on the sweater before settling into a sticking-on-sweater state. I have only seen this behaviour from the lower wall to the lower sweater. In a similar scenario, when it travels back to the upper part of the sweater, it sticks as soon as it reaches the sweater. 

@jessegreenberg and @ariel-phet, is the bounce off the lower left edge intentional behaviour?

To reproduce, gather a very small amount of charge on one balloon, empty the sweater of charge with the other balloon. Place the heavily charged balloon on the lower left arm, and the lightly charged balloon against the lower wall. Then slide the heavily charged balloon up the sweater's arm. The lightly charged balloon will start back to the sweater and do it's little dance.

**Start positions**
<img width="482" alt="set-up-position-01" src="https://user-images.githubusercontent.com/1902116/28125890-87f2feca-6702-11e7-9e20-3b88a4610b22.png">

**Move Green balloon up** and yellow balloon attracts to sweater and bounces off left edge before sticking to sweater.
<img width="475" alt="balloon-2-attracting-to-sweater" src="https://user-images.githubusercontent.com/1902116/28126264-92498276-6703-11e7-9d6f-0714d95d3c38.png">

**Comment by terracoda** [comment]
My testing was made in version [1.3.0-dev.6](http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.6/balloons-and-static-electricity-a11y-view.html).

**Comment by terracoda** [comment]
Description question for @ariel-phet, since the yellow balloon does not stay at the wall in the above case, is actually "sticking" at any point before it moves? Or does it just look like it is sticking?

I am asking because, I think in the model we might need to add a threshold for level of charge to more accurately describe when a lightly charged balloon is actually "Sticking to wall."

**Comment by jessegreenberg** [comment]
I just reproduced the behavior, I think this is correct @terracoda, but I am not entirely sure. The yellow balloon moves across the bottom of the screen because it is repelled by the green balloon. When it hits the left edge, the x component of the velocity is set to zero, but it isn't quite on the sweater yet. It moves back up and onto the sweater because the attractive force from the sweater is then greater than the repulsive force from the other balloon.

@arouinfar can you please also take a look at this?

**Comment by arouinfar** [comment]
@jessegreenberg @terracoda I also reproduced this issue, and I believe this is the correct behavior. The only thing I would add to @jessegreenberg's explanation is that the yellow balloon first moves away from the wall because it is attracted by the sweater, but as it gets closer, the repulsion from the other balloon begins to compete.

**Comment by terracoda** [comment]
@arouinfar and @jessegreenberg, thanks for the explanation. I can't reproduce this behaviour on the upper part of the sim. The balloon just sticks to the sweater on the first pass. Is there a reason for the difference?

**Comment by jessegreenberg** [comment]
The model works by applying a force on the balloon until its center is on the charged area of the sweater. You can see the charged area with query parameter "showSweaterChargedArea":

http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.3.0-dev.6/balloons-and-static-electricity-a11y-view.html?showSweaterChargedArea

So its just about sweater location, along the bottom the balloon center isn't high enough to reach the charged area.

**Comment by terracoda** [comment]
Thanks @jessegreenberg for explaining the charged area of the sweater! 
Now, I just need to describe this behaviour.

**Comment by jessegreenberg** [comment]
@terracoda can this issue be closed?

**Comment by terracoda** [comment]
@jessegreenberg, yes, closing this issue.
Thanks for the explanation.
