### ISSUE TITLE
mouse and touch areas for balloons should be adjusted

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#281]
The mouse and touch areas for the balloons appear to be the rectangle that encloses the image.  This causes issues in some situations, such as when grabbing the green balloon when it is near the yellow balloon.  The following animation illustrates.

![base02](https://user-images.githubusercontent.com/3082831/28132169-47c636cc-66f9-11e7-8f6a-7d19f43362ca.gif)

**Comment by jessegreenberg** [comment]
Thanks @jbphet, i have also noticed this.  Ill can look into this one.

**Comment by jessegreenberg** [comment]
It looks like if you specify touch/mouse areas that are smaller than the Node's bounds there is no change in the size of the clickable bounds.

**Comment by jessegreenberg** [comment]
Maybe we will need to draw some balloons with Scenery to fix this!

**Comment by jessegreenberg** [comment]
Over skype @jonathanolson recommended

> you can put a touch area on a parent and set the actual object to pickable:false if necessary

**Comment by jbphet** [comment]
Definitely an improvement.  I spent a few minutes seeing how hard it would be to make the bottom portion match more closely, but because `ellipticalArcTo` exists but is not implemented in `Shape` it seems like this would be a bit tricky and thus not worth the effort at this time.  Thanks @jessegreenberg, closing.
