### ISSUE TITLE
Balloon location needs preposition change: "At center" not "On center" 

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#291]
Noticed minor mistake in the description string for the balloon's location when it is in the center of the open Play Area. In version 1.4.0-dev.1, the balloon is described as "On center of Play Area," which does awkward to me.

All locations are described using only "at" and "on". See design doc [Attractive State & Location Pattern](https://docs.google.com/document/d/1WNVq5_-Hc9LSdeZVSn2edlwYwpHtGNT1ThFD9NXpZ5Q/edit#heading=h.qyj0asz27kxx)
 
For the general Play Area locations this means there are two prepositions used "at" for center locations and "on" for side locations. For example,
- "At center of Play Area."
- "At upper-center of Play Area."
- "On right side of Play Area." 
- "On upper-right side of Play Area."
- "On lower-left side of Play Area."

If the possibility of using two different prepositions is not already available, I think it would be less awkward to use "at" for all the open Play Area locations.
- "At center of Play Area."
- "At upper-center of Play Area."
- "At right side of Play Area." 
- "At upper-right side of Play Area."
- "At lower-left side of Play Area."

I don't think using "at" negatively impacts dragging alerts. They might go something like this:
- "Left. Near wall.", "At right side of Play Area.", "Closer to center...", "At center...", "Closer to sweater.", "At left side of Play Area. ", "Near sweater.", "On sweater."
- Also same preposition is use din "At top." and "At bottom."

@jessegreenberg, is the simplest solution just changing the "on" string to "at"? And if so, do you see any potential issues with that change? I can't think of any at the moment.

**Note that** "On sweater."  and "At wall." are fine.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, we could do either.  Changing all to  "At" is the simplest solution, but not  substantially so.  What do you think is best?

**Comment by terracoda** [comment]
I like it best with the two prepositions, "at" for center locations and "on" for the side locations. Changes to the original phrases at this point may have consequences.

I also like the break in "At" in the center. "On" makes the center a one-syllable landmark if someone is moving fast.

**Comment by jessegreenberg** [comment]
Sounds good.

**Comment by jessegreenberg** [comment]
@terracoda fixed in the above commit, behaves like the first list in https://github.com/phetsims/balloons-and-static-electricity/issues/291#issue-255979432.
