### ISSUE TITLE
Balloon described locations missing "near" objects

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#297]
In described grid, I am never hearing "near sweater" or "near wall".  @terracoda pinging you since this is happening in the version  I just sent you.

**Comment by jessegreenberg** [comment]
Fixed in the above commit, closing.

**Comment by terracoda** [comment]
@jessegreenberg, not an issue in latest version.

**Comment by jessegreenberg** [comment]
Great! I would have expected this to be in the version I sent you.

**Comment by terracoda** [comment]
hmm, I will check again ;-) I know I heard it, but maybe when I used the JN and JS keys.

**Comment by terracoda** [comment]
@jessegreenberg, you were right. Using the cursor keys version 1.4.o-dev4 did not have this landmarks, but I heard them with the JS and JN hotkeys. Sorry for the confusion.

Looks like you fixed it.
