### ISSUE TITLE
Awkward release string on left side of Sweater.

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#298]
When I release a balloon at the left edge (close to left side of sweater), the release string, includes "right towards wall", which is technically true, but the the first object to the right is the sweater, and the balloon attracts to the sweater and then stays there.

I think it would be better to use the closest object in the direction of movement in the release string, so a release on the left edge of the Play Area says,

"Released. Moved very quickly right towards sweater. Sticking to left arm of sweater."

Actually, maybe we don't need to object in this phrase at all, just velocity and direction. This would make the release phrase much shorter, and increase the chances of it actually being read out. 

"Released. Moved very quickly right. Sticking to left arm of sweater."

@jessegreenberg, I think it makes sense to remove the destination object from that phrase. What do you think. I will have to review the examples, but I don't imagine any terrible ramifications from this change.

**Comment by jessegreenberg** [comment]
Good point @terracoda.

> Actually, maybe we don't need to object in this phrase at all, just velocity and direction. This would make the release phrase much shorter, and increase the chances of it actually being read out.
> "Released. Moved very quickly right. Sticking to left arm of sweater."

I like this a lot! But just to clarify, this would be removed in ALL release cases, not just when moving to the right when the balloon is released to the left of the sweater, correct?

**Comment by terracoda** [comment]
Yes, definitely "all release cases."

**Comment by jessegreenberg** [comment]
Great, lets do it!

**Comment by terracoda** [comment]
OK, I will update the Release Alert section in the design documents. And see if there are any ramifications, but I don't think there will be any.

**Comment by jessegreenberg** [comment]
@terracoda change applied in the above commit, "to object" phrase removed.  Removing my assignment.

**Comment by terracoda** [comment]
@jessegreenberg, I updated the document.
In more complex alerts, Release Movement Pattern 4, I had to replace the "towards destination" string with the "direction" string.

Have you implemented Release pattern 4 yet? I think without the destination object it is much more general.

**Comment by terracoda** [comment]
Yes, you have already implemented Release Pattern 4 with direction, so your commit likely takes care of all release. Closing this issue.

**Comment by jessegreenberg** [comment]
Awesome, thanks @terracoda!
