### ISSUE TITLE
Text for Reset balloon(s) alert and is "uncharged" correct?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#299]
In an email @jessegreenberg noticed we had no alert for when the Reset balloon(s) button is
pressed, and suggested:

"Balloons reset to initial locations and charged state." likely, based on the help text for this button, "Reset balloons to start positions and an uncharged state."

**Two issues:**
1. Is the term “uncharged” state incorrect in the help text? Does no net charge mean "uncharged"?

2. Language for reset alert:
  a.  "Balloons reset to initial positions and charged states.", OR
  b. something simpler: “Balloon(s) and sweater reset.” 

I think version 2b is simpler, does not repeat the help text and is more inline with the general reset language: “Sim screen restarted. Everything reset.”

Note that like the “s” on the button’s label, we would need two versions of the alert - one for single balloon resets, and one for two balloon resets.

Personally, I think communicating that the sweater has been reset may be more important than communicating the change in position for the balloon(s). The user will get the balloons’ position when they go try to find them.

@jessegreenberg, what you do you think?

**Comment by jessegreenberg** [comment]
> Is the term “uncharged” state incorrect in the help text? Does no net charge mean "uncharged"?

I was just brainstorming, wasn't considering the wording too much @terracoda so I'll bet it is OK as is.

> something simpler: “Balloon(s) and sweater reset.”

Sounds great to me, Ill add this.

**Comment by terracoda** [comment]
Ok, great! Let's go simple.

**Comment by jessegreenberg** [comment]
Done in the above commit, closing.

**Comment by jessegreenberg** [comment]
Reopening. We aren't preventing the other alerts when this happens, so we are hearing too much on balloon reset.

**Comment by jessegreenberg** [comment]
Fixed in above commit, closing.
