### ISSUE TITLE
inconsistent prefix for filenames

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#301]
This sim mixes conventions for filename prefix.  Some of the files use the "BASE" abbreviation (e.g BASEConstants.js), others use the full name "BalloonsAndStaticElectricity" (e.g. BalloonsAndStaticElectricityQueryParameters.js).

The choice of which convention to follow is up to the developer, but it should be applied consistently.

**Comment by jessegreenberg** [comment]
Made consistent with the above commits, closing.

**Comment by jessegreenberg** [comment]
Changed all to use "BASE" prefix instead of "BalloonsAndStaticElectricity".
