### ISSUE TITLE
Dragging alerts not heard unless moving really slowly (JAWS 18 and Firefox)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#306]
Found in the same user session as to https://github.com/phetsims/balloons-and-static-electricity/issues/305

When we switched to Firefox (a fresh install) and JAWS 18
- No alerts fired, only key presses (A, A, A, ) were read out when moving in Play Area.
- Balloon did pick up negative charge, but I don’t think alerts fired.
- When user moved more slowly in the Play Area, the alerts fired. However, user had to move more slowly than they felt was fun or useful.

@jessegreenberg, I find similar slow movement is needed with VO and Safari, but it did seem more slow than VO.

**Comment by jessegreenberg** [comment]
@terracoda were you able to see the users screen? Was the balloon moving  at all when JAWS said "A, A, A..."?

**Comment by terracoda** [comment]
Yes, I could see the screen and yes they balloon was moving as I heard A, A, A. The user was good at slowing down to the point where they heard the alert, but at that speed it was not very interactive. It was described as 5 or 10 seconds by the user, but probably more like 4 seconds between key presses.

**Comment by jessegreenberg** [comment]
Ok, ill see if I can reproduce the problem.

**Comment by jessegreenberg** [comment]
This and #305 both sound like performance issues to me.  I am not able to reproduce this problem.

**Comment by terracoda** [comment]
I'll find out the system details. It could just be that JAWS an ZOOM (even without screen sharing) just take up too many resources.

**Comment by jessegreenberg** [comment]
@terracoda any more information about this or can it be closed? Alerts sounds great for me with FF and JAWS 18.

**Comment by terracoda** [comment]
@jessegreenberg, I am going to close this issue. We can re-open if the issue shows up again.
