### ISSUE TITLE
Space key doesn't exit forms mode when used to grab the balloon (JAWS)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#308]
As mentioned in #307, during usability testing of BASE version 1.4.0 Dev 4 we found some big difference between Enter and Space key for grabbing and releasing the balloon.

Pressing the Enter key to grab the balloon will exit forms mode and start the application role, thus making the WASD keys available for moving the balloon.

Pressing Space key to grab the balloon does not force JAWS to exit forms mode, so if JAWS is in forms mode when the balloon is grabbed by pressing the Space key, the WASD keys are not passed through to the application. Pressing A will move focus to the next radio button, and pressing W will try to make a word list.

We discovered this after switching the charge view to "Show charge differences" which triggered forms mode, but then after grabbing the balloon (with Space key), the WASD keys would only do JAWS things.

We also noticed that after releasing the balloon with the Space key, JAWS remained in forms mode and the WASD keys did not do their JAWS-y things, and did nothing. The user surmised that JAWS must still be in forms mode and in that case the keys would just be normal typing key presses.

@jessegreenberg, have you experienced such behaviour?

We need to understand better how Enter and Space are designed to be similar, but different.

**Comment by jessegreenberg** [comment]
@terracoda yes, this almost sounds like a duplicate of https://github.com/phetsims/balloons-and-static-electricity/issues/293.

**Comment by jessegreenberg** [comment]
Unfortunately, it looks like  1.4.0-dev.4 includes the workaround that was committed for #293, so it didn't quite fix it.

**Comment by jessegreenberg** [comment]
Information about JAWS and role=application is here: http://www.freedomscientific.com/Support/TechnicalSupport/Bulletin/1404

> These changes only take effect for those form controls that are descendents of the container element with the role of "application".

That could be the problem, i need to make sure that ```application``` is on the parent container element of the balloon.

**Comment by jessegreenberg** [comment]
Yes, here is the balloon
```html
<div id="64-125-356-436-593-437-508" tabindex="0" role="application" >Yellow Balloon</div>
```
It might behave better like this:
```html
<div role="application">
  <div id="64-125-356-436-593-437-508" tabindex="0">Yellow Balloon</div>
</div>
```

**Comment by jessegreenberg** [comment]
I notice that JAWS resists forms mode if I tab to the balloon and very quickly press enter/spacebar to pick it up.  Otherwise, it works consistently whether or not I have application role on the parent element or the balloon div itself.

**Comment by terracoda** [comment]
@jessegreenberg, have you tried entering forms mode before grabbing the balloon with the Space key?

**Comment by jessegreenberg** [comment]
@terracoda with a key command? How do you force JAWS into forms mode?

**Comment by terracoda** [comment]
It seemed in our use yesterday that forms mode (launched by activating a radio button) and the launching of appilication role through the grab balloon button are different modes.

**Comment by terracoda** [comment]
@jessegreenberg, I do not know the key to manually start forms mode, but if you activate the different radio buttons, you should hear a the Jaws forms-mode pop.

**Comment by terracoda** [comment]
Yesterday, the participant tabbed to the radios and then used the arrow keys to get the 3rd one, and then hit enter to activate the Show charge differences radio button. I heard the JAWS forms-mode pop at that moment, I think.

**Comment by jessegreenberg** [comment]
Oh for the radio buttons, yes that is what I am observing too.  Pressing "Enter" makes JAWS go into forms mode.  Tabbing away from them makes JAWS leave forms mode.

**Comment by terracoda** [comment]
But if you try grabbing the balloon with the Space bar after activating a Radio with Enter, JAWS seems to not exit forms mode???

**Comment by terracoda** [comment]
At least, that seemed to be our experience yesterday. The WASD keys did not work after activating the radio and the grabbing the balloon.

**Comment by jessegreenberg** [comment]
Hmm, that is not what I am seeing.  Here are my steps with nodes about how JAWS behaves for me, can you please verify I am checking the right thing?

- Tab to Radio Button group
- Arrow key to second radio button (selected with virtual cursor)
- Press "Enter" (Second radio button selected, JAWS enters forms mode)
- Shift tab to balloon (JAWS reverts to  document mode)
- Pick up balloon with spacebar (JAWS enters forms mode)
- Move balloon with WASD keys.

**Comment by terracoda** [comment]
Hmm, that's not how it appeared to work for the participant yesterday. JAWS did not seem to revert to document mode when moving to the Grab balloon button, and hitting Space to grab did not enter forms mode. However, it is hard to tell exactly what was going on because I could not see the exact key presses.

I'll have to ask her to try it again.

**Comment by jessegreenberg** [comment]
I believe it! AT are highly unpredictable. Thanks.

**Comment by jessegreenberg** [comment]
This could be a user setting issue, in JAWS you can decide how/when it enters forms mode.

> This feature determines if JAWS will automatically switch between Forms Mode and Virtual mode when working in Applications such as IE, Firefox, Help,
Acrobat, etc. When set to Auto, you will be able to navigate to controls with the ARROW keys where input is needed and JAWS will automatically switch to Forms Mode.
If you continue to arrow past the control, Forms mode will be disabled again automatically. It will make interacting with Forms much more transparent. 
When Forms Mode is set to Manual, it will remain off and you will be forced to manually go in and out of Forms Mode with the ENTER key and PC Cursor key.
When set to Semi-auto, JAWS will automatically enter Forms Mode when tabbing, but you will need to manually exit Forms Mode with the PC Cursor key.
The default setting is Auto.

Iam curious if user had a setting other than "auto". If anything other than "auto" is selected, I would not expect space key to behave as expected when picking up the balloon.

**Comment by terracoda** [comment]
@jessegreenberg, I will check with the user where their typical setting is.

**Comment by jessegreenberg** [comment]
@terracoda is this still a question and are we still waiting for feedback?

**Comment by terracoda** [comment]
@jessegreenberg, I will check again with screen reader consultant.

**Comment by terracoda** [comment]
@jessegreenberg, if I do not hear back, we can watch for issues in RC testing.

**Comment by terracoda** [comment]
@jessegreenberg, consultant generally uses "Automatic".

> I tend to use automatic. Sometimes it gets annoying though and I set it to manual. Usually it is on automatic though.

I am asking some follow-up questions and will report more here asap.

**Comment by terracoda** [comment]
@jessegreenberg, I haven't heard back, so I think I will close this issue and see if the problem resurfaces at some point.
