### ISSUE TITLE
Remove Grabbed balloon hint after successful interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#312]
Screen reader consultant confirmed my idea that removing the long _Grabbed balloon hint_ after successful interaction would be a good thing.

"Once I know how to move the balloon, I don't need that information anymore."

Truncating the Grab Alert in this way also fits with the way we provide visual interaction cues.

Please make it so the _Grabbed balloon hint_ is there on the first grab, and on the first grab after a partial or full reset.

I have made a note in the design documentation.

**Comment by jessegreenberg** [comment]
Sounds good,  applied in the above commit @terracoda.

**Comment by terracoda** [comment]
@jessegreenberg, thanks for re-opening. I noticed this too :-)

**Comment by jessegreenberg** [comment]
This has been fixed. Closing.
