### ISSUE TITLE
Neutral balloon moves towards sweater when released over charged balloon on sweater

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#315]
This is likely an unintentional side effect of https://github.com/phetsims/balloons-and-static-electricity/issues/279. We were trying to visually place the balloons side by side when releasing one on sweater when the balloon that is being released is visually right in front of the un-grabbed balloon.

Should a neutral balloon ever move at all upon release? 

Grabbed neutral balloon before release
<img width="734" alt="screen shot 2017-10-05 at 12 20 55" src="https://user-images.githubusercontent.com/1902116/31233655-b29c8dbe-a9c7-11e7-89cd-d41fb81525bd.png">

Grabbed neutral balloon after release
<img width="731" alt="screen shot 2017-10-05 at 12 23 36" src="https://user-images.githubusercontent.com/1902116/31233874-1cdd256c-a9c8-11e7-9056-2fee45062a0a.png">

**Comment by jessegreenberg** [comment]
That is correct @terracoda, this is the behavior that we introduced in https://github.com/phetsims/balloons-and-static-electricity/issues/279 to address occlusion issues, and this movement was not indicative of charge. I think changing the behavior for neutral balloons would negate the reasons we decided to shift the balloon in that issue. @arouinfar @ariel-phet do you think this is an issue?

**Comment by jessegreenberg** [comment]
> This is likely an unintentional side effect of #279.

I don't really see this as an unintentional side effect, just the behavior that was decided in #279.

**Comment by terracoda** [comment]
@jessegreenberg, my concern is that there is visual movement now for an uncharged balloon. That seems like an incorrect representation of the science.

Would it be difficult to limit the movement to balloons with charge that actually attract to the sweater based on the model?

**Comment by ariel-phet** [comment]
@terracoda @jessegreenberg this is a good point for the neutral balloon.

It seems we should remove the "slight bumping" to the side of the balloon when overlapped. Even if you perfectly overlap the balloons, and want to move the bottom one, you can easily move the top one a bit first, so it is not a major impediment to normal use of the sim.

**Comment by arouinfar** [comment]
Just to add -- I think that bumping a neutral balloon has the potential to be pedagogically  problematic, as it could be interpreted that the neutral balloon was somehow repelled from the other balloon or attracted to the sweater.

**Comment by jessegreenberg** [comment]
Ok, I will revert the changes made for #279.

**Comment by terracoda** [comment]
Thanks, @jessegreenberg.

**Comment by jessegreenberg** [comment]
Changes related to #279 have been reverted, closing.
