### ISSUE TITLE
Reconsider aria-role="switch" for two-balloon experiments

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#317]
In recent screen reader session, VO user commented that that state and type of the control was not clear.

Note from session:
> The button to add the green balloon seemed weird, not a button, but a switch and it doesn’t have a clear checked state.

User agreed that 2 radio buttons would be very verbose and suggested we use a plain checkbox, or a button with a changing label. These are both good options. Wording of the label is most crucial.

**Comment by jessegreenberg** [comment]
> User agreed that 2 radio buttons would be very verbose 

@terracoda could you please elaborate on why radio buttons are too verbose?

**Comment by terracoda** [comment]
@jessegreenberg, what do you think of representing the two-balloon interaction as a plain checkbox, rather than a toggle or a switch?

It might sound something like this when using a screen reader:
- "Two-balloon experiment, checkbox not checked" and when checked
- "Two-balloon experiment, checkbox checked" 

Visually, there is no checkbox, but in the unchecked state the single balloon picture is active and the in the checked state the two balloon picture is active. 

The focus highlight would still go around both pictures as it is one control.

I'm not sure if we are using a label and an input element in the PDOM or if we are using an aria-label attribute on the input element. Both should work the same, but they might not sound the same in screen readers.

Could you paste the rendered PDOM snippet for the two-balloon switch here for me please?

**Comment by terracoda** [comment]
It's only two options, so having two inputs each with a label adds verbosity, when a checkbox or switch can communicate the same information with one input and one label.

**Comment by terracoda** [comment]
I know the team thinks of these things as a scene switch, but it is such a simple scene switch that I think that the most simple representation possible in the code makes the interaction quicker.

**Comment by terracoda** [comment]
I think the coils in Faraday's Law would be similar, and there are probably many other "simple scene switch" examples that might represented better as a single element rather than two radios.

A larger number of scene switch options is definitely a group of radios. It is just these groups of 2 that may be better represented as a checkbox.

**Comment by jessegreenberg** [comment]
@terracoda I think that my concerns about having something that looks like PhET radio buttons and acts like a switch are better documented in #213. But for this issue, I think a checkbox sounds like a nice idea, and it will work much  better with JAWS.

Here is the html now:
```html
<div tabindex="-1" id="container-62-125-359-435-426-409">
<button id="62-125-359-435-426-409" tabindex="0" aria-pressed="false">Two-Balloon Experiments</button><p tabindex="-1" id="description-62-125-359-435-426-409">Play with two balloons or just one.</p>
</div>
```

**Comment by jessegreenberg** [comment]
@terracoda do you think it should be something like this?

```html
<div tabindex="-1" id="container-62-125-359-435-426-409">
<input type="checkbox" id="62-125-359-435-426-409" tabindex="0">Two-Balloon Experiments</button>
<p tabindex="-1" id="description-62-125-359-435-426-409">Play with two balloons or just one.</p>
</div>
```

that will be a very simple change.

**Comment by terracoda** [comment]
I agree that we had a good discussion in #213.

Interesting @jessegreenberg, I thought we had already changed over to a `input type="checkbox"` with `role="switch"`. Perhaps we refrained from doing that because it was a change to a checkbox from a button - oh my!

I think you can only use the switch role with a checkbox.

**Comment by jessegreenberg** [comment]
@terracoda we decided not to use ```role=switch``` because we found that role=switch is really broken with  JAWS (it totally skips the element and doesn't gracefully fall back to anything).

**Comment by terracoda** [comment]
Thanks for the reminder.

**Comment by terracoda** [comment]
Happy to try a plain checkbox ;)

**Comment by jessegreenberg** [comment]
Alright, sounds good!

**Comment by jessegreenberg** [comment]
@terracoda here is the new html, look OK?

```html
<div tabindex="-1" id="container-64-125-359-435-426-409">
    <input id="64-125-359-435-426-409" tabindex="0" type="checkbox" style="width: 1px;">
    <label tabindex="-1" id="label-64-125-359-435-426-409" for="64-125-359-435-426-409">Two-Balloon Experiment</label>
    <p tabindex="-1" id="description-64-125-359-435-426-409">Play with two balloons or just one.</p>
</div>
```

One downside with the checkbox is that 'enter' doesn't activate this element.

**Comment by terracoda** [comment]
> One downside with the checkbox is that 'enter' doesn't activate this element.
And it doesn't look like a checkbox! Much like the balloon doesn't look like a button.

We giveth with on hand and taketh with the other.

**Comment by terracoda** [comment]
@jessegreenberg, we'll try this and see if it sounds ok. Shall I mark it pending testing?

**Comment by terracoda** [comment]
@jessegreenberg, I am happy with the way the checkbox sounds Voice Over. One issue for sighted users it the design looks more like a button than a checkbox. Only the space key will work to activate it. We will have to see how visual keyboard users respond.

**Comment by terracoda** [comment]
@jessegreenberg, I am going to close this issue.

**Comment by jessegreenberg** [comment]
Great thanks @terracoda!
