### ISSUE TITLE
Lost whitespace in keyboard dialog

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#319]
@jessegreenberg  and @zepumph, I think changes in Scenery be for the presentation of dialogs, are affecting other dialogs see https://github.com/phetsims/friction/issues/45, ? For example, BASE was fine in the last Dev version, but I just noticed it has lost a large amount of white space in the built version. I am just checking the built version for the first time.

Perhaps the solution in BASE's Dev version can be used in Scenery for other sims?

**Built version:**
<img width="289" alt="screen shot 2017-10-20 at 09 10 42" src="https://user-images.githubusercontent.com/1902116/31819288-98a8c0a2-b576-11e7-99c6-dd54eb985f30.png">

<img width="317" alt="screen shot 2017-10-20 at 09 10 49" src="https://user-images.githubusercontent.com/1902116/31819293-9dc970ea-b576-11e7-80c7-a8c900214369.png">

**Dev version:**
<img width="285" alt="screen shot 2017-10-20 at 09 13 45" src="https://user-images.githubusercontent.com/1902116/31819402-0e055824-b577-11e7-82c1-66a6d08f61f9.png">

<img width="328" alt="screen shot 2017-10-20 at 09 14 01" src="https://user-images.githubusercontent.com/1902116/31819408-1058cdc2-b577-11e7-8b5b-8e638a9cb92d.png">

**Comment by zepumph** [comment]
It looks like @jessegreenberg offered to take a look.

**Comment by jessegreenberg** [comment]
The letter keys are using TextKeyNode now. Once https://github.com/phetsims/scenery-phet/issues/343 we will come back  to this issue.

**Comment by zepumph** [comment]
I'll take this one on as soon as I finish general consistency within keys.

**Comment by jessegreenberg** [comment]
Thanks @zepumph!

**Comment by zepumph** [comment]
Don't mind the reverted commit :/ 

I just did a few minor adjustments, in general it looks good. @jessegreenberg back to you.

**Comment by jessegreenberg** [comment]
Thanks for doing this @zepumph, looks great. The mockup for these keys had them larger than the ones in the dialog so I made them a bit bigger using the options you added to KeyNode. Closing.
