### ISSUE TITLE
Add "interactive sim" content to Scene Summary

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#333]
Update Scene Summary to include the cue that tells the user that the sim is interactive and that descriptions will change as they play.

**Specifically from design document:**
> This is an interactive sim. Descriptions change as you play with it. It has a Play Area and a Control Panel. The Play Area is a small room. The Control Panel has buttons and a checkbox to change conditions in the room.

**Comment by terracoda** [comment]
@jessegreenberg, I tried to make this update myself, but I don't think I am pulling the right stuff from GitHub.

Could you please update the introductory static sentences to the Scene Summary?

**Comment by jessegreenberg** [comment]
Sure, done in the above commit, here it is in the a11y-view. Reassigning back to you @terracoda.
![capture](https://user-images.githubusercontent.com/6396244/33140825-63548492-cf6e-11e7-95a5-746d1a017075.PNG)

**Comment by terracoda** [comment]
Awesome, thanks. Closing this issue.
