### ISSUE TITLE
Alert corrections for moving balloon around

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#334]
Testing on Mac High Sierra,  Safari 11 and VO

While moving the balloon around, I noticed the following related issues:
**Moving and Jumping Balloon Around**
- [x] Jump to wall alert (show all charge): extra periods at end of sentences. "At wall..Negative charges in wall move away from Yellow Balloon a little bit.."
- [x] Hear "Near Near right edge.l" when wall is removed and moving past Near right edge location.
- [x] Hear no locations when moving along right edge with wall removed. 
- [x] Also, do not hear vertical dragging alerts in some vertical column locations (e.g. Near sweater column, Near Wall column). Is this intentional, or just incomplete? If you need walk throughs for these columns, I can provide them.

**Comment by jessegreenberg** [comment]
When we are in a landmark location, we aren't getting any location alerts.

**Comment by jessegreenberg** [comment]
The above commits fix this, thanks for finding @terracoda.
