### ISSUE TITLE
Release alert at wall has inconsistant description of charge deflection

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#340]
On grab and rubbing, deflection is described as being "a little bit", but on a release that begins with moving down the wall and ends at bottom right corner, the deflection is described as "In lower wall, no change in charges."

Here are two screen shots with the same amount of charge on the Green Balloon.
On Grabbed we have "a little bit" of deflection
<img width="946" alt="base-grabbed-a-little-deflection" src="https://user-images.githubusercontent.com/1902116/33948764-5385bbb8-e002-11e7-8d53-53ceee3f3a6c.png">

On release we have "In lower wall, no change in charges." I think this incorrect induced charge description only happens at end of the Release Movement 4 pattern.
<img width="857" alt="base-deflection-no-change-in-charges" src="https://user-images.githubusercontent.com/1902116/33949018-e879c07a-e002-11e7-813f-75ca16b68941.png">

@jessegreenberg, you might still be working on these.

**Comment by terracoda** [comment]
@jessegreenberg, please note that I have have an issue https://github.com/phetsims/balloons-and-static-electricity/issues/332 assigned to myself to clarify the documentation which I have not yet marked as completed.

If you have any questions, please do not hesitate to ask.

The deflection issue above seems to be something to do with the model and not the design documents, but I just wanted to mention issue #332 just in case.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, fixed in above commit. Now alert is something like

> Yellow Balloon, at lower wall. Negative charges in lower wall move away from Yellow Balloon a lot.

Closing.
