### ISSUE TITLE
Induced charge description spoken when there is no wall is present

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#342]
The induced charge portion of the descriptions needs to be suppressed (turned off) in all cases when there is no wall present. I found the following examples:

Grab Alert when there is no wall
<img width="1041" alt="base-grab-alert-get-induced-no-wall" src="https://user-images.githubusercontent.com/1902116/34111949-bbccda62-e3e5-11e7-8f31-9ec67ab155f9.png">

Jump to alert when there is not wall:
<img width="980" alt="base-jump-to-alert-no-wall" src="https://user-images.githubusercontent.com/1902116/34112071-0519ee94-e3e6-11e7-9d91-e99d6b477c0b.png">

Dragging when there is no wall
<img width="980" alt="base-dragging-when-no-wall" src="https://user-images.githubusercontent.com/1902116/34112135-3471afc4-e3e6-11e7-8265-7b3bebe4041d.png">

Dragging along right edge when there is no wall
<img width="980" alt="base-dragging-when-no-wall" src="https://user-images.githubusercontent.com/1902116/34112212-7357a784-e3e6-11e7-978d-b6ef4cb6a6a2.png">

**Comment by jessegreenberg** [comment]
Thanks @terracoda, fixed in the above commits.
