### ISSUE TITLE
Unintended "no change in charges" firing during rubbing on sweater.

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#347]
Things @terracoda Dev version 9 Mac OS Safari:
-  [ ] When rubbing on sweater - Extra unintended alert interrupting rubbing: "In upper arm, no change in charges." It might be related to confusion in the model about induced charge. The unintended alert only happens when there are two balloons in Play Area.

**Comment by terracoda** [comment]
I noticed this right after you fixed induced charge in the model.

**Comment by jessegreenberg** [comment]
@terracoda this was fixed, the induced charge is always described at the walls location now. It sometimes used to use the balloons location (for some reason...). Closing.
