### ISSUE TITLE
Need simple induced charge description when release starts and ends at wall

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#348]
Dec version 9. Mac OS Safari and Voice Over.

During my latest testing I noticed that that the **[+ Induced charge (simple)]** pattern has been implemented to the end of releases that end at the wall after some movement. And sounds great!

However, for releases that start and end at the wall resulting in  no movement, the user does not get the induced charge description at the end.

Originally, there was no induced charge at all in any releases, but since they have been added to regular releases that end at the wall, I think it is ok to add this same description for releases that start and end at the wall and result in no movement.

I updated the design document so the documentation on [+ Induced charge (simple)] is more clear as well.

**Comment by jessegreenberg** [comment]
Done in the above commit @terracoda, here is an example:
> Yellow Balloon, no change in position. Yellow Balloon, at lower wall. Negative charges in lower wall move away from Yellow Balloon a lot.

Closing this issue.

**Comment by terracoda** [comment]
Thanks @jessegreenberg. It sounds great.
