### ISSUE TITLE
Labels for balloon movement in two-balloon scenarios

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#349]
Currently, it is a little difficult to figure which balloon path is being described in releases and independent movement during two-balloon scenarios.

To address this design problem we will try peppering in two more labels into the existing alert system.

If possible, these two extra labels should just be added when there are two balloons added to the play area. I have updated Section 4 Interactive Release Alerts and Section 5 Independent Balloon Movement in the Grid design document here:
https://docs.google.com/document/d/1dfsa6JApPPAOuF757Ag_qQ0-pAy4-eA1tB_aoD1GIhE/edit#heading=h.4xn2gqwfg1t

I cleaned up the design documentation removing Option A. I hope everything is clear. Please let me know if you have any questions.

And again, if it is really difficult to add the extra labels only in two-balloon scenarios, we can go with the extra labels in both scenarios and see what the impact is.

**Comment by jessegreenberg** [comment]
@terracoda labels in two  balloon scenarios were added. It was not much extra work to only have the labels when both balloons were visible. Closing this issue!
