### ISSUE TITLE
branch: accessibility-mixin

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#352]
Identified by `print-branches.sh`. Please describe.

FYI, all non-release branches are supposed to have an associated GitHub issue. Title is of the form "branch: {{branchName}}}". The description should include: the purpose of the branch, expected lifetime of the branch, references to any related issues.

**Comment by jessegreenberg** [comment]
This branch was stale, I deleted it. Thanks @pixelzoom.

**Comment by jessegreenberg** [comment]
Needs to be re-deleted for https://github.com/phetsims/special-ops/issues/198
