### ISSUE TITLE
branch: drag-no-keyup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#355]
Identified by `print-branches.sh`. Please describe.

FYI, all non-release branches are supposed to have an associated GitHub issue. Title is of the form "branch: {{branchName}}}". The description should include: the purpose of the branch, expected lifetime of the branch, references to any related issues.

**Comment by jessegreenberg** [comment]
Thanks @pixelzoom this branch is quite stale and can be pruned.

**Comment by jessegreenberg** [comment]
Deleted.

**Comment by jessegreenberg** [comment]
Has been re-deleted for https://github.com/phetsims/special-ops/issues/198
