### ISSUE TITLE
User suggestion: polarization of molecules in wall

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#359]
> In the simulation Ballons & static electricity I would suggest that the molecules in the wall really experience polarization (reorganization of the orientation of the molecules) rather than induction - at the moment the electrons leave "their" protons if the charged balloon comes near. In my opinion this is not helpful to establish an understanding of the difference between a conductor and an isolator. Therfore, I think I won't be able to use the simulation.

**Comment by terracoda** [comment]
There is no mention of "induced charge" in the descriptions, only movement. It is possible a visual change (if needed) will not affect description design.

@oliver-phet, does this issue need to be assigned to a content expert?

**Comment by jessegreenberg** [comment]
Discussed with @ariel-phet @terracoda @emily-phet:

This change would be beyond the scope of this simulation. We understand and the feedback is correct,  but this sim is meant for a much younger audience to get a basic understanding. @oliver-phet can you please notify the user of this?

**Comment by oliver-phet** [comment]
Done. Closing.
