### ISSUE TITLE
Punctuation: Wall description in PDOM has extra period

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#361]
Need to remove extra period.
![screen shot 2018-02-27 at 12 30 34](https://user-images.githubusercontent.com/1902116/36739255-0c4105fc-1bba-11e8-96fb-fcd0ac76b9a5.png)

**Comment by jessegreenberg** [comment]
This was fixed with #362, and the  "Positive charges do not move" portion was removed entirely for this case, as requested in #362. Closing.
