### ISSUE TITLE
Incorrect starting description of Wall

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#362]
While testing dev version 13, I noticed an extra phrase on the Wall's description.

https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.13/phet/balloons-and-static-electricity_en_phet.html?accessibility

Wall 

> At right edge of Play Area. Has zero net charge, many pairs of negative and positive charges. Positive charges do not move.

The last string/phrase, _Positive charges do not move._ is only relevant when there is a positive induced charge effect. This string/phrase should not be included as part of the wall's general description. It is added along with other strings when  a negatively charged balloon is against the wall.

**Comment by terracoda** [comment]
@jessegreenberg, let me know if yo have any questions.

**Comment by jessegreenberg** [comment]
@terracoda thanks for reporting. I believe this might have been transient, it is not showing up in latest version. Here is what I see in the a11y view.
![capture](https://user-images.githubusercontent.com/6396244/37375767-d153904e-26e6-11e8-8270-adab5dabe024.PNG)

**Comment by jessegreenberg** [comment]
It is there with  induced charge (although with an extra period)

![capture](https://user-images.githubusercontent.com/6396244/37375797-f8147428-26e6-11e8-9544-d0016008595e.PNG)

**Comment by jessegreenberg** [comment]
Removed the extra period in the above commit, closing.
