### ISSUE TITLE
Rubbing on sweater and picking up charges (Alerts 3B-1 and 3B-2 series)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#368]
Rubbing/Dragging/Moving Alerts
3B-1 series. Rubbing on sweater (Picking up charges) tested
3B-2 series. Rubbing on sweater (Not Picking up charges) tested

March 12, 2018
March 12th, testing BASE from PhET Test
Voice Over and Safari (11.03) on Mac OS 10.13.3

There are 3 descriptions in each series.

**In first series,**
only the first alert (3B-1-1) has location information "On Sweater".
With _Show all charges_ and _Show charges differences_
- [x] I'm not hearing the next-to phrase yet for 3B-1-1 in the rare case that the grabbed balloon arrives on sweater, overlaps the un-grabbed balloon and picks up negative charges at the same time.
- @jessegreenberg, if this is difficult, let's discuss, because it may not be crucial. I often hear the proximity shortly after rub B-1-1.

**_Show no charges_**
- [x] I'm not hearing the next-to phrase yet for 3B-1-1, but hear it 1 or 2 moves later. For example, I hear, "Near sweater. On sweater. (On right arm of sweater.) On right arm of sweater, next to yellow balloon." 
- again, may not be crucial, so if difficult to implement, let's discuss.

**In second series,**
the first and last alerts have location information, and the next-to phrases are implemented and working nicely in all charge views.

**Comment by jessegreenberg** [comment]
> 'm not hearing the next-to phrase yet for 3B-1-1 in the rare case that the grabbed balloon arrives on sweater, overlaps the un-grabbed balloon and picks up negative charges at the same time.

To fix this, I increased  the threshold for when "next to {{other balloon}}" gets triggered. I believe things still sound OK, but if you notice problems please let me know @terracoda. Otherwise we will need a new strategy for this because generally when the balloon left edge hits the sweater right edge, it is not close enough to other balloon to trigger this.

**Comment by jessegreenberg** [comment]
Closing this issue since it has been included.
