### ISSUE TITLE
Wall's dynamic description not quite right (more than punctuation)

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#372]
Testing Date: March 27, 2018
Dev Version: [1.4.0-dev.13](https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.13/phet/balloons-and-static-electricity_a11y_view.html)
Environment: Ally View in Firefox, Mac OS, no screen reader.

While testing the Scene Summary in #371, I noticed some issues with the wall's dynamic description that are a bit more than just issues with punctuation. 

I realize that some issues related to combined induced might not yet be fully implemented.

The [BASE: Charge Views design doc](https://docs.google.com/document/d/1EOeMXgu0Cvqu1lh9WgFp_21enK8Xdy5EI_H1l6tBsvA/edit#heading=h.1cpvo7fy0907) should provide up-to-date guidance

- [x] **Show all charges - page load**
  - extra period and extra phrase: 
"At right edge of Play Area. Has zero net charge, many pairs of positive and negative charges. Positive charges do not move.."
    - Should be: "At right edge of Play Area. Has zero net charge, many pairs of positive and negative charges."
    - Note that the phrase, "Positive charges do not move." is only needed when a balloon is actually at the wall. No charges are moving if there is not balloon at the wall.

- [x] **Show all charges - balloon at wall**
  - 2 extra periods. Description is perfect.
"At right edge of Play Area. Has zero net charge, many pairs of positive and negative charges. Negative charges in wall move away from Yellow Balloon a little bit.. Positive charges do not move.."

I will be adding to this issue.

**Comment by jessegreenberg** [comment]
@terracoda just FYI dev.13 is 25 days old and may be very stale, it may not be worthwhile to test that version.

**Comment by jessegreenberg** [comment]
On page load, here is the description for the wall in master:
![capture](https://user-images.githubusercontent.com/6396244/38042817-9a80dda0-3272-11e8-82fe-6aa072134f34.PNG)

In master,  there  is  one extra period at the end of the wall description with induced charge
![capture](https://user-images.githubusercontent.com/6396244/38042897-ce753ffc-3272-11e8-884c-ff090b9cdf42.PNG)

**Comment by terracoda** [comment]
Ok, sounds good. I will wait for latest working version.

**Comment by jessegreenberg** [comment]
Alright, list in original issue has been fixed. Reassigning to @terracoda  to close or add to issue.

**Comment by terracoda** [comment]
@jessegreenberg, I am closing this issue. The two issues noted above are fixed.
