### ISSUE TITLE
A11y View is not updating and not loading

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#375]
This issue is likely related to changes made in #373.

The A11y View for [1.4.0-dev.13](https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.13/phet/balloons-and-static-electricity_a11y_view.html) was working fine yesterday, and today the PDOM content is not updating. The alerts seem to be working, though.

In a later version, [1.4.0-dev.15](https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.15/phet/balloons-and-static-electricity_a11y_view.html), the PDOM content and the alerts do load at all.

**Comment by jessegreenberg** [comment]
I accidentally had working copy changes in dev.15 that broke things. New version has been deployed. Sorry @terracoda!

**Comment by terracoda** [comment]
Thanks @jessegreenberg! You are awesome!
