### ISSUE TITLE
Scene summary item for sweater/wall charge not correct

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#376]
@terracoda the design document says:
> “{{Sweater and Wall}} have {{many}} {{pairs of negative and positive charges}}.”

Currently master has this description:
> Sweater and wall have zero net charge, many pairs of negative and positive charges.

I am going to change it to the one in the design document, I assume that is latest design.

**Comment by jessegreenberg** [comment]
But then later in the document the example for page load shows this.
>Sweater {{and wall}} have {{zero}} net charge, {{each}} has {{many}} {{pairs of negative and positive charges}}.

@terracoda which is correct? Can we skip the "each has" in this description?

**Comment by jessegreenberg** [comment]
I am going to go ahead and make it match the examples in the table.

**Comment by terracoda** [comment]
@jessegreenberg, I'll look into this, too.

**Comment by terracoda** [comment]
@jessegreenberg, again, sorry for the inconsistency, the added "each" when the sweater and wall both have zero net charge does emphasize that they separately both have "many pairs of positive and negative charges".

The examples in the tables are preferred, but if that is tricky to implement we can use the simpler phasing:
- “{{Sweater and Wall}} have {{zero}} net charge, {{many}} {{pairs of negative and positive charges}}.”

Thanks again for noticing the inconsistencies. I updated the examples outside the tables to include "each".

**Comment by jessegreenberg** [comment]
Sounds good @terracoda, I made it match the design doc. Here are 'diff' and 'all' charge view descriptions, respectively.

![capture](https://user-images.githubusercontent.com/6396244/38218224-43b59f5e-368e-11e8-9a1a-88347b231ab9.PNG)
![capture2](https://user-images.githubusercontent.com/6396244/38218262-5e501f9c-368e-11e8-9a29-0395d1deffa9.PNG)

Closing.
