### ISSUE TITLE
Add "from sweater" to rub #1-1 pattern in charge differences view?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#380]
@terracoda I noticed that the first time balloon picks up charges after hitting sweater in charge differences view looks like this:

> On sweater.
[[Yellow ]] balloon picks up negative charges. [[Same increase]] of positive charges showing on sweater.

For consistency with 'all' view and to avoid a special case can we include "from sweater" to the pick up phrase?
> On sweater.
>[[Yellow ]] balloon picks up negative charges from sweater. [[Same increase]] of positive charges showing on sweater.

**Comment by terracoda** [comment]
@jessegreenberg, well spotted. I think your suggestion will work fine.

**Comment by jessegreenberg** [comment]
Thanks @terracoda sounds good. This is how it is in master so this can be closed.
