### ISSUE TITLE
Grab alert in Show charge differences, missing net charge description.

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#382]
While testing dragging alerts in single-balloon scenarios in [dev version 18](https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.18/phet/balloons-and-static-electricity_en_phet.html?accessibility)

I noticed that the Grab Alert in **Show charge differences** is missing the balloon oject's negative net charge description.

<img width="616" alt="screen shot 2018-04-02 at 18 20 35" src="https://user-images.githubusercontent.com/1902116/38215714-462834b2-36a3-11e8-8ee2-3c755e5ba091.png">

In Show charge differences, the grab alert should be:
"Grabbed. {{At center}} {{of Play Area}}. Has {{zero}} net charge, {{showing no charges}}. [+ Grabbed balloon hint.]"

Still need to do more testing of dragging, but that's all I found thus far.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, this is fixed in master.
![capture](https://user-images.githubusercontent.com/6396244/38217918-3ea0fd0c-368d-11e8-8427-eef498d66bd2.PNG)


Closing.
