### ISSUE TITLE
Add ESC key as a release mechanism for the balloon?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#387]
Design Considerations from recent interviews

@jessegreenberg, in a recent interview with a JAWS user, the participant tried to use the ESC key several times (repeatedly) to release the balloon. The participant's reason, "The ESC key is a common way to exit forms mode."

**Question for BASE:**
1. What do you think about adding the ESC key as a release mechanism for the Balloon in BASE?

**Question in General:**
2. Do you think this has more general implications, for example, should this be a general thing we do for exiting forms mode. Or more specifically, a general thing we do for custom interactions that use the application role?

I'll mark this as an a11y-design meeting question, and if more appropriate I can move this issue to the a11y-research repo.

**Comment by jessegreenberg** [comment]
Seems like it could be useful @terracoda. I think the only thing to investigate is if AT make this possible. If they exit forms mode with "escape" key, they may or may not send information to the browser that  "escape" key was pressed.

@terracoda was the user able to hear "Press space to release" cue?

**Comment by terracoda** [comment]
@jessegreenberg, as discussed in a11y meeting, I think the user did hear the cues, but was just used to using the ESC key to exit forms mode.

**Comment by jessegreenberg** [comment]
@terracoda I added escape key as a way to release the balloon - I tested on JAWS and NVDA on Firefox  and VoiceOver on Safari, it is working nicely on all of those platforms.

Closing.
