### ISSUE TITLE
Consider small change to scene summary's static paragraph

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#395]
In recent sim designs we start off the Scene Summary with a slightly more generic sentence:

“This is an interactive sim. It changes as you play with it. ..."

In BASE, we have, "This is an interactive sim. Descriptions change as you play with it. ..." (see screenshot below).

@emily-phet, I like the more generic approach as it does not specifically mention a mode (i.e., descriptions). Do you agree? 

<img width="811" alt="screen shot 2018-04-11 at 15 21 17" src="https://user-images.githubusercontent.com/1902116/38634068-0e748462-3d9c-11e8-9f4c-9501b821ce9f.png">

**Comment by jessegreenberg** [comment]
@terracoda I agree that this sim should use the generic description that was designed for all sims. Ill go ahead and make the change, but @emily-phet please let us know if there are concerns.

**Comment by jessegreenberg** [comment]
With the above commit, the opening paragraph looks like ![capture](https://user-images.githubusercontent.com/6396244/38639382-31663776-3d8e-11e8-85ed-f09ef6b45f21.PNG)

@terracoda anything else to do for this issue?

**Comment by terracoda** [comment]
You are awesome :-)
I am unassigning @emily-phet. I think this is good! Closing issue.
