### ISSUE TITLE
keyboard navigation focus from Reset All spilling into navigation bar

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#403]
![screen shot 2018-05-14 at 4 40 24 pm](https://user-images.githubusercontent.com/31285590/40081045-1db5fa96-584a-11e8-81c9-28bc5d7d976c.png)

For phetsims/QA/issues/112. Should we change this? @jessegreenberg and I weren't sure whether this warranted an issue, but as per @ariel-phet's advice, I'm erring on the side of more issues.

**Comment by jessegreenberg** [comment]
A couple of options, all of which would likely take 0-10 minutes:
 - Do nothing, it isn't a big deal.
 - Make the focus highlight smaller so it doesn't overlap the nav bar.
 - Shift the control panel up just a bit so the default highlight dilation for the button can still be used.

**Comment by terracoda** [comment]
Of the other two options, if we need to move it, I would vote for moving the control panel up slightly. I would not want to make the focus highlight inconsistent with other reset buttons.

**Comment by jessegreenberg** [comment]
Thanks @terracoda, Ill go ahead and close this issue, we will leave as is.
