### ISSUE TITLE
JAWS shifts keyboard navigation focus after picking up balloon

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#405]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Firefox ESR 52.8.0

<b>Problem Description</b>

For phetsims/QA/issues/112. For some reason, tabbing to the balloon, pressing space, and then pressing A will shift the keyboard navigation focus to the radio buttons for the charge settings. This only occurs when JAWS is running, and doesn't occur when I try to record it. I don't think it's luck, I've tried to record it many times and I even tried a different screen capture software, so I'm not sure what to make of that. Possibly related to #404.

<b>Steps to Reproduce</b>

1. Have JAWS running.
2. Tab to balloon.
3. Press space.
4. Press A.

<b>Visuals</b>

No visuals. See description of problem.

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.21/phet/balloons-and-static-electricity_all_phet_debug.html?accessibility
Version: 1.4.0-dev.21 2018-04-04 18:25:56 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:52.0) Gecko/20100101 Firefox/52.0
Language: en-US
Window: 1280x611
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"balloons-and-static-electricity":{"sha":"f4f3cc64","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"bc7c5d1f","branch":"master"},"dot":{"sha":"e5489d18","branch":"master"},"joist":{"sha":"2cf256a9","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"b6c2b0f5","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"de004c6e","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"4a4afee2","branch":"master"},"scenery-phet":{"sha":"e68ebc03","branch":"master"},"sherpa":{"sha":"bb14a03a","branch":"master"},"sun":{"sha":"8a187c9f","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}

</details>

**Comment by terracoda** [comment]
@lmulhall-phet, do you have forms mode set to auto? I think that is the default setting, but I am not sure?

If JAWS is not going into forms mode automatically, it is possible that only the Enter key will force it into forms mode. 

Does the balloon get grabbed if you press Enter twice then press A key, or press Enter then Space then A key?

At any point do you hear the JAWS-entered-forms-mode pop sound?

**Comment by terracoda** [comment]
Oh, and to clarify this only happens with Space key? Then maybe doubling up the interaction is not very useful?

**Comment by terracoda** [comment]
Oh, I just found this document on JAWS and forms mode:
https://www.freedomscientific.com/.../JAWS-ARIA-Support.doc

Could this section be the issue?

> Different Control Types
In terms of Forms Mode, there are two groups of controls: those that require Forms Mode to interact with them, and those controls that never require Forms Mode to interact with them.
Forms Mode is required for edit fields, combo boxes, spin controls, list controls, tab controls, menu bars, tree views, and grid cells. For these controls, press ENTER or SPACEBAR to enter Forms Mode, and ESC or NUM PAD PLUS to exit Forms Mode. 
For buttons and check boxes, use ENTER or SPACEBAR to activate the control at the location of the Virtual Cursor. Users interact with these controls simply by pressing ENTER or SPACEBAR; so forms mode is unnecessary. Auto Forms Mode causes JAWS to leave Forms Mode when it encounters these control types because they are just as usable without Forms Mode.

**Comment by terracoda** [comment]
It should matter whether one is in forms mode or not when on a button, but maybe it is here?

**Comment by terracoda** [comment]
@lmulhall-phet for comparison and understanding can you test with auto-forms mode set to off, and see how that affects the interaction?

**Comment by jessegreenberg** [comment]
It seems to me like it shouldn't matter, focus is on the div with role=application.

**Comment by terracoda** [comment]
@jessegreenberg, my understanding was that perhaps JAWS was not entering application role (aka forms mode) from the button??

**Comment by lmulhall-phet** [comment]
@terracoda @jessegreenberg I'll test forms mode to verify.

**Comment by jessegreenberg** [comment]
Perhaps, but I think @lmulhall-phet said he could use the WASD keys sometimes with JAWS. My interpretation of the section you posted is for the active element, not the previous element that had focus.

**Comment by lmulhall-phet** [comment]
I'm not experiencing this issue on FF 60.

**Comment by jessegreenberg** [comment]
Thanks @lmulhall-phet, good to know.

**Comment by lmulhall-phet** [comment]
@terracoda @jessegreenberg this happens with the enter key as well.

**Comment by lmulhall-phet** [comment]
@jessegreenberg Still occurs when I wait for the dialogue to complete.

**Comment by jessegreenberg** [comment]
@lmulhall-phet when using JAWS, have you ever heard it say "Forms mode on"?

**Comment by lmulhall-phet** [comment]
@jessegreenberg, no I haven't.

**Comment by terracoda** [comment]
@jessegreenberg and @lmulhall-phet, my understanding and experience is that JAWS makes a pop sound when it enters forms mode. I have heard this sound many times during interviews. I don't know if this pop sound is turned on through a user setting.

**Comment by terracoda** [comment]
@lmulhall-phet, just for clarification, you tab to the Grab balloon button, you hit Enter or Space keys, and in both cases you do not hear a pop, then you Press A and go to the radio buttons.

Is that correct?

**Comment by terracoda** [comment]
And at any time after hitting Enter or Space on the grab button, do you hear, "Grabbed. At center of play area..."?

**Comment by jessegreenberg** [comment]
> my understanding and experience is that JAWS makes a pop sound when it enters forms mode.

Interesting, probably a user setting then. My version definitely says "Forms mode on" and "Forms mode off" when it toggles.

**Comment by terracoda** [comment]
Makes sense why I hear the pop in interviews with screen reader users then. Seems like a good setting to change. I'd rather hear a pop than "forms mode on/off" every time I entered forms mode.

**Comment by lmulhall-phet** [comment]
@jessegreenberg I'm experiencing the keyboard navigation focus shifting phenomenon with the Reset Balloon button as well on FF 60.0.1.

**Comment by lmulhall-phet** [comment]
I'm experiencing keyboard navigation focus shifting with the following:

Balloon
- space: no
- enter: no

Remove Wall
- space: yes
- enter: yes

Balloon Checkbox
- space: yes
- enter: yes

Reset Balloon
- space: yes
- enter: yes

Charge Settings Radio Buttons
- space: no
- enter: no

Reset All
- space: yes
- enter: yes

Keyboard Shortcuts
- space: no
- enter: no

PhET Menu
- space: no
- enter: no

**Comment by jessegreenberg** [comment]
I am able to reproduce this, it is very very weird. Focus is jumping spontaneously. Sometimes I am able to successfully interact with a button, then the second time I click it focus jumps somewhere else and clicks a different button that I didn't want to click.

**Comment by jessegreenberg** [comment]
@lmulhall-phet was that comment meant for this issue or #404

**Comment by jessegreenberg** [comment]
I am not able to reproduce the original issue
> For some reason, tabbing to the balloon, pressing space, and then pressing A will shift the keyboard navigation focus to the radio buttons for the charge settings. 

in FF 60. @lmulhall-phet I think you said that as well in https://github.com/phetsims/balloons-and-static-electricity/issues/405#issuecomment-389654083.

If we proceed with supporting FF 60, can this issue be closed?

**Comment by lmulhall-phet** [comment]
> @lmulhall-phet was #405 (comment) comment meant for this issue or #404?

I agree #404 would have been a more appropriate place to post that comment.

> can this issue be closed?

@jessegreenberg I haven't been able to reproduce the original issue either, so yes.
