### ISSUE TITLE
Report a Problem, PhET Website throw assertion failed error, cannot interact with sim

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#406]
<b>Test Device</b>

MacBook Air, Hanson

<b>Operating System</b>

macOS 10.13.4, Windows 10

<b>Browser</b>

Firefox 60.0.1

<b>Problem Description</b>

For phetsims/QA/issues/112. While doing some general dev testing, I noticed that
1. Clicking the PhET Website link
-OR-
2. Clicking the Report a Problem link

throws the following error:

`Error: Assertion failed: Exit events not matched by an enter`

You cannot interact with the simulation after doing one of the two above items.

This issue is isolated to Firefox, but as noted above, it occurs on macOS and Windows.

<b>Steps to Reproduce</b>

1. Open the sim in Firefox.
2. Open console.
3. Click PhET Website link or Report a Problem link.

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.21/phet/balloons-and-static-electricity_all_phet_debug.html?accessibility
Version: 1.4.0-dev.21 2018-04-04 18:25:56 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1920x983
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"balloons-and-static-electricity":{"sha":"f4f3cc64","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"bc7c5d1f","branch":"master"},"dot":{"sha":"e5489d18","branch":"master"},"joist":{"sha":"2cf256a9","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"b6c2b0f5","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"de004c6e","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"4a4afee2","branch":"master"},"scenery-phet":{"sha":"e68ebc03","branch":"master"},"sherpa":{"sha":"bb14a03a","branch":"master"},"sun":{"sha":"8a187c9f","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}

</details>

**Comment by terracoda** [comment]
@jessegreenberg, this is out of my realm, I think. Let me know if you need my help.

**Comment by lmulhall-phet** [comment]
@jessegreenberg This does not occur when I use keyboard navigation to open either of the links.

**Comment by jessegreenberg** [comment]
I spent ~20 minutes trying to track it down but got nowhere. Happy to spend more time but @jonathanolson might isolate the problem immediately so Ill wait for a response in the above issue.

**Comment by jonathanolson** [comment]
Ok, apparently the animation frame CAN fire while waiting for the window.open.

<img src="https://media.giphy.com/media/NPyHgTkMStCXC/giphy.gif" alt="Crazy Pills"/>

Looking for the best solution (ideally a non-blocking form), but also I'll need to solve the general problem for the enter/exit counts also.

**Comment by jonathanolson** [comment]
Created the `branch-input` branch for some work on this.

**Comment by jonathanolson** [comment]
Moved to master, tests are showing this being pretty stable. The usual "could have broken some obscure input thing, or something in a different browser" applies.

@lmulhall-phet, can you confirm that this fixes the bug in master?

**Comment by lmulhall-phet** [comment]
@jonathanolson fixed in master for BASE, but I'm not sure what other sims to test...  How would I go about figuring out which sims use ButtonListener?

**Comment by jonathanolson** [comment]
It's more of a "fixed a general problem that happens to affect ButtonListener in this case".

If it's fixed in this instance (and snapshots show it's fairly unlikely I broke general behavior), I'm going to close it.
