### ISSUE TITLE
JAWS, FF 60.0.1 arrow keys do not shift keyboard navigation focus for charge settings radio buttons

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#407]
<b>Test Device</b>

Hanson

<b>Operating System</b>

Windows 10

<b>Browser</b>

Firefox 60.0.1

<b>Problem Description</b>

For phetsims/QA/issues/112. If you tab to the radio buttons for the charge settings, using the arrow keys will not shift the keyboard navigation focus. However, JAWS does have the correct readout, e.g. if I'm on the "Show all charges" radio button and press the down arrow key, it will do the readout for "Show no charges."

<b>Steps to Reproduce</b>

1. Open BASE in FF 60.0.1.
2. Tab to "Show all charges."
3. Try to use the arrow keys to shift the keyboard navigation focus.

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.21/phet/balloons-and-static-electricity_all_phet_debug.html?accessibility
Version: 1.4.0-dev.21 2018-04-04 18:25:56 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1280x606
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"balloons-and-static-electricity":{"sha":"f4f3cc64","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"bc7c5d1f","branch":"master"},"dot":{"sha":"e5489d18","branch":"master"},"joist":{"sha":"2cf256a9","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"b6c2b0f5","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"de004c6e","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"4a4afee2","branch":"master"},"scenery-phet":{"sha":"e68ebc03","branch":"master"},"sherpa":{"sha":"bb14a03a","branch":"master"},"sun":{"sha":"8a187c9f","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}

</details>

**Comment by jessegreenberg** [comment]
Thanks for making an issue @lmulhall-phet but this is actually the expected behavior. It was a surprise to us too and we ended up submitting a bug report to VFO about it (https://github.com/phetsims/a11y-research/issues/54).

> However, JAWS does have the correct readout, e.g. if I'm on the "Show all charges" radio button and press the down arrow key, it will do the readout for "Show no charges."

If you then press "enter", the "Show no charges" radio button will  be selected.

@lmulhall-phet @terracoda should this quirk be documented somewhere in the design patterns doc or somewhere in QA resources?

**Comment by terracoda** [comment]
@jessegreenberg, that might be a good idea.

**Comment by lmulhall-phet** [comment]
Huh, that's some weird behavior. Thanks @jessegreenberg. I can document this for QA. Closing.

**Comment by lmulhall-phet** [comment]
@jessegreenberg, QA is done.
