### ISSUE TITLE
incorrect behavior with iOS Safari touch actions/scrolling

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/balloons-and-static-electricity#408]
<b>Test Device</b>

iPad Pro

<b>Operating System</b>

iOS 11.3.1

<b>Browser</b>

Safari

<b>Problem Description</b>

For phetsims/QA/issues/112. I'm experiencing the touch actions/scrolling behavior @jonathanolson documented in phetsims/scenery/issues/770, i.e. when I try to move the balloon around, the screen will move up and down with the balloon. Wondering if this should be fixed for this dev version (1.4.0-dev.24).

<b>Steps to Reproduce</b>

1. Open BASE in Safari.
2. Try to move the balloon around.

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Balloons and Static Electricity‬
URL: https://bayes.colorado.edu/dev/html/balloons-and-static-electricity/1.4.0-dev.21/phet/balloons-and-static-electricity_all_phet_debug.html?accessibility
Version: 1.4.0-dev.21 2018-04-04 18:25:56 UTC
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Mobile/15E148 Safari/604.1
Language: en-US
Window: 980x1209
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Metal - 52.3.2)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.00)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 8 uniform: 128
Texture: size: 4096 imageUnits: 8 (vertex: 8, combined: 8)
Max viewport: 4096x4096
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"balloons-and-static-electricity":{"sha":"f4f3cc64","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"bc7c5d1f","branch":"master"},"dot":{"sha":"e5489d18","branch":"master"},"joist":{"sha":"2cf256a9","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"b6c2b0f5","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"de004c6e","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"4a4afee2","branch":"master"},"scenery-phet":{"sha":"e68ebc03","branch":"master"},"sherpa":{"sha":"bb14a03a","branch":"master"},"sun":{"sha":"8a187c9f","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}

</details>

**Comment by jessegreenberg** [comment]
Thanks for checking, it looks like patches were added for that bug 20 days ago and 1.4.0-dev.24 is older than that so I *would* expect the bug to show up in this test. @lmulhall-phet I assume it isn't showing up in master so this issue can be closed, but let us know.

**Comment by phet-steele** [comment]
@lmulhall-phet note the date on the scenery fix (https://github.com/phetsims/scenery/commit/ef52b4c39792a112c4949576ed31bb6f3523787c) and how it comes after the build date for this dev (https://github.com/phetsims/balloons-and-static-electricity/commit/680f64f74248911af8576f73d91992846a0dcd34). As @jessegreenberg said, 1.4.0-dev.24 is expected to have the issue.

**Comment by lmulhall-phet** [comment]
Thanks, @phet-steele!
