### ISSUE TITLE
Weird focus issues with green balloon

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#410]
From https://github.com/phetsims/scenery/issues/713

> In BASE I am seeing that behavior for everything except the green balloon (when clicking green then tabbing, it still highlights the yellow balloon). Is that a bug?

**Comment by jessegreenberg** [comment]
Also, picking up the green balloon after using enter or spacebar (immediately after adding balloon to screen) makes focus go away.

My guess is this is caused by moveToFront().

**Comment by terracoda** [comment]
@jessegreenberg, focus highlight is behaving very strange in Safari as well with both balloons active.

With keyboard alone:
- sometimes do not get grabbed focus highlight
- tabbing away sometimes does not release balloon and coming back to it, it is already grabbed and gets the dotted grabbed focus outline.
- tabbing through after an un-indicated grab, a tab will first go to the solid outline then the next tab goes to the grabbed focus highlight on the same balloon.

With VoiceOver on:
- when the grabbed state does not visually appear, I cannot move the balloon, though Voice does indeed say it is grabbed.
- tabbing around a bit fixes things temporarily.

**Comment by jessegreenberg** [comment]
If I remove the moveToFront() calls to move the focused balloon to the front, the problem goes away.

**Comment by terracoda** [comment]
@jessegreenberg, awesome! 
Do you think there is  a way to fix the moveToFront() call?

The moveToFront() call is so that the grabbed balloon always appears in front, right?

**Comment by jessegreenberg** [comment]
Exactly, it looks like that is the only way. This was introduced somewhere in the recent a11y tree remapping work.

**Comment by jessegreenberg** [comment]
This will be handled in scenery, created https://github.com/phetsims/scenery/issues/809 to work on it.

**Comment by terracoda** [comment]
Thanks @jessegreenberg!

**Comment by jessegreenberg** [comment]
A working solution has been added and this has been fixed.

**Comment by terracoda** [comment]
@jessegreenberg, looks good in Safari!
