### ISSUE TITLE
Sometimes balloon velocity is described when it is too small to notice

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#413]
For instance:
![capture](https://user-images.githubusercontent.com/6396244/41067403-afa8fe30-69a2-11e8-8165-bbd7772ef17c.PNG)
There is some non zero velocity, but We will keep hearing "Moving Up" forever. It is easy to hit this case by
- Removing wall
- Charging balloon
- Moving balloon to right edge of play area
- Quickly adding wall back in

The force on the balloon will have some vertical component that does not go away after it hits the wall.

@terracoda I am going to make it so that when the balloon is moving this way, we don't get any velocity updates. This issue seems familiar, its possible you already requested this before!

**Comment by terracoda** [comment]
This is a familiar issue. The description we adjusted last time was "sticking to wall." We decided to stop  using that description.

I think your suggestion here will work. I think it allows us to have velocity on more of the complex movement scenarios (which is good and I think was lacking before) while also having a description that is kind of moving without velocity.

Great idea, @jessegreenberg.

**Comment by jessegreenberg** [comment]
Sounds great @terracoda, thanks! I will proceed then.

**Comment by jessegreenberg** [comment]
Ok, done in the above commit. I added a threshold, determined empirically. The velocity was magnitude of velocity was chosen such that when the movement of the balloon is not observable visually, no alerts occur.

Another way to go might have been to place a minumum value when setting velocity in BalloonModel, but I was concerned that would have larger impacts so I avoided it.
