### ISSUE TITLE
[1.2.3-rc.2], [1.3.5-rc.1] poor wrapper performance

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/balloons-and-static-electricity#414]
System: PC Laptop 

OS: Windows 10 v. 1803

Browser: Google Chrome v. 67.0.3396.79

Problem Description: For phetsims/QA#128 when both version 1.2.3 and version 1.3.5 of the balloon and static electricity sim are run with the events colorized, events textarea, and state wrappers the sim performs poorly with the balloons jumping from location to location when moved too quickly. I have checked this in master as well and the issue is still present in all three wrappers. The problem seems to increase as the balloon becomes more negatively charged, maybe something to do with moving all of the negative charges that accumulate on the balloon.

Reproduce Steps:
1. Open BASE v. 1.2 or 1.3 from phetsims/phet-io#1329 (standalone)
2. Navigate to the wrappers index using {{sim name}}/{{version}}/wrappers/index/
3. Open any of the events: colorized, events: textarea, or state wrappers (&relativeSimPath works for this sim)
4. Move balloon around the screen quickly while in any of these wrappers, the balloon should lag behind the cursor location

**Comment by jonathanolson** [comment]
Console output would slow most things down. Is it just related to that?

**Comment by lmulhall-phet** [comment]
@jonathanolson, I think so. The performance isn't great, but I would say it's acceptable. I assume you're OK with slightly suboptimal performance for this wrapper. I move to close this issue if no one objects.
