### ISSUE TITLE
Extra movement & incorrect charge alerts when Wall is added to play area and balloon is at right edge

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#415]
Restarting second from #411 here in a new issue.
Sorry for any confusion.

I found a similar case, opposite case, rather, when there are two balloons and one is staying calmly on right edge of Play Area and the Wall is added back in, the alert says:

    "Wall added to Play Area."
    "Yellow Balloon, now left."
    "Yellow balloon, moving left."

While again, these are correct, position information would be better here. Something like,

    "Wall added to Play Area."
    "Yellow Balloon, now left." (Not really necessary, but can leave it in if it is difficult to remove.)
    "Yellow balloon, at {{upper}} wall. Negative charges in {{upper}} wall move away from balloon {{a little bit}}. Positive charges do not move." (This would be the exact same as the release alert where the balloon ends at the wall.)

@jessegreenberg, is this as easy as the previous fix, or should I start a new issue?

**Comment by terracoda** [comment]
This issue has not been fixed by this commit  68e720b 
The descriptions for the wall are incorrect.
![screen shot 2018-06-08 at 11 57 31 am](https://user-images.githubusercontent.com/1902116/41163431-3371c5fa-6b13-11e8-9e26-52dbb5a72edd.png)

@jessegreenberg, we don't want the "rubbing alert", but rather the final part of a "release alert"
Like this one. I just released the balloon close to the same spot to get the content. 
![screen shot 2018-06-08 at 12 07 58 pm](https://user-images.githubusercontent.com/1902116/41163977-9f5fda1c-6b14-11e8-9505-47b638b1156c.png)

@jessegreenberg, does that make sense?

**Comment by terracoda** [comment]
@jessegreenberg, assign me if you want me to do further testing.

**Comment by jessegreenberg** [comment]
@terracoda I think this is done, can you please review master to make sure?

**Comment by terracoda** [comment]
@jessegreenberg, when I add the wall back in, I still hear:
- Green balloon, now left. (which is fine)
- At lower wall. In lower wall, no change in charges." when I add the wall back in. (but this is not accurate as the charges move away from green balloon a little bit.)

I am going to pull from master again in case I tried before you committed.

**Comment by terracoda** [comment]
I see changes...testing again :-)

**Comment by jessegreenberg** [comment]
Hmm, I am not able to reproduce that in master. Let me know if you see again and maybe we can screen share.

**Comment by terracoda** [comment]
@jessegreenberg, it's good now! I tested too soon!

I sometimes hear "Green balloon, now left." which is fine, and I am not getting the correct charge description!

Closing!
