### ISSUE TITLE
BalloonNode's accessibleDragNode behaves differently for keydown/up and blur

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#425]
Found while working on https://github.com/phetsims/scenery-phet/issues/368
Take a look at this code: 
```js
    accessibleDragNode.addAccessibleInputListener( {
      keydown: function( event ) {
        if ( event.keyCode === KeyboardUtil.KEY_ENTER ) {
          releasedWithEnter = true;
          releaseBalloon();
        }
      },
      keyup: function( event ) {
        // release  on keyup of spacebar so that we don't pick up the balloon again when we release the spacebar
        // and trigger a click event - escape could be added to either keyup or keydown listeners
        if ( event.keyCode === KeyboardUtil.KEY_SPACE || event.keyCode === KeyboardUtil.KEY_ESCAPE ) {
          releaseBalloon();
        }
      }
//...
      blur: function( event ) {
        if ( !self.movingToFront ) {
          endDragListener();

          // the draggable node should no longer be focusable
          accessibleDragNode.accessibleVisible = false;

          self.dragNodeBlurredEmitter.emit();

        }
      }
    } );
```

Shouldn't the blur event interrupt the drag also? Maybe I don't understand this fully. What do you think @jessegreenberg?

**Comment by zepumph** [comment]
Note: `releaseBalloon()` calls the interrupt on the drag handler, but `endDragListener()` does not.

**Comment by jessegreenberg** [comment]
I added some documentation and renamed a function to hopefully improve clarity. The blur event should interrupt keyboard dragging, but it already did/does. Prior to https://github.com/phetsims/scenery-phet/issues/368, the KeyboardDragListener was `reset` on the `blur` event. Now `Accessibility.interruptAccessibleInput` is doing this for us on `blur`. @zepumph does this seem OK?

**Comment by zepumph** [comment]
Yes it makes sense now, thanks!
