### ISSUE TITLE
Adjusting ResetAllButton position, and other polishes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/balloons-and-static-electricity#439]
@jessegreenberg with the universal dilation of the ResetAll Button, it slightly overlaps the navbar in this sim (accidental touch between this button and the keyboard nav button seems more likely currently).

I suggest moving both the ResetAllButton and Remove Wall button vertically.

Additionally, having not looked at this sim in awhile, I see a few other obvious polishes:

1. The other controls (radio buttons and such) should also be moved a few pixels vertically up. They all seem unnecessarily close to the navbar. This would also allow preservation of the current bottom alignment of everything. 

2. It seems odd to me that the "Remove Wall" button is so large and overlaps the wall. It seems it size could be reduce a bit and its font size made to match the Reset Balloon Button. I am not sure in the flow of the sim it should have such a prominent visual weight. Then it would sit completely withing the wall, and not be so tight to the dev bounds.

![balloonstoucharea](https://user-images.githubusercontent.com/4051174/51954147-4baefa00-23fc-11e9-85b5-c75436507a50.PNG)

**Comment by jessegreenberg** [comment]
Looks like test code to make the touch areas smaller than the bounds of the node, which actually isn't possible. Discovered and discussed as part of that issue that this is not possible. So these lines have no impact and should not have been committed.

**Comment by jessegreenberg** [comment]
Should be done, @ariel-phet can you please review master?

**Comment by ariel-phet** [comment]
Awesome @jessegreenberg - looks great. Closing
