### ISSUE TITLE
Sim rescales and becomes unusable in phet-io iframe applications on iOS

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#440]
I'm working on sound design prototypes that make use of the phet-io API, and I've run into an issue with this sim on iOS devices where it abruptly scales itself in such a way that the lower portion of the sim becomes unreachable.  I was able to duplicate the problem on iOS 11 and iOS 12 using most of the wrappers at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.3/phet-io/.  

To duplicate:
+ I've only seen this on iOS, and I tried it on iOS11 & 12 and it happened on both of those
+ Go into any of the wrappers at the above link, such as "studio"
+ Enable the 2nd balloon
+ Drag it downwards

This worked about 90% of the time to recreate the issue for me.  There are lots of other ways to make it happen to, so generally just playing around with the sim will make it occur eventually.

I'm assigning to @jessegreenberg initially for two reasons.  One is that he is the responsible dev.  The second is that I saw a number of releases in the dev area from a branch labeled something like `pdomTransform`, so I thought maybe this was related.

I tested an older phet-io release at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.0-dev.27/ and this problem didn't seem to occur.

It would be nice to get this fixed fairly quickly if possible, since we want to use this sim for some of the PISEC testing with sound, and this problem makes the sim pretty much unusable for that purpose.

Tagging @jonathanolson and @zepumph in case they have any immediate insights.

**Comment by phet-steele** [comment]
@jbphet does it look like any of the screenshots in phetsims/phet-io/issues/998? (there are many to look through)

**Comment by jessegreenberg** [comment]
Thank you @phet-steele! That does look related.

That issue recommends `scrolling="no"` on the iframe as a fix but I don't know if that was explored. Do wrapper iframes use `scrolling="no"` attribute?

I only have access to iOS 9.3.5, something similar is happening there but not exactly what is described in https://github.com/phetsims/balloons-and-static-electricity/issues/440#issue-409051139. The iframe gets larger when dragging a balloon, but the sim is still usable. Sometimes the iframe snaps back to the original size then doesn't change again.

Nothing from the sim branch `pdomTransform` should be in master, so I don't expect that to be related.

**Comment by jessegreenberg** [comment]
In studio, `document.getElementById( 'source' ).scrolling` returns `""`, so it probably isn't being used. I am curious if this is happening in other sims.

**Comment by jbphet** [comment]
It does look like it could be related.  What I'm seeing is a little different - it doesn't have a big nav bar the way the screenshots in the other issue do.  I'll some captures below.

I'll try turning off the scrolling the in iframe wrappers.
![image](https://user-images.githubusercontent.com/3082831/52653598-7a71a980-2ead-11e9-9534-88d7a45af4d5.png)
![image](https://user-images.githubusercontent.com/3082831/52653653-a42ad080-2ead-11e9-83fa-15c74cea2328.png)

**Comment by jessegreenberg** [comment]
Thanks for the pictures, that looks similar to what I am seeing in the "active" wrapper on iOS 9.3.5. That wrapper lets me scroll down, and when I do I can see the navigation bar.

I also tested https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.4.0-dev.27/ and I did not see the problem there either. scrolling="no" isn't used there either, so it may not be related to that after all.

**Comment by jessegreenberg** [comment]
I just verified this isn't happening on my Windows laptop with a touch screen.

**Comment by jessegreenberg** [comment]
I tried to test a recent version of friction to see if this was happening there, but it isn't loading on my iPad2. Maybe wrapper code is using es6? https://github.com/phetsims/phet-io-wrapper-sonification/issues/70

**Comment by jessegreenberg** [comment]
I also just found https://github.com/phetsims/phet-io-wrapper-sonification/issues/71, it seems like the issue could be very related to that.

**Comment by jessegreenberg** [comment]
As a final test, found that this is not happening in the sim in the a11y view at http://localhost:8080/balloons-and-static-electricity/build/phet/balloons-and-static-electricity_a11y_view.html. That iframe does use `scrolling=no`, but I don't know if that is related.

The way the sim is dragged down in https://github.com/phetsims/balloons-and-static-electricity/issues/440#issuecomment-462844827 makes me think this is somehow related to scrolling though, so https://github.com/phetsims/phet-io-wrapper-sonification/issues/71 might address this issue.  

Sorry I couldn't be of more help, removing my assignment.

**Comment by jbphet** [comment]
Adding `scrolling=no` didn't change anything.

Below is a screen capture of the behavior in the "Studio" wrapper of the recently published phet-io version at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.3/phet-io/.  This was captured on the PhET test device "Hopper" running iOS 12.1.4.

![base-resize-scaled-2](https://user-images.githubusercontent.com/3082831/52664347-068fcb00-2ec6-11e9-9683-fc3f5c8260bb.gif)

@chrisklus has expressed an interest in taking a look at this, so I'm assigning it to him for now.

**Comment by chrisklus** [comment]
I looked into this for a while today. I found that I could reproduce with any wrapper that loads the sim in an iframe, like active and state. In both of those cases, adding `scrolling="no"` to the iframe tag consistently fixed the problem. I didn't have any luck when adding that to the sonification wrapper, but I'm now realizing that it's possible that it wasn't being interpreted, because the `width="" height=""` arguments that were also part of the iframe tag weren't working (they were being overridden in css). I'd like to investigate that a bit more tomorrow morning.

I also noticed that when the sim is turned to portrait view and then back to landscape, the sim doesn't resize correctly, but instead remains at the same aspect ratio from portrait view (but at 100% screen width, so only the top part of the sim is visible). This was only occurring when loaded in the sonification wrapper, and I was able to reproduce with other sims in the sonification wrapper as well. I have a feeling that fixing this resizing issue would also fix the vertical-growth issue, since the iframe should be respecting its width and height of 100%. When turned to portrait mode, the iframe correctly fills the page at 100% width and height, and the vertical-growth problem does not occur.

**Comment by chrisklus** [comment]
>I didn't have any luck when adding that to the sonification wrapper, but I'm now realizing that it's possible that it wasn't being interpreted, because the `width="" height=""` arguments that were also part of the iframe tag weren't working (they were being overridden in css). I'd like to investigate that a bit more tomorrow morning.

I just tried this again after commenting out the iframe css and verifying that `scrolling="no"` was working, but the sim still gets taller.

**Comment by zepumph** [comment]
I can't say that I've read every word above (only skimmed). I wonder if this problem has to do with how BASE is layed out as a sim. I don't know why, but I have noticed that the screenview in BASE is always bottom justified, no matter the size of the sim window. The dev bounds (or something like it) seem to  be always touching the navbar. Notice here:

![image](https://user-images.githubusercontent.com/6856943/52748859-183fa400-2f94-11e9-86a9-fd4cc970beb5.png)


Whereas other sims put the  screenview centered horizontally in the sim. 

![image](https://user-images.githubusercontent.com/6856943/52748898-37d6cc80-2f94-11e9-9911-f69adced750f.png)

Perhaps investigation there may yield more pertinent information.

**Comment by jessegreenberg** [comment]
Good point @zepumph, BASE does use a layout strategy that keeps the sim bottom aligned with the nav bar (https://github.com/phetsims/balloons-and-static-electricity/issues/77).

energy-skate-park/energy-skate-park-basics does something similar, if this is the reason, it will likely show up in wrappers for those sims too.

**Comment by chrisklus** [comment]
>I wonder if this problem has to do with how BASE is layed out as a sim. I don't know why, but I have noticed that the screenview in BASE is always bottom justified, no matter the size of the sim window.

Thanks @zepumph! Indeed, that is why the sim goes down when the problem happens (and therefore is unusable in the wrapper), but I don't think it is related to cause of the expansion of the iframe. I previously tried changing its layout function to the standard one, and the problem still ocured, but with the sim staying in the center of the iframe instead of floating to the bottom.

**Comment by jbphet** [comment]
Marking for dev meeting to try and figure out who can help us fix this.

**Comment by Denz1994** [comment]
@samreid will assist with this going forward by tethering a device.

**Comment by samreid** [comment]
I tried using `<iframe id="sim" style="position:fixed; top:0; left:0; bottom:0; right:0; width:100%; height:100%; border:none; margin:0; padding:0; overflow:hidden; z-index:999999;"></iframe>` as indicated in https://stackoverflow.com/questions/3982422/full-screen-iframe but that still showed the same symptom.

**Comment by samreid** [comment]
Using this patch I am unable to see the problem on iPad after about 2 minutes of testing (problem normally occurs after around 20-30 seconds).

<details>

```
Index: scenery/js/accessibility/AccessibleSiblingStyle.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- scenery/js/accessibility/AccessibleSiblingStyle.js	(revision 92e64cd15c7e58af419691c90e05384f941a994d)
+++ scenery/js/accessibility/AccessibleSiblingStyle.js	(date 1550247518000)
@@ -22,43 +22,43 @@
   // All elements that use AccessibilityUtil.createElement should have this style. The only exception is the root of
   // the PDOM, which should use 'a11y-root' class attributes instead.
   SceneryStyle.addRule( '.' + SIBLING_CLASS_NAME +
-    '{' +
-      // fixed to the 'relative' styled root element, to be transformed with left/top
-      'position: fixed;' +
+                        '{' +
+                        // fixed to the 'relative' styled root element, to be transformed with left/top
+                        'position: fixed;' +
 
-      // ABSOLUTELY CRITICAL - so PDOM elements do not interfere with rest of scenery input
-      'pointer-events: none;' +
+                        // ABSOLUTELY CRITICAL - so PDOM elements do not interfere with rest of scenery input
+                        'pointer-events: none;' +
 
-      // default, to the 'relative' root PDOM element - will change with node transform if focusable
-      'top: 0px;' +
-      'left: 0px;' +
+                        // default, to the 'relative' root PDOM element - will change with node transform if focusable
+                        'top: 0px;' +
+                        'left: 0px;' +
 
-      // for CSS transformations of focusable elements, origin at left top
-      'transform-origin: left top 0px;' +
+                        // for CSS transformations of focusable elements, origin at left top
+                        'transform-origin: left top 0px;' +
 
-      // helps get accurate bounds with getBoundingClientRect() for transformations
-      'border-width: 0px;' +
-      'border: 0px;' +
-      'padding: 1px 1px;' + // cannot be zero, otherwise certain elements will have undefined width and height
-      'margin: 0px;' +
-      'white-space: nowrap;' +
+                        // helps get accurate bounds with getBoundingClientRect() for transformations
+                        'border-width: 0px;' +
+                        'border: 0px;' +
+                        'padding: 1px 1px;' + // cannot be zero, otherwise certain elements will have undefined width and height
+                        'margin: 0px;' +
+                        'white-space: nowrap;' +
 
-      // to remove the default focus highlight around HTML elements
-      'outline: none;' +
-      'box-shadow:none;' +
-      'border-color:transparent;' +
+                        // to remove the default focus highlight around HTML elements
+                        'outline: none;' +
+                        'box-shadow:none;' +
+                        'border-color:transparent;' +
 
-      // So that elements can never be seen visually, can comment this out to "see" transformed elements in the
-      // PDOM. Text and Backgrounds of elements are made transparent where possible. Text is made very small so that
-      // it doesn't extend into the display. Very low opacity on the root takes care of the rest.
-      'font-size: 1px;' + // must be at least 1px to be readable with AT
-      'color: transparent;' +
-      'background-color: transparent;' +
+                        // So that elements can never be seen visually, can comment this out to "see" transformed elements in the
+                        // PDOM. Text and Backgrounds of elements are made transparent where possible. Text is made very small so that
+                        // it doesn't extend into the display. Very low opacity on the root takes care of the rest.
+                        // 'font-size: 1px;' + // must be at least 1px to be readable with AT
+                        // 'color: transparent;' +
+                        // 'background-color: transparent;' +
 
-      // Just for debugging!
-      // color: white // helpful for seeing text over a black background
-      // 'z-index: 5000;' + // on top of other display Blocks
-    '}'
+                        // Just for debugging!
+                        // color: white // helpful for seeing text over a black background
+                        // 'z-index: 5000;' + // on top of other display Blocks
+                        '}'
   );
 
   SceneryStyle.addRule( '.' + ROOT_CLASS_NAME +
Index: phet-io-wrapper-sonification/balloons-and-static-electricity/html/balloons-and-static-electricity-sonification.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- phet-io-wrapper-sonification/balloons-and-static-electricity/html/balloons-and-static-electricity-sonification.html	(revision 03413eb971ea31f771222f0c2590dea6325d2ef8)
+++ phet-io-wrapper-sonification/balloons-and-static-electricity/html/balloons-and-static-electricity-sonification.html	(date 1550247097000)
@@ -17,8 +17,6 @@
 <head>
   <title>PhET-iO Sonification Wrapper</title>
   <link rel="stylesheet" type="text/css" href="../../../phet-io-wrappers/common/css/full-screen-iframe.css">
-  <script
-      src="https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.3/phet-io/lib/phet-io.js"></script>
 </head>
 
 <body>
@@ -26,6 +24,12 @@
 <!-- define iframe where sim will run -->
 <iframe id="sim" width="100%" height="100%"></iframe>
 
+<script src="../../../query-string-machine/js/QueryStringMachine.js"></script>
+<script src="../../../phet-io-wrappers/common/js/WrapperTypes.js"></script>
+<script src="../../../phet-io-wrappers/common/js/assert.js"></script>
+<script src="../../../phet-io-wrappers/common/js/Client.js"></script>
+<script src="../../../tandem/js/PhetioIDUtils.js"></script>
+
 <script>
 
   // Set up the global values needed by the code used in this prototype to run correctly.  This is, admittedly, rather
@@ -39,7 +43,8 @@
     chipper: {
       queryParameters: {
         sound: 'enabled',
-        enhancedSoundInitiallyEnabled: true
+        enhancedSoundInitiallyEnabled: true,
+        rootRenderer: 'canvas'
       }
     }
   };
Index: balloons-and-static-electricity/js/balloons-and-static-electricity-main.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- balloons-and-static-electricity/js/balloons-and-static-electricity-main.js	(revision dc1fb0313cc9aa0422426f2b6fb8186657012667)
+++ balloons-and-static-electricity/js/balloons-and-static-electricity-main.js	(date 1550247406000)
@@ -35,7 +35,7 @@
         graphicArts: 'Sharon Siman-Tov',
         thanks: 'Thanks to Mobile Learner Labs for working with the PhET development team to convert this simulation to HTML5.'
       },
-      accessibility: true,
+      accessibility: false,
       keyboardHelpNode: new BASEKeyboardHelpContent()
     };
 
Index: chipper/js/initialize-globals.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- chipper/js/initialize-globals.js	(revision d1f53936f6a457abd523088a77d111195b13aeb0)
+++ chipper/js/initialize-globals.js	(date 1550242849000)
@@ -362,7 +362,7 @@
      */
     rootRenderer: {
       type: 'string',
-      defaultValue: null,
+      defaultValue: 'canvas',
       validValues: [ null, 'canvas', 'svg', 'dom', 'webgl' ] // see Node.setRenderer
     },
 

```

</details>

**Comment by samreid** [comment]
Likewise, I built a version of balloons and static electricity with `accessibility: false`.  Pointed to it in the phet-io-wrapper-sonification/balloons-and-static-electricity/html/balloons-and-static-electricity-sonification.html and cannot reproduce the problem after a few minutes of testing.

**Comment by samreid** [comment]
@jbphet would it work to build and publish a dev version of BASe with `accessibility: false` to use for PISEC, until we can get the root problem solved?

**Comment by samreid** [comment]
@jessegreenberg putting `accessibility: false` seems to prevent this problem.  I do not know all of the things that happen when `accessibility: true`, but perhaps there are more DOM elements created, and one of them is interfering with the iframe bounds.  I'm not sure the best way to investigate this avenue further.

**Comment by jessegreenberg** [comment]
OK, thanks @samreid, Ill take a look.

**Comment by samreid** [comment]
I also wanted to refer to https://github.com/phetsims/scenery/issues/852 which appears to be the issue for updating dom peer bounds on mobile.

**Comment by jessegreenberg** [comment]
I tried disabling updating DOM peer bounds, so all elements are hidden in the top left of the screen, but the problem still occurred. I verified that I wasn't testing a chached version by checking the build time stamp in the about dialog.

**Comment by jessegreenberg** [comment]
I am wondering if this may have been caused by this styling change to the PDOM from last year: https://github.com/phetsims/scenery/commit/2602da303f9246852a3e23bfe268368899a011bb

**Comment by jbphet** [comment]
I noticed something else that may be related (and if it isn't, we should log a separate bug):  Trying to access the PhET menu from BASE inside the sonification wrapper locks up the sim.  It also crashes the sim when running in Chrome, which is nice, because that means it's easy to duplicate.  The stack trace seemed to indicate that the problem had something to do with phet-io (error and stack trace below).  **However**, turning off accessibility made this problem go away, which is why I thought these might have the same root cause.

Here's a screenshot of the output when the error occurs:

![image](https://user-images.githubusercontent.com/3082831/52877375-0e927980-3117-11e9-964f-ee94a62c73e6.png)

Here's the stack trace:

```
window.assertions.assertFunction (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5556)
(anonymous) (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
toStateObject (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
toStateObject (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
(anonymous) (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
phetioStartEvent (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
set (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
set focus (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
show (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
listener (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
fire (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
a (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
set (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
onRelease (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
release (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
pointerUp (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
first (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
run (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
value (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
batchWindowEvent (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
onpointerup (balloons-and-static-electricity_all_phet-io_debug.html?ea&phetioEmitStates=false&phetioEmitStatesInterval=1&phetioEmitHighFrequencyEvents=true&postMessageOnError&sonificationFile=sonificationOptions&accessibility:5598)
```

**Comment by jessegreenberg** [comment]
Thanks @jbphet, I don't think that is related, but it is possible. Ill make a new issue for that.

**Comment by jessegreenberg** [comment]
I tried adding a number of CSS attributes that used to style the PDOM, but none of them made the issue go away: `position: absolute; left: 0; top: 0; width: 0; height: 0, clip: rect(0,0,0,0);`.

Then I tried keeping accessibility enabled, but removed the root of the PDOM from the Display. This did not fix the problem.

Finally, I tried disabling all alerts. This seems to have fixed the problem. So my theory is something about the aria-live elements is causing this.
```html
<div id='aria-live-elements' style="position: absolute; left: 0px; top: 0px; width: 0px; height: 0px; clip: rect(0px 0px 0px 0px); pointer-events: none;">
  <p id="polite-1" aria-live="polite"></p>
  <p id="polite-2" aria-live="polite"></p>
  <p id="polite-3" aria-live="polite"></p>
  <p id="polite-4" aria-live="polite"></p>
</div>
```

**Comment by jessegreenberg** [comment]
This is fixed on my ipad2 in the PhET-iO wrappers from "compiled index" of phetmarks. I wasn't able to run the sonification wrapper because it is using es6 code.

@chrisklus would you mind testing to see if the above change fixes this issue on the device you were using to test?

**Comment by chrisklus** [comment]
I did a pull-all, built a local BASE, and pointed the sonification wrapper to that file. All looks good, nice @jessegreenberg!

**Comment by zepumph** [comment]
Tagging @jbphet because it looks like things may be fixed now

**Comment by jessegreenberg** [comment]
Yes, thanks for testing @chrisklus, that is good news! Over to @jbphet to confirm and close or any next steps.

**Comment by jbphet** [comment]
I built a dev version at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.5/phet-io/balloons-and-static-electricity_all_phet-io.html and tested it in the wrapper, and it is indeed behaving well.  Thanks @jessegreenberg - closing.

**Comment by jessegreenberg** [comment]
OK great! Sorry for the trouble, and thanks everyone in this issue for the help in resolving this problem.
