### ISSUE TITLE
Incorrect arguments to Vector2 in unit tests

### ISSUE THREAD

**Issue by samreid** [phetsims/balloons-and-static-electricity#441]
Discovered in https://github.com/phetsims/dot/issues/85.  Some occurrences are passing an object instead of a number as the 2nd argument to Vector2.  This will appear shortly in unit test on Continuous testing.  Assigned to @jessegreenberg for investigation.

**Comment by jessegreenberg** [comment]
Thanks @samreid, #442 was also opened and was a duplication of this issue, unit tests are passing after https://github.com/phetsims/balloons-and-static-electricity/commit/7f93681fc12f8f719696c276a5c5360b44dd7d96. Closing.
