### ISSUE TITLE
branch: instrumentOnSweaterProperty

### ISSUE THREAD

**Issue by chrisklus** [phetsims/balloons-and-static-electricity#446]
I'm creating a one-off to instrument `onSweaterProperty` for usage in https://github.com/phetsims/phet-io-wrapper-sonification/issues/85. I'll delete the branch once I've published the one-off.

Tagging @jessegreenberg.

**Comment by chrisklus** [comment]
The one-off has been published at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-instrumentOnSweaterProperty.1/phet-io/, and this branch has been deleted. Closing.

**Comment by chrisklus** [comment]
The one-off has been published at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-instrumentOnSweaterProperty.2/phet-io/, and this time I'm going to leave this branch in existence until we are finished working with the students in Louisiana (8/2).

**Comment by jessegreenberg** [comment]
I checked with @chrisklus and verified that this is OK to delete now.
