### ISSUE TITLE
Found extra headings in PDOM

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#447]
In https://github.com/phetsims/phet-io-wrapper-sonification/issues/88 I noticed that there are extra headings in the PDOM.

@jessegreenberg could you make sure these headings haven't slipped out into production and also fix master.

Once you fix master, could you let @chrisklus know, so he can port a new version into the sonification wrapper if needed.

**Comment by terracoda** [comment]
<img width="1150" alt="Screen Shot 2019-07-30 at 8 14 28 PM" src="https://user-images.githubusercontent.com/1902116/62155079-56ddd680-b308-11e9-9e10-6951dc62b333.png">

**Comment by jessegreenberg** [comment]
Fixed in the above commit, related to https://github.com/phetsims/scenery-phet/issues/381.
