### ISSUE TITLE
branch: customZoom

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#448]
For phetsims/scenery#972, explored in this sim before the feature is fully integrated.

**Comment by zepumph** [comment]
@jessegreenberg, should this branch remain open, or be deleted as part of phetsims/special-ops#198?

**Comment by jessegreenberg** [comment]
Thanks, no need to keep this. It has been deleted.

**Comment by jessegreenberg** [comment]
Deleting again for https://github.com/phetsims/special-ops/issues/198
