### ISSUE TITLE
Can this code for wrapper support be removed?

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#450]
In 5665d744676f41130632abd69d78db71833ec157 some code was added that looks like this:

```js
  // modules used by wrappers
  require( 'TAMBO/sound-generators/SoundClip' );
  require( 'TAMBO/phetAudioContext' );
```

We've decided not to use wrappers for sound prototyping anymore.  Can this be removed?

**Comment by samreid** [comment]
Removed, thanks!  Closing.
