### ISSUE TITLE
Add sound generation for transfer of charge from sweater to balloon

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#451]
@liquatics is doing some prototyping of vibration for this sim (see #449) and has requested a bit of sound generation to support it.  Specifically, a sound generator should be added for the transfer of charges from the sweater to the balloon.  This was discussed in the 10/15 haptics meeting.  We also decided to use the same sound generator as that used for charge transfer in John Travoltage.

**Comment by jbphet** [comment]
@liquatics - assigning to you to test.  To hear the sound you'll need to use the `supportsSound` query parameter.  If it works as needed, you can close this issue, otherwise let me know what needs to change and assign back to me.

**Comment by jbphet** [comment]
At today's Haptics & Sound meeting, @liquatics said that she needed a development version published for her testing.  I've put one out at https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.13/phet/balloons-and-static-electricity_en_phet.html?supportsSound (note that the `supportsSound` query parameter is necessary for the sound to be able to play).

@liquatics - does this look (and sound) like what you need?

**Comment by liquatics** [comment]
@jbphet Just checked it out. This will work great for the upcoming interviews. I'll let you know if I run into any problems.
