### ISSUE TITLE
Not getting grab/release alerts during grab and drag with iOS VoiceOver

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#456]
From #452 and #455. Also related to #453 but making another issue because I think there are a few things going on.

@terracoda said 
> I mentioned I wasn't hearing "Release" responses. It's possible they are getting lost due to the pile up of responses in the utteranceQueue.

I also almost always never hear the "Grabbed" alerts.  Im not sure yet if we are missing both for the same reasons.

For the "grabbed" alerts, I think the balloons is actually not getting grabbed on iOS until the first movement of the finger. And so if you press and hold down the balloon without moving your finger, you never the grabbed alerts. GOing to tether to a mac to see for sure.

**Comment by jessegreenberg** [comment]
> I think the balloons is actually not getting grabbed on iOS until the first movement of the finger. 

No, what is actually happening is that the grabbed alert isn't being sent to the utteranceQueue until the first movement of the balloon rather than first pickup. I think this can be changed.

**Comment by terracoda** [comment]
> No, what is actually happening is that the grabbed alert isn't being sent to the utteranceQueue until the first movement of the balloon rather than first pickup. I think this can be changed.

That describes what was happening during my testing, perfectly.

**Comment by jessegreenberg** [comment]
This was fixed with the above commit.
