### ISSUE TITLE
keyboardInteractionCue should only disappear after the balloon is successfully moved

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#460]
It currently goes away after successful pick up, rather than successful move.

**Comment by zepumph** [comment]
@jessegreenberg  you have already used this here, but is `GrabDragInteraction.successfulDrag` enough to solve this issue?

**Comment by jessegreenberg** [comment]
Thanks, very likely! Ill take a look at that to fix this.

**Comment by jessegreenberg** [comment]
I don't think this is an issue anymore, if this is how GrabDragInteraction works in general (and I verified that to be the case in a few other sims) it is how it should work for BASE too. Closing.
