### ISSUE TITLE
Unit test error: this.callback is not a function

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#466]
From https://github.com/phetsims/joist/issues/621#issuecomment-620000152

I thought it best to create a side issue instead of tackling it there. Without too much investigation, I wonder if this issue isn't from a unit test loading a module that then calls SimLauncher before it was imported.

**Comment by zepumph** [comment]
Unit tests are passing after fixing https://github.com/phetsims/balloons-and-static-electricity/issues/468. @samreid, when you get to this, if CT is clear please close.

**Comment by jessegreenberg** [comment]
CT has been clear for a while, closing.
