### ISSUE TITLE
problems with TwoSceneSelectionNode dispose

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#471]
Two problems in TwoSceneSelectionNode:

(1) There's a memory leak in `dispose`. TwoSceneSelectionNode is a subclass of Node.  So `dispose` needs to call `super.dispose`, and should be `@override`.

```
  /**
   * Make eligible for garbage collection.
   * @public
   */
  dispose: function() {
    this.disposeTwoSceneSelectionNode();
  },
```

(2) Half of `this.disposeTwoSceneSelectionNode` is unnecessary.  These 2 lines are not needed, since TwoSceneSelectionNode owns the listeners:

```
    this.removeInputListener( downUpListener );
    this.removeInputListener( clickListener );
```

I suspect that TwoSceneSelectionNode is never actually disposed, so an alternative would be to delete `dispose` and `this.disposeTwoSceneSelectionNode`.

**Comment by jessegreenberg** [comment]
Yes, thanks - it is never actually disposed so I removed `dispose` and `disposeTwoSceneSelectionNode`.
