### ISSUE TITLE
Should grab drag cue show after you have moved with the mouse?

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#475]
@emily-phet just noticed a potential bug. We expected that there would still be a drag cue until you successfully dragged the balloon with alt input. 

Steps to reproduce:

1. mouse drag the balloon to the top of the screen. 
2. tab to the balloon.
3. space to grab it.
4. No drag cue shows, just the dashed line.

@jessegreenberg, is this a bug or a feature? I'm also curious because of recent work in changing how the drag cue is shown. Any thoughts here?

**Comment by terracoda** [comment]
I currently, can get the visual cue on how to grab with Alt Input after a successful pick up with mouse.

I think this bug is fixed, so closing.
