### ISSUE TITLE
Sonification Implementation Notes

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/balloons-and-static-electricity#478]
@jbphet I thought if I added an issue it would help you track addressing the notes easier than email.

[I have created a BASE Sound Design document.](https://docs.google.com/document/d/10YGIROBfW2u4DA6JAA6XZuP0mAmErsquIJjaZ_AB5sM/edit?usp=sharing) Please look at the section below the table called "Sound Design Details Implementation Notes, Info for JB" for ideas I have for how we should start adding/correcting sound on this sim.

Also I can't assign anyone currently so I will copy this to your email.

**Comment by jbphet** [comment]
Thanks @Ashton-Morris.  I've set up the sound implementation checklist in a GitHub issue, see #479, so that will supersede this one.  Also, I've added the Sound Design team as a collaborator, so you should be able to assign and modify issues now.  Closing.
