### ISSUE TITLE
Replace grab/release sounds for the balloons or make them common

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#480]
In the sound design document for this sim @Ashton-Morris suggested temporarily using the grab/release sounds that were used for the magnet in "Faraday's Law" as the sounds for picking up and release of the balloons.  We would most likely replace these with something custom eventually.

I will copy these sound files over from Faraday's Law, but we won't have a corresponding asset in the `assets` directory.  This GitHub issue is being opened so that we remember to either replace the sounds or, if we eventually decide we like them, move them to tambo and make them a shared resource.

**Comment by Ashton-Morris** [comment]
I have two sets of Balloon Grab and Release options ready to implement. [Sounds for this sim will be stored here](https://drive.google.com/drive/folders/15ISSjQogiSKOCGlueZhYGfMUvARGTQ4s?usp=sharing)

- balloon-grab-001.mp3
- balloon-grab.mp3
- balloon-release-001.mp3
- balloon-release.mp3

**Comment by jbphet** [comment]
The sound design team - @Ashton-Morris, @emily-phet, and me - tried these out in the sim during this week's sound design meeting, and we feel like something that is a little more cartoonish and not as realistic is what we're after.  The magnet sounds (which are based on a wood block) that were previously used actually work fairly well in terms of being distinct, but are a little too "solid".  So, and this is always challenging to capture in words, maybe something with the clarity of the wood block sounds but a bit more "airy".

**Comment by Ashton-Morris** [comment]
I have created a few other options for us to try. 

- balloon-release-002.mp3
- balloon-grab-002.mp3 (To be played quietly)

- balloon-grab-003.mp3
- balloon-release-003.mp3

- balloon-release-004.mp3
- balloon-grab-004.mp3

- balloon-release-005.mp3
- balloon-grab-005.mp3

**Comment by jbphet** [comment]
These sounds were reviewed in the 2/16/2021 sound design meeting, and we decided to go with the 004 sounds from the list above.  @Ashton-Morris heard a bit of distortions in the sounds, though, so he is going to try creating them again, and then we will integrate these sounds before giving them final approval.

**Comment by Ashton-Morris** [comment]
I have cleaned the audio files and removed the distortion. They are labeled this

- balloon-release-006.mp3
- balloon-grab-006.mp3

**Comment by jbphet** [comment]
These new sounds were integrated and then reviewed and approved in today's sound design meeting.  Closing.
