### ISSUE TITLE
Negative charges in wall are cut off

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#481]
This might be a known issue. I just happen to notice this today on master. The negative charges in the published version look fine.
![Screen Shot 2021-02-08 at 11 44 30 AM](https://user-images.githubusercontent.com/1902116/107252256-ba71b580-6a0f-11eb-831a-a90d0ae56194.png)

**Comment by emily-phet** [comment]
@terracoda @jessegreenberg I believe this is a known issue. @jbphet has been working on this sim, adding sound, and we noticed this in a sound design meeting. I think @jbphet thinks he may have done this in his work on the sim. You'll probably want to check with him re maintenance release, as he has some things in progress at the moment.

**Comment by terracoda** [comment]
In light of issue https://github.com/phetsims/scenery-phet/issues/490 and the need for maintenance releases for a few sims including this one (BASE), @jbphet can you work with @jessegreenberg to make sure this image problem doesn't end up in the maintenance release.

Maybe the commits for the maintenance release are obvious, and there is no concern. 

Assigning the issue to you, @jbphet, just in case.

**Comment by terracoda** [comment]
Assign back to me if yo need me to verify anything or have any questions.

**Comment by terracoda** [comment]
@jbphet, @jessegreenberg said this bug won't be part of the maintenance release needed for https://github.com/phetsims/scenery-phet/issues/490 , so you can deal with this bug as you see fit within your own list of priorities :-)

**Comment by jessegreenberg** [comment]
Thanks @terracoda @emily-phet, good to know. The maintenance releases for phetsims/scenery-phet#490 will only include the fixing commit for that issue and shouldn't include other breaking changes in master, but we will be sure to check for this before we republish.

 From https://github.com/phetsims/balloons-and-static-electricity/issues/481#issuecomment-779250924 it sounds like @jbphet may be aware of changes for this issue already so I will leave him assigned, but let me know if I should look into it!

**Comment by jbphet** [comment]
This was identified in https://github.com/phetsims/balloons-and-static-electricity/issues/482 and has been addressed.  It was a Scenery bug, and was not related to any of the work that was being done for sonification.  And, for the record, I never thought that it was.  Closing.
