### ISSUE TITLE
Negative charges in wall are incorrectly rendered

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#482]
On master, the charges on the wall look like this:

![image](https://user-images.githubusercontent.com/3082831/107424053-6b448700-6ada-11eb-998d-d7f7dc00ac78.png)

They should look like this:

![image](https://user-images.githubusercontent.com/3082831/107424124-82837480-6ada-11eb-88d4-0ed983cceb38.png)

I did some digging, and I think the problem started with this commit to scenery: https://github.com/phetsims/scenery/commit/3b738ccdde323627a6846ea3156772f6e03af67d.  I reverted my local copy of scenery to the previous commit (https://github.com/phetsims/scenery/commit/4b032f5b97d71818393499d9ea41cf8f748cf67c) and the problem went away.

@jonathanolson - this looks related to some work you were doing.  Can you please take a look?

**Comment by jonathanolson** [comment]
Looking into it!

**Comment by jonathanolson** [comment]
Was a bit tricky to track down, as it was actually rasterizing an already-rasterized node that made the bug apparent!

I neglected to handle rasterization scale properly in my change, and it should be fixed above. @jbphet can you verify?

**Comment by jbphet** [comment]
Yep, the charges look great now.  Thanks, closing.
