### ISSUE TITLE
Create a sound to use as a "carrier" for the balloon drift velocity

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#483]
The parent issue for this is https://github.com/phetsims/balloons-and-static-electricity/issues/479.

An early prototype for the velocity at which the balloon drifts has been created and is called `BalloonVelocitySoundGenerator`.  It was based on a noise generator with a sliding filter.  We reviewed this in the 2/9/2021 sound design meeting and the feedback was that it sounded a bit too "breathy", and we've gotten feedback that teachers dislike this because it cues the students that the air is somehow important.

For the next step, we're going to have @Ashton-Morris create a "carrier" sound, meaning a sound whose pitch will be varied in much the same way that the pitch of the current filter is changing and see if that works better.  We're thinking something kind of like the sound used in Gravity Force Lab for the force level, but somewhat more playful.

**Comment by Ashton-Morris** [comment]
I have created 3 looping options for the carrier sound. All whistle like but each with more or less wind in the sound. They are in our shared sound folder.[
](https://drive.google.com/drive/u/1/folders/15ISSjQogiSKOCGlueZhYGfMUvARGTQ4s)
- carrier-000.wav
- carrier-001.wav
- carrier-002.wav

**Comment by jbphet** [comment]
These have been integrated into the master version, and we will review during today's sound design meeting.

**Comment by jbphet** [comment]
Reviewed in the 2/16/2021 sound design meeting and we decide that we liked carrier waves 000 and 002, and we should use the former for the yellow balloon and the latter for the green one.

**Comment by jbphet** [comment]
We reviewed the two different sounds in context in this week's sound design review meeting and approved it.  I think we're basically done here.  Closing.
