### ISSUE TITLE
Create a sound for when the balloon attaches to the sweater

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#484]
The parent issue for this is #479.

We need a sound for the moment when the balloon was drifting due to static charge and stops on the sweater.  The magnitude of this sound, meaning the duration and/or the volume, should be larger when the balloon has traveled more and smaller for shorter distances.

@Ashton-Morris will create a base sound for this and then @jbphet will integrate it into the sim with the behavior described above.

**Comment by Ashton-Morris** [comment]
I have added a file for this

- balloon-hit-sweater.mp3

**Comment by jbphet** [comment]
This sound is now integrated and we can review at the next sound design meeting.

**Comment by jbphet** [comment]
Reviewed in the sound design meeting and approved.  Closing.
