### ISSUE TITLE
(Sound Design) Edge sounds for Play Area?

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#492]
For #486, I was just listening to BASE with sounds and I didn't hear any edge sounds indicating the edge of the play area.

These edges are described, but it is known from previous interviews that edge sounds are beneficial.

There may already be edge sounds, but they just are not currently hooked up.

**Comment by Ashton-Morris** [comment]
That is correct. We have noticed it but have not added them yet. They are needed though. I'll leave this issue open until we add them in.

**Comment by jbphet** [comment]
@Ashton-Morris - I went ahead and used the wall contact sound for all boundaries, and it seems pretty reasonable to me.  Please take it for a test drive on master and let me know what you think.

**Comment by terracoda** [comment]
@jbphet, that might work, but my feeling is that the wall is different than the other edges since it has charges in it, and can be rubbed.

Moving along any other edge won't make a rubbing noise, nor with they produce the induced charge effect sounds, so maybe those sounds will be enough to make it clear that the wall is different.

My main concern is when the balloon is moved to the right edge when the wall is not present. A learner would hear the same bump sound at the right edge and at the wall.

We may need a second sound for the other three edges that indicates an uninteresting boundary - oh, ok, I can't move any further in that direction.

We may not need two sounds. A more general edge sound might be useful in many sims.

**Comment by Ashton-Morris** [comment]
I have had troubles testing on Master but I think the edge boundary sounds from GFL:B Should work well in this.

https://phet.colorado.edu/sims/html/gravity-force-lab-basics/latest/gravity-force-lab-basics_en.html

**Comment by jbphet** [comment]
@Ashton-Morris discussed this in today's sound design meeting and we're going to try the boundary sound from ratio-and-proportion for this.  So, we will use that for all contacts except contact with the wall, whereupon we will use the current wall-contact sound.

**Comment by jbphet** [comment]
I've updated this to use a different sound for hitting the boundaries versus the edges.  @Ashton-Morris and @terracoda - please take it for a test drive (using phet-test and the current master version) and let me know if you think this will work.  Personally, I think this configuration is quite nice.

**Comment by terracoda** [comment]
I like it with the differentiated edge sounds. Thanks for making that change.

**Comment by Ashton-Morris** [comment]
After mixing the sim and testing it more thoroughly I feel that the top, bottom, and left boundary sounds are too similar in tone and timbre to the wall charge sounds. 

The boundary sounds tend to disappear into the other sounds, especially as you’re moving up and down the wall with some charges on it reaching the top and bottom of the sim.

I think in this case we should use the boundary sound from GFL:B instead.

**Comment by terracoda** [comment]
@Ashton-Morris, I am glad you mentioned that as I also thought they were a little too similar. I like having a different edge sound from the wall, but was a little concerned about the similar-ness to the induced charge sounds. I wasn't feeling so confident about my ears though. I will try to be more confident next time ;-)

**Comment by jbphet** [comment]
Okay, I've changed the non-wall edge sounds to be the same one used in gravity-force-lab-basics.  @Ashton-Morris and @terracoda - please try it out on master and see if you prefer this.

**Comment by jbphet** [comment]
We reviewed these sounds in a sound design meeting a while back, and they were approved.  Closing.
