### ISSUE TITLE
Adjust relative sound levels

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#496]
This is a step in the sound implementation process, and the parent issue is #479.

The sound design has been mostly implemented at this point, and it's time to do a "mix", meaning that the relative sounds levels should be adjusted.  

@Ashton-Morris - I've marked the adjustable output level parameters with the following comment, and you should be able to find these by searching through the code:

```
   // @Ashton-Morris - This is a sound parameter that can be adjusted.
```

I think I marked them all, but if you come across a sound and are unable to figure out how to adjust the level, let me know.

Please take a pass through the sim and either adjust the levels, and we can discuss at the next sound design meeting.

For reference, there is a non-mixed dev version published at  https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.27/phet/balloons-and-static-electricity_en_phet.html.

**Comment by Ashton-Morris** [comment]
```diff
Index: js/balloons-and-static-electricity/view/BalloonNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/balloons-and-static-electricity/view/BalloonNode.js	(revision 39bb668d46d375aee7aa7cc7f82284d0868651a4)
+++ js/balloons-and-static-electricity/view/BalloonNode.js	(date 1618178460438)
@@ -260,7 +260,7 @@
     // sound generation for when the balloon contacts the sweater
     const balloonHitsSweaterSoundClip = new SoundClip( balloonHitsSweaterSound, {
       // @Ashton-Morris - This is a sound parameter that can be adjusted.
-      initialOutputLevel: 0.1
+      initialOutputLevel: 0.075
     } );
     soundManager.addSoundGenerator( balloonHitsSweaterSoundClip );
     model.velocityProperty.lazyLink( ( currentVelocity, previousVelocity ) => {
@@ -274,12 +274,12 @@
     // Add the sound generation for when the balloon hits the wall or the drag bounds.
     const balloonHitsWallSoundClip = new SoundClip( balloonHitsWallSound, {
       // @Ashton-Morris - This is a sound parameter that can be adjusted.
-      initialOutputLevel: 0.6
+      initialOutputLevel: 0.15
     } );
     soundManager.addSoundGenerator( balloonHitsWallSoundClip );
     const balloonHitsBoundarySoundClip = new SoundClip( generalBoundaryBoopSound, {
       // @Ashton-Morris - This is a sound parameter that can be adjusted.
-      initialOutputLevel: 0.6
+      initialOutputLevel: 0.4
     } );
     soundManager.addSoundGenerator( balloonHitsBoundarySoundClip );
     model.positionProperty.lazyLink( ( position, previousPosition ) => {
Index: js/balloons-and-static-electricity/view/ChargeDeflectionSoundGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/balloons-and-static-electricity/view/ChargeDeflectionSoundGenerator.js	(revision 39bb668d46d375aee7aa7cc7f82284d0868651a4)
+++ js/balloons-and-static-electricity/view/ChargeDeflectionSoundGenerator.js	(date 1618178662996)
@@ -85,7 +85,7 @@
 const octaveOffsetProperty = new Property( 0.2 );
 
 // @Ashton-Morris - This is a sound parameter that can be adjusted.
-const outputLevelProperty = new Property( 0.75 );
+const outputLevelProperty = new Property( 0.55 );
 
 // Map of strings to algorithms that will map a numerical bin number to a playback rate for a sound generator.  This is
 // organized in this way so that it can be fed into a combo box in SoundOptionsDialogContent.  Each of the algorithms

```

**Comment by jbphet** [comment]
@Ashton-Morris - I applied the patch above and removed the comment markers associated with the changed output levels.  However, I noticed that there were two places with comment markers for which the output levels weren't changed.  I left those in place, because I wasn't sure if they were missed or if you just decided that the levels were good at their current settings.  Can you please take another look and make sure that we don't need any changes in these places?

**Comment by Ashton-Morris** [comment]
@jbphet Those are correct. Those lines are when I set the sound to 0 to test which sound it was and then realized that it needed no changes.

**Comment by jbphet** [comment]
Okay, cool.  I've published a dev version with these sound levels.  @Ashton-Morris - please review and make sure that you're good with these levels and, if so, we'll close this issue and move one.  See  https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.28/phet/balloons-and-static-electricity_en_phet.html.

**Comment by Ashton-Morris** [comment]
Yup these sound great!
