### ISSUE TITLE
User suggestion: 'Show all charges' - balloon removes some but not all charges

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/balloons-and-static-electricity#497]
> I think it would be good if the balloon removed some but not all of the charges from the sweater. We don't want students to think that this is possible in macroscopic objects.

**Comment by terracoda** [comment]
I guess this would be like in the Friction sim, where for unknown reasons the atoms on the Physics book don't disappear and why some of the ones on the Chemistry book don't disappear. (I think I mean evaporate).

**Comment by jbphet** [comment]
@arouinfar is currently the responsible designer for this sim, assigning to her.

**Comment by terracoda** [comment]
Just a note, a change like this would impact strings that we have in the description design, like "only positive charges". 

I am not saying we shouldn't make the change, just if we do, we need to revisit the Interactive Description design to make sure nothing gets broken :-)

**Comment by jbphet** [comment]
@arouinfar - This sim is slated for republication from master shortly, and it would be good to get your input on this before that happens.  We should either disposition this issue as "deferred" or "blocks-publication".

**Comment by jbphet** [comment]
I asked @arouinfar about this over Slack, and she said:

> We won't be making that change[.]

I'm not entirely sure if that means ever or just for the upcoming release, so I'll mark it as deferred for now and @arouinfar can update when she has the time.

**Comment by arouinfar** [comment]
This is not a change request that we can accommodate. 

“Show all charges” will display all of the charges in the underlying model, not the actual number of charges in the real world. The positive and negative charges are meant to give a relative idea of charge. We are not displaying all of the charges within a real sweater. It is important to help students understand that electrons are transferred or relocated, but not the protons. It would be problematic if we only allow some of the electrons in the sweater representation to be removed.

I've amended the Teacher Tips to clarify this point, closing.
