### ISSUE TITLE
Getting some alerts about balloon movement after balloon is released with no charge

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#506]

**Comment by jessegreenberg** [comment]
While working on #491 @terracoda and I noticed this bug.

**Comment by terracoda** [comment]
Yes, I can sometimes hear a one or left, right, up, down alerts after a release.
And I am not hearing "Released." 
Released seems to get overridden by the balloon position response that is said right after the release.

I am not sure there if there is a simple solution to make sure the release response is heard.

**Comment by terracoda** [comment]
@jessegreenberg, after re-listening on MacOS and iOS, I am wondering how much it would cost us to not these simple directional responses when a balloon is in the grabbed state. I think we need them for independent balloon movement, "Green Balloon, moves slowly left."..."Green Balloon, now up." etc. But I have a feeling we do not need them when the balloon is grabbed.

If this is not straight-forward and you see potential for unintended side-effects, lets leave them in. 
Otherwise, I'd love a dev version that has them removed.

**Comment by jessegreenberg** [comment]
This was also caused by https://github.com/phetsims/balloons-and-static-electricity/issues/455

**Comment by jessegreenberg** [comment]
The problem is the order we are sending alerts to the queue.

![image](https://user-images.githubusercontent.com/6396244/126843671-6680e5f1-8098-4d9f-9d33-fb3b7a248410.png)

The direction utterance needs to happen before the released alert, but because of polling it is happening last.

**Comment by jessegreenberg** [comment]
The ordering problem is also because we are using GrabDragInteraction. The GrabDragInteraction sends the 'released' alert as soon as it happens but the BalloonDescriber sends the "No change..." and "Right."  alerts as they should be ordered.

We probably need to remove the alert in GrabDragInteraction by making it optional so we can alert it exactly when we want in BASE.

**Comment by jessegreenberg** [comment]
This was fixed in the above commit. The `directionUtterance` had an `alertStableDelay` such that it made the alert come after the "released" utterance of the GrabDragInteraction. The alerts are added to the back of the queue in the right order so removing the `alertStableDelay` for the `directionUtterance` fixed the problem.

I feel confident that this is a safe change because the alert of direction change during drag only happens if the change in position of the balloon is large enough, so the direction change information will not repeat itself unecessarily.

Closing.
