### ISSUE TITLE
Not hearing independent balloon movement alerts for the balloons

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#507]
We are often not hearing alerts related to balloon movement when it is moving independently from charge forces.

**Comment by jessegreenberg** [comment]
@terracoda was testing this on her Mac when we observed this happen.

However, they came through correctly when testing on her phone.

**Comment by terracoda** [comment]
@jessegreenberg, upon retesting this dev link
https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.30/phet/balloons-and-static-electricity_en_phet.html

With Safari and VO on Macbook Pro MacOS 10.13.6

I do hear independent balloon movement responses.

I have a feeling after a lot of use, some responses can stop working. This is kind of random on VO, and it used to happen a lot more frequently than it does now.

**Comment by terracoda** [comment]
I am hearing independent balloon movement responses. Maybe this issue can be closed?

**Comment by terracoda** [comment]
I am hearing independent balloon responses, so I am closing.
