### ISSUE TITLE
The "Remove Wall" button is no longer visible on the wall

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#509]
While testing today, I noticed that the "Remove Wall" button seemed to be gone, but then I found I could navigate to it using the tab keys.  Turns out that it is now behind the wall instead of in from of it.  After a little detective work, I believe I've traced it to this commit: https://github.com/phetsims/joist/commit/17645a7ad98b2177524b9cc9e61b5d0a9660a82c.

This was done by @jessegreenberg, so I'm going to assign it to him.

In general, this change seems like it could have similar impacts on other sims, so I'd recommend having QA regression test all sims that are using `pdomControlAreaNode` and `pdomPlayAreaNode` if we decide to keep this change.

**Comment by jessegreenberg** [comment]
Sorry about that, this has been fixed for BASE in the above commit. Ill check other sims in perennial/data/interactive-description to make sure this hasn't happened for those and make an issue to review z-order for those sims.

Back to @jbphet to confirm this is fixed in BASE.

**Comment by zepumph** [comment]
Discussed during dev meeting today, and we just need to double check this in BASE, and not all sims.

**Comment by jbphet** [comment]
The button is back, so this appears to be fixed.  I don't know enough about the consequences of using `this.addChild` instead of `this.pdomPlayAreaNode.addChild`, so I'll trust you on that, but I didn't notice any behavioral problems.  Plus, this is getting close to being re-released off of master, so any problems would likely be found by QA during testing.

I think we're good to close this.
