### ISSUE TITLE
Design doc for BASE sound design

### ISSUE THREAD

**Issue by emily-phet** [phetsims/balloons-and-static-electricity#510]
@Ashton-Morris Can you please (or finalize, if you've already started) a design doc for the sound design for BASE? That's the doc with the table listing all the sounds in the sim with a description, and a list of the filenames for the sounds. It would go in the PhET Design/Balloons and Static Electricity / Multimodal Features / Sound folder.

If you have questions on that, let me know.

When you're done, can you message me so I can take a read through and we can do a final review in an upcoming sound design meeting. Thanks!

**Comment by Ashton-Morris** [comment]
For some reason I did not get an email notification about this issue. Working on it now.

**Comment by Ashton-Morris** [comment]
While working on this I was remembering that someone asked me to create a Sound Design Document Template. Can you review this and how it is formatted and written?

[Sound Design Document Template](https://docs.google.com/document/d/1ukDfYziXaUjMKGawkrJ9v11O2IYv32MULQB2E3xoGHA/edit#heading=h.aks8yxxh5lwd)

Also, I placed it in this folder: Design Templates - Multimodal Features

**Comment by emily-phet** [comment]
Sound design document template looks great! I made a few tiny tweaks. I think it's good to go!

When we meet later today, can you show me the location of the folder it's in?

**Comment by Ashton-Morris** [comment]
Sure I can show you then.

**Comment by Ashton-Morris** [comment]
I have completed the documentation. @emily-phet [Please review it here.](https://docs.google.com/document/d/10YGIROBfW2u4DA6JAA6XZuP0mAmErsquIJjaZ_AB5sM/edit#heading=h.rh2254o1e8yd)

**Comment by jbphet** [comment]
Discussed this in today's sound design meeting, and the document has been reviewed and is good to go.  Closing.
