### ISSUE TITLE
Crackling sound heard when balloon moves on iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balloons-and-static-electricity#527]
**Test device**
iPad

**Operating System**
14.7.1

**Browser**
safari

**Problem description**
https://github.com/phetsims/qa/issues/689

When the balloon is attracted to the sweater and moves towards it, a crackling sound is heard. It doesn't matter if the balloon is moving fast or slow. 
Issue is not seen with Mac11 + safari/chrome. 

**Steps to reproduce**
1. Remove wall
2. Move balloon over sweater and pick up some charges. 
3. Move balloon all the way to the right of the play area and release. 

**Visuals**
https://drive.google.com/file/d/1WEut39YR6_LJzXGAoNnOqOjQFo8TbCSa/view?usp=sharing 

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_all_phet.html
Version: 1.5.0-dev.35 2021-08-06 21:46:41 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
Language: en-US
Window: 1440x693
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by Nancy-Salpepi** [comment]
After the crackling noise occurred consistently for over 1 hr of testing, it has now stopped. I am not sure what, if anything, I am doing differently.

**Comment by jbphet** [comment]
I tried to reproduce this for a while on the iPad test device that I have, which is an unnamed A2270.  I just looked this model number up on the internet, and apparently it's an 8th generation device.

@Nancy-Salpepi - What device were you using for this testing?

**Comment by Nancy-Salpepi** [comment]
@jbphet I was using an older iPad pro but it has the most up to date iPados on it. It is my personal iPad and have never heard crackling before while watching videos/movies.

**Comment by jbphet** [comment]
Can I get the model number (it's usually on the back in very small letters)?

**Comment by Nancy-Salpepi** [comment]
model # ML3K2LL/A

**Comment by jbphet** [comment]
The model number above is from a 3rd generation iPad, so it's definitely a bit older, but still a device that I think we support.  I suspect that the audio rendering thread isn't quite keeping up, and that's what's causing the glitches in the sound.  I put some temporary logging into the code and found that the playback rate was being changed a lot when the balloon was drifting, so I thought I'd try two things:

1. Cancel any outstanding changes to the playback rate whenever changes are made so that we don't have competing changes
2. Use a thresholding mechanism to change the value less often

I regression tested these changes on my Win10 system using Chrome, and it seemed to work well, and the logging showed that the playback rate was being changed far less frequently.

@Nancy-Salpepi - Since I can't duplicate the problem locally, can you please test the master version on your iPad and see if the changes I've made have had an impact?  Thanks.

**Comment by Nancy-Salpepi** [comment]
The first 6-7 minutes were perfect @jbphet. I was just about to stop testing when the crackling started again. I had been switching between using 1 and 2 balloons. Since my initial test, I was sent a PhET iPad--iPad air 2 model # MGLW2LL/A and after several minutes of testing, I heard no static....so it is definitely my older model that is the problem.

**Comment by jbphet** [comment]
I've added code that applies the same thresholding technique to output level changes, since these were happening very frequently as well.  @Nancy-Salpepi - Please test the master version with the older iPad again and see if the situation has improved any further.

**Comment by Nancy-Salpepi** [comment]
After 11 minutes of testing, I didn't hear 1 crackle! Awesome job!

**Comment by jbphet** [comment]
> After 11 minutes of testing, I didn't hear 1 crackle!

Awesome!

@Ashton-Morris, @emily-phet, and I reviewed this change during today's sound design meeting, since there is a small impact on the behavior of the sound, and we collectively agreed that it's fine and we can move to RC with this.

**Comment by Nancy-Salpepi** [comment]
Tested the older iPad Pro (3rd generation) for 15 minutes and didn't hear any crackling. No crackling was heard on the iPad Air 2 either with 1 hour of RC testing. Both were OS 14.7.1
