### ISSUE TITLE
Balloon pointer area can block reset-all button

### ISSUE THREAD

**Issue by DevonQui** [phetsims/balloons-and-static-electricity#529]
**Test device**
MacBook Pro

**Operating System**
Big Sur 11.5

**Browser**
Chrome

**Problem description**
This is for https://github.com/phetsims/qa/issues/689

If you move either of the balloons to the rightmost bottom corner, you'll notice that the balloon only partially covers the orange reset all button so it should still be clickable. However, if you try to click it it's blocked by the balloon. Upon inspection of the showPointerAreas query, I noticed that the clickable area extended beyond the pointer area shown with the query.

**Steps to reproduce**
1. Open simulation
2. Drag balloon to the rightmost bottom corner
3. Try to click the orange-reset all button and notice that you can't

**Visuals**
https://drive.google.com/file/d/1QFJutKZ00s2cEv7cSayVHyOHk3JGQDFr/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_all_phet.html
Version: 1.5.0-dev.35 2021-08-06 21:46:41 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Language: en-US
Window: 1440x736
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jessegreenberg** [comment]
Thanks @DevonQui - I think this may be the same as https://github.com/phetsims/balloons-and-static-electricity/issues/522, does that seem right to you @DevonQui? Does this seem resolved in master?

**Comment by DevonQui** [comment]
@jessegreenberg that is the same issue, didn't see that. I will check in master just for double confirmation that the issue has been resolved and close.

**Comment by jessegreenberg** [comment]
Thanks! The pointer areas don't perfectly align with the balloon shape but they should be relatively elliptical and adhere to the shapes shown by ?showPointerAreas.

**Comment by DevonQui** [comment]
Okay, everything checked out in master. Closing
