### ISSUE TITLE
Noise Bug when Toggling Between One and Two Balloons

### ISSUE THREAD

**Issue by DevonQui** [phetsims/balloons-and-static-electricity#530]
**Test device**
MacBook Pro

**Operating System**
Big Sur 11.5

**Browser**
Chrome

**Problem description**
This is for https://github.com/phetsims/qa/issues/689

I noticed that if you toggle the sim from two balloons to one balloon while the green (second) balloon is still moving, the sim will continue to make noise as if the green balloon is still moving.

**Steps to reproduce**
1. open the sim
2. toggle the sim so that it has two balloons
3. take the green balloon and rub it against the sweater to gather a few electrons
4. remove the wall
5. drag the green balloon away from the sweater and allow it float towards the sweater
6. while the green balloon is still moving, toggle the amount of balloons back to just one balloon and notice that the sim is still making noise as if the green balloon was still floating.

**Visuals**
https://drive.google.com/file/d/1HcWhOgmV9bVFwmQ08zDk6kIkvlhOs0F_/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-dev.35/phet/balloons-and-static-electricity_all_phet.html
Version: 1.5.0-dev.35 2021-08-06 21:46:41 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
Language: en-US
Window: 1440x736
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

**Comment by jbphet** [comment]
Nice one @DevonQui!  This should definitely be fixed before publication.  I'm on it.

**Comment by jbphet** [comment]
I've used the balloon model's `isVisibleProperty` as an enable-control property for the sound generator.  Based on my initial testing, this seems to fix the issue.

**Comment by jbphet** [comment]
Unassigning, will make sure this is verified in the next round of QA testing.

**Comment by Nancy-Salpepi** [comment]
I was unable to reproduce this issue using Mac + chrome/safari.
