### ISSUE TITLE
Update credits for 1.5 release

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#537]
The 1.5 release branch has been created and the sim is going through RC testing at the moment.  @KatieWoe - please let me know (in this issue) which QA testers should be added to the credits so that I can update them before publication.

**Comment by KatieWoe** [comment]
Kathryn Woessner, Logan Bray, Nancy Salpepi, and Emily Miller should be added

**Comment by jbphet** [comment]
The update has been made on both the 1.5 branch and master.

**Comment by jbphet** [comment]
Note that due to the workaround that was put into place for https://github.com/phetsims/balloons-and-static-electricity/issues/555 there may now be line breaks between the first and last names of the QA testers.

**Comment by jbphet** [comment]
1.5.0 is deployed, credits should be in good shape.  Closing.
