### ISSUE TITLE
Sound decoding issues on MacOS Catalina and Safari 15

### ISSUE THREAD

**Issue by jbphet** [phetsims/balloons-and-static-electricity#545]
The parent issue for this is https://github.com/phetsims/tambo/issues/151.  The short version of the story is that there is an issue with decoding MP3 files in Safari 15 when running on MacOS Catalina, and this problem can cause a sim to crash.  

We are fixing this problem in a maintenance release, so there shouldn't be any specific effort needed for this sim, but I wanted an issue that we could use to make sure this is verified in the next release.

**Comment by Nancy-Salpepi** [comment]
The sim successfully opens with MacOS Catalina + Safari with partial sound--rub balloon on sweater/wall, collect charges, released charged balloon floats towards wall/sweater. 

The sounds that currently do not work are too many to list here, but are all the .mp3 files in the BASE Sound Design Document found in Google Drive.
