### ISSUE TITLE
xhtml sim freezes when "About..." in PhET menu is selected

### ISSUE THREAD

**Issue by stemilymill** [phetsims/balloons-and-static-electricity#555]
Win10 Firefox and Chrome. For https://github.com/phetsims/qa/issues/721.

Clicking or selecting with keyboard nav "About..." in the PhET menu freezes the sim. This happens in every dev/rc version I've tested, but not in dev/rc versions of other recent sims (fourier, pH scale, etc)

https://user-images.githubusercontent.com/85511101/138527854-a9c03998-9a16-47b4-bb42-76a9133fbf13.mp4

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Balloons and Static Electricity‬
URL: https://phet-dev.colorado.edu/html/balloons-and-static-electricity/1.5.0-rc.2/phet/xhtml/balloons-and-static-electricity_all.xhtml
Version: 1.5.0-rc.2 2021-10-11 21:55:48 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0
Language: en-US
Window: 1408x668
Pixel Ratio: 1.3636363636363635/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by KatieWoe** [comment]
Looks good on Win 11, rc.3
