### ISSUE TITLE
(Interactive Description) Spelling mistake in "Balloon Settings

### ISSUE THREAD

**Issue by terracoda** [phetsims/balloons-and-static-electricity#559]
![image](https://user-images.githubusercontent.com/1902116/140578904-e8cc4bee-f581-423e-b0f2-876116cbb678.png)

Please remove the extra "t" in "Settings" in the H3 "Balloon Settings" in the Control Area.

What a sneaky typo, you can't easily hear it when using screen reader software. This typo must have been around for years.

**Comment by terracoda** [comment]
I am not sure it should block since there is little to no effect on the user experience. It would just be nice get this simple fix in before republication if that is possible.

Please reduce priority and just fix for the next maintenance release if this at all complicates the upcoming release of the this sim.

**Comment by jbphet** [comment]
I fixed the type on master and cherry-picked the commit to the 1.5 branch.

**Comment by Nancy-Salpepi** [comment]
Spelling error has been corrected.
