### ISSUE TITLE
"Looping" sound not heard when sim is initially launched in Studio Wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/balloons-and-static-electricity#561]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Chrome

**Problem description**
When testing https://github.com/phetsims/phet-io/issues/1626 in master, I noticed an inconsistency in sound between the Studio and State Wrappers. In the State wrapper, if I set the state while the balloon is in motion, I hear the associated sound in the downstream sim (as expected). However, if I launch the sim in Studio while the balloon is in motion, the sim launches without the sound. Clicking anywhere on the screen will turn the sound on.

With Mac + Safari, the sim launches with sound on. 

As per MK's recommendation, I am not assigning to any developer at this time. 

**Steps to reproduce**
In Studio:
1. Remove Wall
2. Rub balloon on the sweater to gather a few electrons
3. Release the balloon far from the sweater
4. Press 'preview sim' -- the balloon is moving without sound
5. Click anywhere on the screen--the sound turns on

**Visuals**

https://user-images.githubusercontent.com/87318828/153526581-e7b6b7eb-4a28-485d-9948-0c4120ba36a4.mov

**Comment by KatieWoe** [comment]
Tested on Win 11 and I saw something similar to https://github.com/phetsims/fourier-making-waves/issues/217 here. On Chrome I reproduced this. On Firefox I did not.

**Comment by zepumph** [comment]
This is the identical issue as in https://github.com/phetsims/fourier-making-waves/issues/217#issuecomment-1051140400. Closing as a duplicate.
