### ISSUE TITLE
Discrepancy between wall.width and wallWidth

### ISSUE THREAD

**Issue by samreid** [phetsims/balloons-and-static-electricity#64]
While I was resolving https://github.com/phetsims/balloons-and-static-electricity/issues/63, I noticed that model.wall.width = 600 whereas model.wallWidth = 80.  What is the reason for this discrepancy, and should it be resolved?

**Comment by jessegreenberg** [comment]
Hmm, good point, Ill take a look at this.

**Comment by jessegreenberg** [comment]
At the moment, it looks like model.wallWidth is only used privately in BalloonsAndStaticElectricityModel.

**Comment by jessegreenberg** [comment]
And I actually don't see any usages of model.wall.width.

**Comment by jessegreenberg** [comment]
It looks like height is also not used?

**Comment by jessegreenberg** [comment]
```js
    // @private {number} - scaling factors for calculating positions for induced charge
    this.dx = Math.round( 80 / this.numX + 2 );
    this.dy = height / this.numY;
```

80 happens to be the width of the wall.

**Comment by jessegreenberg** [comment]
I removed model.wall.height, and replaced model.wall.width with model.wallWidth, so variables should be consistent now. Closing.
