### ISSUE TITLE
balloon jumps to a new location

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#67]
http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.0-rc2/balloons-and-static-electricity_en.html
All platforms.

Put the sim approximately in the state shown in the screenshot below: 2 ballons, both with charges, and no wall.  Then drag the yellow balloon directly on top of the green balloon.  The green balloon appears to jump to a new location without animating to that location; it will disappear and reappear somewhere to the right.  

This is probably because the model computes a large location delta in one time step. I recommend limiting that delta so that the balloons motion is always visible and it doesn't just jump somewhere.

![balloons](https://f.cloud.github.com/assets/3046552/975612/4a0b7e74-067c-11e3-8bb0-5044f641261a.jpg)

**Comment by samreid** [comment]
Since this is reported as fixed but needs testing, I'll mark it for S2015R.

**Comment by jessegreenberg** [comment]
This is no longer an issue in master or the published version:
https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html

Going through the steps in the original issue comment, the balloon will be forced off to the side but it doesn't jump without animation.

Closing.
