### ISSUE TITLE
performance is sluggish on Firefox + Win7

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#68]
Dragging balloons feels sluggish, even with 'no charges' selected.

Here's the diagnostics info:

Troubleshooting information

Name: Balloons and Static Electricity

URL: http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.0-rc2/balloons-and-static-electricity_en.html

Version: 1.0.0-rc2

Features missing: flexbox, touch

User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0

Language: en-US

Window: 1066x671

Pixel Ratio: 1/1

**Comment by ariel-phet** [comment]
Sim on master looks absolutely fine on master. Tested on 5/15/2018 on Win 7 FF.
