### ISSUE TITLE
performance is sluggish on Nexus7

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#69]
http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.0-rc2/balloons-and-static-electricity_en.html
Android 4.3
Chrome 28.0.1500.94
Firefox 23.0

Dragging the balloons is sluggish.

**Comment by samreid** [comment]
Closing until we have a bigger plan for Android.
