### ISSUE TITLE
aesthetics of "Remove Wall" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#70]
http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.0-rc2/balloons-and-static-electricity_en.html
All platforms.

Aesthetically, there could be a bit of whitespace between the "Remove Wall" button and the left edge of the wall. Better yet, center the button in the wall.

Here's what it looks like now:

![wall-button](https://f.cloud.github.com/assets/3046552/975899/cdba33be-0681-11e3-8ba3-5acc081b64ed.jpg)

**Comment by jessegreenberg** [comment]
Reviewed with @emily-phet @ariel-phet @terracoda. Agreed that the current look is OK. This issue can be closed.
