### ISSUE TITLE
Black bars on the sides!?

### ISSUE THREAD

**Issue by samreid** [phetsims/balloons-and-static-electricity#77]
Perhaps due to the change in default layout bounds, now there are black bars on the sides of this app on iPad3.  Doesn't look too great.

**Comment by jessegreenberg** [comment]
Agreed that the black rectangles at the edge of the sim look strange on all platforms with screens that go beyond layout bounds.
![black bars](https://cloud.githubusercontent.com/assets/6396244/10858791/46fcb24a-7f1d-11e5-9aaf-32f01a32657c.PNG)

**Comment by jessegreenberg** [comment]
> The side rectangles should stay because of the wall.

To clarify, it is because the wall image doesn't extend beyond the black rectangle on the right side. And if we were to make it wider, we would have to add additional charges which we do not want to do at this time.

**Comment by jessegreenberg** [comment]
It looks like there is more info about the rectangles in #54

//A black rectangle that vertically 'extends' the navbar from joist, see #54

**Comment by jessegreenberg** [comment]
Removing it has no impact when running with "dev" bounds. Here is what it looks like running in narrower layout bounds"

**Comment by jessegreenberg** [comment]
![capture](https://user-images.githubusercontent.com/6396244/40135148-c51497d6-5901-11e8-86dd-9f5006d099dc.PNG)

**Comment by jessegreenberg** [comment]
One option is to make the balloon tether point and wall bottom at the bottom of the layout bounds.

**Comment by arouinfar** [comment]
@jessegreenberg I think it would look a bit more natural if the sim contents didn't float up. Can we instead tack the dev boundary to the navbar? We did something similar in ESPB

![image](https://user-images.githubusercontent.com/8419308/40136302-bed622d8-5904-11e8-961f-4d66f8e9f595.png)

**Comment by jessegreenberg** [comment]
Great, thanks @arouinfar and @terracoda! Closing this issue.
