### ISSUE TITLE
Moving the balloons slowly does not pick up any charge.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balloons-and-static-electricity#78]
Moving the balloons slowly does not pick up any charge, and may instantly pick up charge from locations the balloon travel over.
Low priority.

**Comment by samreid** [comment]
Unassigning this for now. I'll reassign it when we start reworking this simulation for the Summer 2015 Redeploy.

**Comment by jessegreenberg** [comment]
> Moving the balloons slowly does not pick up any charge.

There is an explicit threshold that prevents a slowly moving balloon from picking up charges.

> and may instantly pick up charge from locations the balloon travel over.

I am not too sure what this means, and I haven't seen any spontaneous charge movement while digging around in here for a11y.  @arouinfar OK to close this?

**Comment by arouinfar** [comment]
👍
