### ISSUE TITLE
# of picked up charge is not conserved.

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/balloons-and-static-electricity#79]
The number of charges is not conserved when being picked up by balloons.

To reproduce select the two balloons option.
Take one balloon and pick up most of the charge and leave a few charges on the sweater(1-3 charges).
Take the second balloon and pick up the remaining charge.
The charges displayed on the balloon are less than the number of charges that were remaining on the sweater. 

![untitled](https://cloud.githubusercontent.com/assets/5631059/3330675/65379f54-f7d3-11e3-99e3-62e7feb0797d.png)

![untitled1](https://cloud.githubusercontent.com/assets/5631059/3330681/6c37f538-f7d3-11e3-8e72-b2e4a776aaf9.png)

**Comment by BryceAG** [comment]
I also noticed that if the second balloon picks up just one electron, although it doesn't show the spare electron it does react to the other balloon by repelling from it. Also if you have just one balloon and pick up just one electron, it still won't show up but will be attracted to the sweater. So the electrons are still counted as far as the forces are concerned

**Comment by jessegreenberg** [comment]
Thanks for catching this!  This was fixed in #131.
![conserved](https://cloud.githubusercontent.com/assets/6396244/13233287/4cceb2b0-d970-11e5-82f3-b6cead2261a3.PNG)

Closing.
