### ISSUE TITLE
Difficult to grab certain balloon when both are close together

### ISSUE THREAD

**Issue by bryo5363** [phetsims/balloons-and-static-electricity#80]
Test device:

Operating System:

Browser:

Problem description:When both balloons are in close proximity on the sweater, it is difficult to grab the lower balloon. 

Steps to reproduce
-Acquire a negative charge for both balloons (does not have to be equal)
-Set both on the sweater with one balloon higher than the other
-Align the cursor on the same horizontal axis as the bottom of the top balloon
-Move the cursor to the right or the left (while the cursor is still on top of the second balloon)
-If you click and drag at that point, even if the cursor is on the lower balloon, the top balloon will be dragged. 

Severity:

Screenshots:
![screen shot 2014-06-19 at 11 10 26 am](https://cloud.githubusercontent.com/assets/7717368/3330810/222e1ca4-f7d5-11e3-8fb4-782ed8ef65b2.png)

Troubleshooting information (do not edit):
Name: Balloons and Static Electricity
URL: http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.0-rc.5/balloons-and-static-electricity_en.html
Version: 1.1.0-rc.5
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36
Language: en-US
Window: 973x610
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jessegreenberg** [comment]
This was fixed by #279 and #281.  Closing.
