### ISSUE TITLE
Positions of balloons are not maintained when switching from one balloon to two

### ISSUE THREAD

**Issue by bryo5363** [phetsims/balloons-and-static-electricity#81]
Switching from two balloons to one balloon then back to two balloons will cause one of the balloons to move away from the original positions.

Steps to reproduce
-Distribute charges evenly (or relatively close) between the two balloons
-Place the two balloons in the same location (one overlapping the other)
-Make sure they do not deviate from the location
-Switch to one balloon and back to two balloons
-One of the balloons will move from the location

**Comment by jessegreenberg** [comment]
I will see if I can reproduce the problem.

**Comment by jessegreenberg** [comment]
@emily-phet and @jessegreenberg tried to reproduce the problem and could not. Closing.
