### ISSUE TITLE
website thumbnail is not checked in

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#85]
It should be assets/balloons-and-static-electricity-128.png

**Comment by samreid** [comment]
We should address this during summer 2015 redeploy, unassigning until then.

**Comment by pixelzoom** [comment]
This refers to an old convention.  We no longer use `<repo>-128.png` files, we use `<repo>-screenshot.png`, and this sim has that file.

Closing.
