### ISSUE TITLE
Download file only 1kb and not working from main website

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/balloons-and-static-electricity#96]
I was just trying to provide some emergency access to the sims for tomorrows downtime, and found that the download of balloons and static electricity was not working. Assigning to Aaron to look into to see why it isn't a good download.

**Comment by samreid** [comment]
For reference, here is the entire HTML file when you click download:

```html
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="initial-scale=1,user-scalable=no,maximum-scale=1"/>
    <title>Balloons and Static Electricity 1.0.0</title> <!-- Localized title will be filled in by JavaScript. -->
    <script type="text/javascript" src="balloons-and-static-electricity-preload.min.js"></script>
    <script type="text/javascript" src="balloons-and-static-electricity.min.js"></script>
</head>
<body bgcolor="black"><img id="splash" style="position: absolute;top: 50%;left: 50%;margin-top: -180px;margin-left: -252px;" src="images/joist/phet-logo-loading.svg">
</body>
</html>
```

**Comment by aaronsamuel137** [comment]
Looks like balloons-and-static-electricity uses an old version of the build process?

Here's the files on the server:

```
-rw-rw-r-- 1 tomcat phet    699 Aug 16  2013 balloons-and-static-electricity_en.html
-rw-rw-r-- 1 tomcat phet 356763 Aug 16  2013 balloons-and-static-electricity.min.js
-rw-rw-r-- 1 tomcat phet 185394 Aug 16  2013 balloons-and-static-electricity-preload.min.js
```

Seems like it works live and not as a download because balloons-and-static-electricity_en.html depends on these other files, as opposed everything being bundled in one html file.

I don't know how to fix this except to redeploy with the sim with new build process. Can someone more familiar with the old build process comment?

**Comment by samreid** [comment]
Consensus: Increase priority for summer 2015 redeploys.

**Comment by samreid** [comment]
New consensus: inline the external files into the HTML so it will work with a single file.  @kathy-phet asked @jonathanolson to look into this.

**Comment by samreid** [comment]
I marked this as High Priority since it is essentially a "will not launch" bug for people trying to use the download button for this sim.

**Comment by jonathanolson** [comment]
Single-file solution prepared at http://phet.colorado.edu/sims/html/balloons-and-static-electricity/1.0.1/balloons-and-static-electricity_en.html (increased maintenance version number). @ariel-phet, do we want the testers to run through platforms with it?

I can talk with @aaronsamuel137 whenever we want to switch it over to this version.

**Comment by jonathanolson** [comment]
Also, I'd like to point out that there are release candidates for 1.1.0 (http://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.1.0-rc.5/balloons-and-static-electricity_en.html is the latest) that were never published. That's probably why I thought we had a newer version on the website.

We could alternatively test 1.1.0-rc.5 and deploy that.

**Comment by ariel-phet** [comment]
I think we should just do this as part of the S2015R and just bump up priority of this redeploy, so we address issues and RC test properly. Considering that nobody has written phethelp about this particular sim, I think if we fix within a reasonable timeline we do not need to push an untested maintenance release immediately.

**Comment by kathy-phet** [comment]
Ariel, Can you elaborate on what you are considering a reasonable
    timeline? 
    K
    
    On 10/8/2015 11:53 AM, Ariel Paul
      wrote:
    
    
      
      I think we should just do this as part of the S2015R and just
        bump up priority of this redeploy, so we address issues and RC
        test properly. Considering that nobody has written phethelp
        about this particular sim, I think if we fix within a reasonable
        timeline we do not need to push an untested maintenance release
        immediately. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by ariel-phet** [comment]
That depends on when @samreid has addressed open issues, but we can make it a high priority for RC testing once open issues are addressed. 1 month or so would be a guess. 

It was unclear to me if we can just put a downloadable file that matches the one this currently up there or not? @jonathanolson @samreid can you comment?

**Comment by jonathanolson** [comment]
I believe @samreid estimated about a weeks' worth of work to resolve open issues.

> It was unclear to me if we can just put a downloadable file that matches the one this currently up there or not?

Nope, the same HTML file is used for online running and download.

**Comment by pixelzoom** [comment]
@jonathanolson has manually patched the files that are currently on the website, it's version 1.0.1. @ariel-phet said to create a minimal test task.

**Comment by jonathanolson** [comment]
(created minimal test task, linked above).

**Comment by samreid** [comment]
Reassigning to @ariel-phet until https://github.com/phetsims/tasks/issues/386 is complete.

**Comment by ariel-phet** [comment]
no going to fix at the moment...will fix upon redeploy of this sim.
