### ISSUE TITLE
Add download button back on redeploy

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/balloons-and-static-electricity#98]
Because the download file for this sim doesn't work, @ariel-phet has suggested I remove the download button from the website. This was done in: https://github.com/phetsims/website/commit/ff4d2f6327b144acdf521d8451874008fc2714d4

Once this sim is redeployed, we'll want to revert that commit.

**Comment by mattpen** [comment]
Has the download file for this sim been fixed yet?  I applied another workaround for this issue in https://github.com/phetsims/website/commit/fd1a9ab1f3600009d2b0d5460fa5092f7bbbad08

**Comment by lukeadams** [comment]
Any word on this? I don't want to set up the build system but what would stop us from embedding all of the resources in the HTML file like all of the other (downloadable) HTML5 sims? Base64 encode images, etc.

**Comment by pixelzoom** [comment]
@jessegreenberg Please follow up on this issue after the sim is published.

**Comment by jessegreenberg** [comment]
1.1.0 has been published.  https://github.com/phetsims/website/issues/392 was created to track adding back the download button.

**Comment by jessegreenberg** [comment]
Download button has been added back via https://github.com/phetsims/website/issues/392.  Download file is working again, closing.
