### ISSUE TITLE
DragListener does not call custom Translate function

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/balloons-and-static-electricity#99]
I notice in BalloonNode that there is a translate function in the instantiated DragListener, but translate is never called in balloons-and-static-electricity/view/DragListener.  It looks like the BalloonModel is trying to check model against position restrictions in the translation, but this is never happening.

**Comment by jessegreenberg** [comment]
I am a little confused with the purpose of DragListener.  The top level comment is 

```js
/**
 *Copied from SimpleDragHandler on 6-15-2013.  This drag listener keeps the mouse in the same     *relative location and respects constraints.
**/
```

Can't SimpleDragHandler handle such restrictions? Why is this separate and copied DragListener necessary?

**Comment by samreid** [comment]
In the above commit, I'm using MovableDragHandler instead of a stale copy of SimpleDragHandler, it seems like it works perfectly.  Reassigning to @jessegreenberg to double check that the new behavior is good and in case he needs to do anything with other balloons-and-static-electricity branches.

**Comment by jessegreenberg** [comment]
Thanks @samreid, replacing with MovableDragHandler works very well.  I merged the commit above into the accessible-instance branch.  Closing.
